### ISSUE TITLE
Reply to issue with plan. Originally sent on spigotmc.org.

### ISSUE THREAD

**Issue by redhcp91** [Rsl1122/Plan-PlayerAnalytics#1]
Hey, sorry to send this here. I tried to reply on spigotmc.org but for some reason the site keeps throwing a spam error at me for the past 6 hours. 

===================================================================

# **Reply to:**

_Hello. Nice to hear that this plugin will be useful :)
Hopefully we can figure this problem out soon so you can get to the more important tasks of server management :)_

_Edit: I wrote the debug thing a bit earlier and apparently didn't send it, so you can ignore it if this works:
I found out that there were bugs in the code that caused the plugin to fail on Enable, if PlanLite was not installed - My fault, didn't do proper testing._

_However I have now fixed the bug and it should solve your issues:
https://www.spigotmc.org/resources/plan-player-analytics.32536/update?update=139412_

_-- Below debug message if it doesn't fix the issue --_

_Let's start by debugging:
Does the /plan command work on console? (If it does not, skip next step)
Have you given the permissions for the plugin (are you using a permission manager that restricts default permissions)?_ 
_Please send me your config settings
What server version are you using? (Spigot-1.9.4/Paper-1.11.2 for example)
Does the plugin spit any errors when it is enabled/commands are used?
Is your IP set in the server.properties - this is where the server IP is taken for the commands.
Webserver automatically gets the ip though, so it doesn't affect the webserver.
The webserver only accepts connections after data is cached, and only to certain addresses that display the data. This is to prevent possible attacks with the plugin._

_Try this: In the config set RefreshAnalysisCacheOnEnable to true and try to connect to the ip:8804/server after the console says the Analysis is complete:_

_If you can connect to the ip:8804/server it means the webserver is working, but the commands might need permissions
Is there another plugin with the /plan command? - Are you running an older version of plan (1.6.2) alongside with the newest version?
If all this fails, try to redownload the plugin and see if the problem persists, corrupt plugin.yml might cause the plugin to not register commands properly._
_Alright that should help figure out what the problem is. :)_

_The first issue is quite odd really, because the only thing I've written that might say /plan <name> is in the plugin.yml:_
_Code (Text):_
_commands:_
  _plan:_
    _usage: /<command> <name>_
    _description: base command_
_Second issue is most likely because of the explanation of blocking connections above._

_Hoping to hear back soon,_
_-Rsl_

_PS: The Older version of Plan (in december) was only a chatbox data checker for other plugins. (PlanLite if you need such thing) - This webserver one is as new as 4 days :D (released on 17th)_

===================================================================

# My Reply:

Looks like the update fixed the issue. All is working now from what I can tell!

Thanks for the help, and again for making the plugin. I've been looking for something like this for a while now. Been running a small 20-30 person whitelisted server and wanted an easy way to keep track of peoples comings and goings to figure out who's active and who's not. There are some plugins that have what I need as a feature, but not the actual purpose of the plugin. This looks like it's exactly what I was looking for, easy, lightweight and simple.
And yeah I did notice that this is brand new, I saw your post on the admincraft subreddit I believe. In fact until a few moments ago I didn't notice only like 200 total downloads and only 18 downloads of the bug fix update haha. So it's even newer than I thought.
One more thing, I decided to check out the test server you set up for the trying out the plugin. Not sure if you're aware, but people don't have permissions to use it. Only the commands help, analyze and lite show as being available. Figured I'd give you the heads up.

Thanks again,
Chris

PS: Here's a screenshot so you can see for yourself what's available: http://imgur.com/7290e8t

**Comment by Rsl1122** [comment]
Good to know that the fix worked!
Thanks for the heads up too, I think I might have messed something up with perms..
Closed ticket.
