### ISSUE TITLE
Feature request: Server name in title

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#100]
**Plan Version:** 3.2.1
**Server Version:** any
**Database Type:** any
**Command Causing Issue:** None

**Description:**
Add server name to title bar.

**Comment by Rsl1122** [comment]
> The html web pages of the plugin can be completely customized.  
> The plugin uses two .html files: analysis.html and player.html
> 
> If the /plugins/Plan/ folder contains either of the files, they will be used instead of the ones found inside the .jar. This means you can copy the html files from the jar to the folder and edit them.

https://github.com/Rsl1122/Plan-PlayerAnalytics/blob/master/documentation/HtmlCustomization.md

There is no setting for the server name in the current files (server.properties etc) that would be as straight forward as the IP. I can of course add a config setting for that in the next update.

Please clarify "in the title": 
`<title>` (Displayed as the name of the tab/browser window)
`<header>` This bar:

![Pic](http://puu.sh/w3GTb/a8b723d02c.png)

**Comment by SlimeDog** [comment]
I forgot about customization. I'll give that a go.

Either of these would do the trick:
> server.properties:server-name
server.properties:server-id

I suggest using one of those if there is no configuration setting. But a configuration setting would override.

In the <title></title> would be useful, but mostly I was thinking in the "Plan | Server Analysis" bar. I suggest:
> PLAN | _title of the actual page_

one of:
- Information
- Online Activity
- Sessions
- Playerlist
- Command usage
- Demographics
- Plugins

**Comment by SlimeDog** [comment]
Confirmed. Thanks for quick turnaround.
