### ISSUE TITLE
HTML question

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#102]
**Plan Version:** 3.2.1
**Server Version:** Spigot-1.11.2
**Database Type:** sqlite

**Description:**
I am experimenting with custom analysis.html. If I remove the genderPie, the player activity graphs contain no data.
**Steps to Reproduce:**

1. Edit analysis.html to delete or comment out
``` <!-- ```
``` <canvas id="genderPie" width="1000" height="600" style="width: 95%;"></canvas> ```
``` --> ```
2. Refresh the web page.
3. Observe that **_Player Activity - Last 24h_** is empty of data.

**Comment by Rsl1122** [comment]
You also have to remove the Javascript responsible for gender pie 

Look for document.getElementById("genderPie")
There should be variables called
ctxgenderpie
datagenderpie
And the one that actually draws the chart. 

If you're using Chrome, Ctrl+Shift+I opens the Dev console and you can inspect possible Javascript errors.

**Comment by SlimeDog** [comment]
Thanks.
