### ISSUE TITLE
Remain on current web page after refresh

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#103]
**Plan Version:** 3.2.1
**Server Version:** Spigot-1.11.2
**Database Type:** sqlite

**Description:**
Web page refresh reverts to **_Information_** page. IMO, it should continue to display the current page, refreshed.

**Steps to Reproduce:**

1. Navigate to any PLAN page not **_Information_**.
2. Refresh the page.

**Proposed Solution:**
Remain on the current page.

**Comment by Rsl1122** [comment]
The problem here is that the navigation is controlled by javascript & the address bar doesn't contain information about the current tab.
I'll google around & see what I can do though.

**Comment by SlimeDog** [comment]
Confirmed. Thanks for quick turnaround.
