### ISSUE TITLE
Feature request: Refresh on player pages

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#105]
**Plan Version:** 3.3.0
**Server Version:** Spigot-1.11.2
**Database Type:** sqlite

**Description:**
Does %refresh% make sense on the player pages? It is not recognized.

**Steps to Reproduce:**
1. Introduce
``` Last Refresh: %refresh% ago ```
in _player.html_
2. Refresh page
3. Note that page displays
``` %refresh% ```
rather than time since refresh.

**Proposed Solution:**
Same as _analysis.html_

**Comment by Rsl1122** [comment]
Refresh is not currently on the inspect page because the time the data was placed into InspectCache is not saved anywhere.
