### ISSUE TITLE
Refresh not refreshed on tab change

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#106]
**Plan Version:** 3.3.0
**Server Version:** Spigot-1.11.2
**Database Type:** sqlite

**Description:**
Refresh indicator is not refreshed on tab change

**Steps to Reproduce:**
1. Display _analysis.html_
2. Change tab
3. Note that page displays same value

**Proposed Solution:**
Refresh value on tab change.

**Comment by Rsl1122** [comment]
The refresh indicator time is calculated when replacing the placeholders (when the html is served)

https://github.com/Rsl1122/Plan-PlayerAnalytics/blob/master/Plan/src/main/java/com/djrapitops/plan/utilities/PlaceholderUtils.java#L54

It would require writing a new javascript that does the same as the java method.
I'll keep it in mind though. (It would be cool to have it count the seconds in real time)
