### ISSUE TITLE
Player activity graph displaying incorrect data.

### ISSUE THREAD

**Issue by mibby** [Rsl1122/Plan-PlayerAnalytics#113]
Plan 3.4.1
Paper dev 1104 (Spigot 1.11.2)
MySQL Database

I did reload via ```/plan reload``` a couple of times, but not sure why the data would spike upwards.
![link](http://i.imgur.com/pqrn4Lv.png)

**Comment by Rsl1122** [comment]
The graph is drawn using sessions, sessions need to be saved each time the plugin is disabled, and new sessions will be started when the plugin is enabled for those that are online.

The extra sessions will be combined in the future (After I figure out a way to do so)
