### ISSUE TITLE
Session Length calendar

### ISSUE THREAD

**Issue by mibby** [Rsl1122/Plan-PlayerAnalytics#115]
Would it be possible to allow for a longer session tracking so you can see how active players are for the entire month rather than limit it to Monday - Sunday?

**Comment by Rsl1122** [comment]
You mean the Punchcard right?
That but for days of the month?

![Picture](https://puu.sh/w9tYZ/2208231460.png)

**Comment by mibby** [comment]
Oh, the information scales up in the web display? This is all I see.
![link](http://i.imgur.com/QGHzoM4.png)

**Comment by Rsl1122** [comment]
It's a screenshot of only the punchcard on the left.
The data here is from a timespan of 30d for 1092 players

The punchcard displays when the sessions start & the bubbles are scaled relatively on the amount of session starts at that time.

**Comment by mibby** [comment]
@Rsl1122 Just to clarify, I'm looking for 30d punch cards for individual users, not the main server session itself. If possible, I'd like to be able to see every individual session of a user in a month, in date order, and be able to click on the punch card to see how long they were on that day.

**Comment by Rsl1122** [comment]
Best I can do is a table with playtime for each day. I'm guessing you would like to use this feature to track how much your staff plays.

I can't really make anything that can be clicked on in the browser other than links / tables (because of the server in use requires a lot of work to add new responses).

The API & Html pages are quite flexible though, so someone with more javascript know-how might be able to create such graph.

**Comment by mibby** [comment]
>  I'm guessing you would like to use this feature to track how much your staff plays.

Exactly. :) I used OnTime prior to measure how much activity staff members logged daily / weekly / monthly and how much AFK time, but that plugin is not actively in development and causes quite a bit of performance hit. Being able to check how active individual staff members are in a day and week would be nice to have, don't necessarily need to measure AFK time.

**Comment by mibby** [comment]
Any idea on the direction you would like to go with for a session length calendar? :) Still would greatly appreciate a way to monitor staff hours for their individual logins in a day of a month.

**Comment by Rsl1122** [comment]
High charts has map that might work, if not I'll look for another js library that allows values per date.

**Comment by Rsl1122** [comment]
Found this library [FullCalendar](https://fullcalendar.io/) that might do the trick.
I'll look into this after 4.1.0
