### ISSUE TITLE
Player inspecting is case sensitive.

### ISSUE THREAD

**Issue by mibby** [Rsl1122/Plan-PlayerAnalytics#117]
It seems inspecting players is case sensitive.

```/plan qinspect <name>```

If you have someone named Dr_Dumpling, you can't type ```/plan qinspect dr_dumpling``` to pull up their info. You must type ```/plan qinspect Dr_Dumpling```. Since no two players can have the same name, would it be possible to allow for case insensitivity?

**Comment by Rsl1122** [comment]
Currently the cause for case sensitivity is the use of UUIDFetcher for the uuids:
https://github.com/Rsl1122/Plan-PlayerAnalytics/blob/master/Plan/src/main/java/com/djrapitops/plan/utilities/UUIDFetcher.java

I guess it would be possible now that Bukkit data (playername as well) was moved to the database (in version 3.3.0)

**Comment by Rsl1122** [comment]
In the meantime, /plan search is case insensitive.
