### ISSUE TITLE
Display year in qinspect registration date.

### ISSUE THREAD

**Issue by mibby** [Rsl1122/Plan-PlayerAnalytics#118]
The registered date does not seem to display the year the player joined the server. For me and some others specifically, ```/plan qinspect``` shows Mar 04 08:22:45. I wiped my map and player files last year, 2016, yet it doesn't reflect that my join date is from 2016.

**Comment by Rsl1122** [comment]
Just a formatting thing. 

If you order the player list on analysis page by registration it should take in account the year as well.

**Comment by mibby** [comment]
How would I order the player list on analysis for the quick in-game chat output inspect?

**Comment by Rsl1122** [comment]
I recognize that this is a suggestion for formatting the timestamp. 
I just gave an alternative if you need to know something related to the year that works in the current version.

**Comment by mibby** [comment]
@Rsl1122 Would it be possible to add a year time to the 'last seen' qinspect as well? As some people may have been last seen December of 2016, but without a date, could be mistaken for December of 2017 which doesn't make sense.
