### ISSUE TITLE
Last Refresh values NaN on page refresh

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#122]
**Plan Version:** 3.4.1
**Server Version:** Spigot-1.11.2 latest
**Database Type:** sqlite
**Command Causing Issue:** page refresh

**Description:**
On page refresh, _Last Refresh_ values display NaN, then load the counter.

**Steps to Reproduce:**

1. Refresh page
2. Observer NaN (briefly) then counter.

**Comment by Rsl1122** [comment]
I did notice that, I dunno what is causing it though - I think it is related to it trying to format a 0 with Math.floor but I'm not sure because it is javascript.

I was just uploading the update 3.4.2 so this will unfortunately be pushed to 3.5.0

**Comment by Rsl1122** [comment]
Fixed by moving the 3 time variables inside the navigation script tag to the first 3 lines.
