### ISSUE TITLE
HTML uses hardcoded http links so it breaks https.

### ISSUE THREAD

**Issue by FrozenBeard** [Rsl1122/Plan-PlayerAnalytics#123]
it's 2017, everyone should be using Https! With this new export I was able to setup a subdomain with nginx and symbolic link my export directory! The issue is the website uses hardcoded http links, so any images or resources on the website with hard coded http links then breaks the https green lock.

This is called "Mixed Content" you just have to use Protocol Relative URL's when linking resources and images.

Thank you.

**Comment by Rsl1122** [comment]
I'll try to figure something out.

**Comment by Rsl1122** [comment]
Introduced a setting for setting protocol for the link the commands give & moved to relative protocol (//) in links on the pages.

Also changed existing external links (cravatar, scripts, puush images) that were not using https to use https.
