### ISSUE TITLE
Config option to name analysis.html to index.html

### ISSUE THREAD

**Issue by FrozenBeard** [Rsl1122/Plan-PlayerAnalytics#124]
I symbolic link my export directory, but the main file is called analysis.html instead of index.html like you usually would. can we please get a config option to rename analysis.html to index.html when its created please?
By default this should really be index.html.

**Comment by Rsl1122** [comment]
Will be moved to /exportfolder/server/index.html so that the link given by commands will work.

**Comment by Rsl1122** [comment]
3.4.3 will export analysis html to /server/index.html
