### ISSUE TITLE
Time formats

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#126]
**Plan Version:** 3.4.2 and previous
**Server Version:** Spigot 1.11.2 latest
**Database Type:** sqlite

Time format
----

Current time format:
```
      Days: '%days%d '
      Hours: '%hours%h '
      Minutes: '%minutes%m '
      Seconds: '%seconds%s'
```
which I modify to:
```
      Days: '%days% days '
      Hours: '%hours%:'
      Minutes: '%minutes%:'
      Seconds: '%seconds%'
```
There are two problems:
1. 1 day (like 1 year) does not display properly.
2. Single-digit time elements do not display properly.

**Steps to Reproduce:**

1. Observe time fields.

**Proposed Solution:**
Add:
```
    Day: '1d'
    Time: 'hh:mm:ss'
```
which I will modify to:
```
    Day: '1 day'
    Time: 'hh:mm:ss'
```

**Comment by Rsl1122** [comment]
Added Day setting.

Added %zero% - If a Hour, Minute or Second settings contains it, a single '0' will be added in front of numbers from 1 to 9.
