### ISSUE TITLE
Legends: line instead of rectangle?

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#128]
**Plan Version:** 3.4.2
**Server Version:** 1.11.2
**Database Type:** sqlite

**Issue Caused by:** HTML

**Description:**
Chart legends are filled rectangles. I used unfilled lines in my charts, so it would be nice if the legends were lines rather than (filled) rectangles. (For example, **Players Online** in **Activity** page.) Is this possible?

**Comment by Rsl1122** [comment]
Do you have a picture? It would clarify :)

**Comment by SlimeDog** [comment]
Current activity display:
![activity-square](https://user-images.githubusercontent.com/17748923/27008651-2d062e86-4e2c-11e7-844d-c517e3f048cc.png)

Desired activity display:
![activity-line](https://user-images.githubusercontent.com/17748923/27008652-370b841c-4e2c-11e7-9195-a81e5f25ae1e.png)

**Comment by Rsl1122** [comment]
I'll have to see the documentation of chart.js.

**Comment by Rsl1122** [comment]
Unfortunately chart.js doesn't offer a simple solution to this.
The work put into the legend would not be worth the effort (Most likely would take couple of hours, if at all possible). - likely it would require writing custom legend generation code.

**Comment by SlimeDog** [comment]
No problem if it's beyond the pale. It was just an "ask if it's possible." Thanks for looking at it.
