### ISSUE TITLE
Feature request: ASkyBlock

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#138]
**Proposed Solution:**
Include data for ASkyBlock plugin.

**Comment by Rsl1122** [comment]
The requested plugin contains spaghetti code (Does not follow Single Responsibility Principle) & requires a new class that extends CommandSender to be created for getting the data. - This would still spawn a new async task per player every time analysis is run.

Other option would be to rewrite the level calculation code.

Thus this has been marked a low priority.

Code calculating the level:
https://github.com/tastybento/askyblock/blob/f8beec9860f9c25432715446bd3a19214511e036/src/com/wasteofplastic/askyblock/LevelCalcByChunk.java

**Comment by Rsl1122** [comment]
I have opened a ticket for the plugin's author to act on.
https://github.com/tastybento/ASkyBlock-Bugs-N-Features/issues/300

**Comment by Rsl1122** [comment]
The issue has been resolved & support will arrive in 3.5.0

**Comment by SlimeDog** [comment]
Yay!
