### ISSUE TITLE
Connections miscounted

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#157]
**Plan Version:** 3.5.0
**Server Version:** Spigot 1.12 latest
**Database Type:** sqlite

**Description:**
With default analysis.html, connection graph lists -1 or 0 connections, instead of 0 or 1, and the Y-axis baseline is -10.

**Steps to Reproduce:**

1. Update to Plan 3.5.0
2. Revert to default analysis.html (I have a custom file)
3. Run **/plan analyze**
4. Observe results

**Comment by Rsl1122** [comment]
Likely broken already in 3.4.3 as there have been no changes to calculation of the graph.

The source for the online players number will be changed in the code clean-up anyway so it will be fixed then.

**Comment by SlimeDog** [comment]
The issue did not exist in Plan 3.4.3 (for me).

**Comment by SlimeDog** [comment]
Please release with this fix. Without correct player counts, _Plan_ is practically unusable.

**Comment by Rsl1122** [comment]
Current fix has ~80000 points per 24h - the number has to be brought down before the fix can be uploaded.

The update will be ready in 1-2 days.

**Comment by Rsl1122** [comment]
The algorithm I wrote made the graph look ugly so I decided to push that to 3.5.3
Update is live.
