### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by BlackBeltPanda** [Rsl1122/Plan-PlayerAnalytics#16]
Using a MySQL Database on the same machine.

Whenever Plan loads, the entire server hangs until it's finished. I'm also getting large lag spikes when players login and a considerable amount of lag from PlanPlayerMoveListener: https://timings.aikar.co/?id=61d937347e154c979207526516e8fe79

The analyze command always times out and the inspect command takes a couple minutes to return results. During these commands, the entire server hangs.

**Comment by Rsl1122** [comment]
Might be related to #14 and #13 
Try clearing the mysql database as it might contain corrupted data.

To disable location collection set Settings.GatherLocations to false in the config - I'll try to figure something for that.

As for the joining part, I know what is causing it & hopefully I'll figure something out for it in the next update.

**Comment by BlackBeltPanda** [comment]
K, looking forward to the fixes. Clearing the database didn't help, by the way; the problem started up again a few hours later.

**Comment by Rsl1122** [comment]
It might be that the mysql has a slow connection then, does it throw any errors on console when /plan analyze is run?

**Comment by BlackBeltPanda** [comment]
Aside from the previously mentioned errors, it simply times out when running the command.
MySQL connection's typically pretty fast. It's on the same dedicated server and has never given me any connection problems.
For now I've disabled the plugin.

**Comment by Rsl1122** [comment]
I looked into the backup DB you sent me and it has 114 users saved (525080 locations). Since the analysis grabs the data of each player one by one, that is why it times out. 
I'll have to add a way for the DB to grab all users at once, that should fix it (and to load the locations only when needed). :)

**Comment by Rsl1122** [comment]
Fixed in 091e3eb1c50dc5e95e5d2dba0a2ab0db2c9698d0
