### ISSUE TITLE
Player Activity graph scale in tenths

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#164]
**Plan Version:** 3.5.1
**Server Version:** 1.12
**Database Type:** sqlite

**Description:**
Scale of Player Activity graph is in tenths. This is weird, since players online is by definition an integer scale.

**Steps to Reproduce:**

1. Install Plan
2. Start server
3. Navigate to any player page
4. Observe scale of **Player Activity: 7d**

**Proposed Solution:**

Make scale integer.

----

![untitled](https://user-images.githubusercontent.com/17748923/28047493-437abd82-659f-11e7-875e-35c3aac4bd41.png)

**Comment by Rsl1122** [comment]
This is decided automatically by chart.js, if you want it to change to an integer you have to write a callback function for Y-axis labels, check the bubble chart for an example.
