### ISSUE TITLE
HTTP/JS memory leak

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#165]
**Plan Version:** 3.5.1
**Server Version:** 1.12
**Database Type:** sqlite
**Browser:** Mac Safari

**Issue Caused by:** repeated page rendering

----

**Description:**
With automatic page refresh, footprint grows from 250MB at startup to over 1GB over the course of a day.

**Steps to Reproduce:**

1. Set page to auto-refresh:
>         <meta http-equiv="refresh" content="150">
2. Open page
3. Watch memory allocation grow.

**Proposed Solution:**
Find and fix memory leak.

**Comment by Rsl1122** [comment]
So is the memory leak in the server or the machine running the browser? 

I'm going to assume it is the server side Java code

**Comment by SlimeDog** [comment]
How could I help isolate it?

**Comment by Rsl1122** [comment]
> footprint grows from 250MB at startup to over 1GB
I just need to know which machine's memory this refers to, the one with the browser or the server running the plugin. (Or were you running both on the same machine?)
