### ISSUE TITLE
Reduce height of chart elements

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#166]
**Plan Version:** 3.5.1
**Server Version:** 1.12
**Database Type:** sqlite

**Issue Caused by:** Chart elements fill entire page height

----

**Description:**
Charts fill the entire page height. I would like them to consume less real estate, which I could use for other purposes. I have changed various height values, without success.

**Proposed Solution:**
Identify the variables that control the height of the chart elements. As as example, say I wanted the charts to be 75% of their current heights, so if there are two stacked vertically, that would leave 25% of the page (at the bottom) empty.

**Comment by Rsl1122** [comment]
Try to change the height css value of the "row" div you want to change height of.
If height doesn't work its because flex is resizing the component. I don't remember what the flex setting was. 
Here is a cheat sheet for flex http://www.sketchingwithcss.com/samplechapter/cheatsheet.html

**Comment by SlimeDog** [comment]
This did the trick:
```
            .main-limiter {
                margin-left: 15%;
                width: 85%;
                height: 90%; // used to be 100%
                overflow: hidden;
            }
```
