### ISSUE TITLE
Modify size of geolocation map

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#167]
**Plan Version:** 3.5.1
**Server Version:** 1.12
**Database Type:** sqlite

**Description:**
I have modified the display to geolocation map is the only element on that page. I would like to increase (double) the size of the map. Is that possible?

**Comment by Rsl1122** [comment]
Set the width of the element similar to player list tab. 
Unfortunately plotly doesn't make the map boundaries any bigger (when zoomed in there are borders).

I have tried to fix it but I haven't found the correct setting and cloropleth maps were not that well documented. 
https://plot.ly/javascript/choropleth-maps/

**Comment by Rsl1122** [comment]
Fixed in commit 3c63fde839dc2c893d172bdcb209b00190000e76
