### ISSUE TITLE
Island name extras

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#168]
**Plan Version:** 3.5.1
**Server Version:** 1.12
**Database Type:** sqlite

**Description:**
Island name displays extra characters.

**Steps to Reproduce:**

1. Navigate to player plugins page
2. Observe **Island name: rambeauÂ§r**

**Proposed Solution:**
Island name should be  **Island name: rambeau**.

**Comment by Rsl1122** [comment]
Do all island names have the same problem?

**Comment by Rsl1122** [comment]
Please also check if ASkyBlock's islandnames.yml (file) contains the same characters.

**Comment by SlimeDog** [comment]
I have only one island. This is a test server, only one player.

_islandnames.yml_ is empty.
