### ISSUE TITLE
Demographic triggers not removed from config

### ISSUE THREAD

**Issue by mibby** [Rsl1122/Plan-PlayerAnalytics#172]
Plan 3.5.2

@Rsl1122 Forgot to remove the DemographicsTriggers in the config with the age & gender gathering removal?

```
  DemographicsTriggers:
    Trigger: i'm, am, im, bin
    Female: female, girl, gurl, woman, gal, mrs, she, miss, feminin, weiblich, mädchen,
      frau
    Male: male, boy, man, boe, sir, mr, guy, he, männlich, maskulin, junge, mann
    IgnoreWhen: sure, think, with, are, you, din
```

**Comment by Rsl1122** [comment]
Ah just forgot to take them away from the config that's all

**Comment by mibby** [comment]
Demographic is also still in the html file.
https://github.com/Rsl1122/Plan-PlayerAnalytics/search?utf8=%E2%9C%93&q=demographic&type=

**Comment by Rsl1122** [comment]
The java docs are outdated.

**Comment by mibby** [comment]
Ah, alright. Just thought I'd point it out in case it was still used.
