### ISSUE TITLE
Unauthorized 401

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#173]
**Plan Version:** 3.5.2
**Server Version:** Spigot 1.12
**Database Type:** sqlite

**Issue Caused by:** 3.5.2 update configuration

----

**Description:**
```
401 Unauthorized

Authentication Failed.
- Ensure you have registered a user with /plan register
- Check that the username and password are correct
- Username and password are case-sensitive

If you have forgotten your password, ask a staff member to delete your old user and re-register.
```

**Steps to Reproduce:**

1. Update to Plan 3.5.2
2. Replace custom _analyze.html_ with default file
3. Start server
4. **/plan register _password_** returned that user was registered
5. **/plan web check** returned that user had level 0 permissions (all pages)
6. **/plan analyze** returned the correct link
7. Navigate to web page _<my.server.fqdn>:8804/server_

I am not prompted for user/password.

**Comment by Rsl1122** [comment]
When the webpage is opened it returns HTTP code 401 header (Unauthorized) with Authorization method Basic.
On chrome Basic prompts for user information:
![Login prompt](http://puu.sh/wQfCd/fa8c98ce11.png)

> Authorization required
localhost:8804 prompts for user and password
user:
password:
[Login] [Cancel]

What browser are you using?

**Comment by SlimeDog** [comment]
Mac Safari, with access controls. :(

With Firefox and Chrome, the URL also hangs. I do not get prompted for user/password.

**Comment by SlimeDog** [comment]
To clarify, the firewall is open for port 8804. Plan web access has worked fine through v 3.5.1.

**Comment by SlimeDog** [comment]
```
Temporary fix:
If you add <Username>:<password>@<my.server.fqdn>:8804/server it should log in without prompting.
```

Returns:
Safari can't open "username:password@my.server.fqdn:8804/server" because macOS doesn't recognize internet addresses starting with "username:"

(username, password, and FQDN masked herein)

**Comment by Rsl1122** [comment]
That is weird. 
I'll try to Google if I find something

**Comment by Rsl1122** [comment]
Well, fuck. 

> Windows Integrated authentication only works when the client is in the same domain or trusted domains. So make sure your clients are in intranet or via VPN.

Otherwise, clients cannot response to server challenges and you shall see 401 errors.

**Comment by SlimeDog** [comment]
I am connecting over the internet. No VPN. Obviously, not in the same domain. :(

**Comment by Rsl1122** [comment]
Could you enable debug logging to file so I can see what the Request-Response parsing is doing?
(Related to timeouts)

**Comment by Rsl1122** [comment]
It is not prompting because the authorization is running on http and Firefox, Chrome and Safari have prevented the prompts due to insecurity of Http.
I hoped that it would suffice because I have no clue about Https over sockets.

I'll have to convert the server to https or remove the prompt completely.

**Comment by SlimeDog** [comment]
Debug output:
```
[Jul 22, 10:07:41] New Socket Connection: /my.ip.address.masked
[Jul 22, 10:07:41] Webserver Response
[Jul 22, 10:07:41] Not Authorized.
[Jul 22, 10:07:41] Parsed response: PromptAuthorizationResponse
[Jul 22, 10:07:41] Webserver Response took 2 ms
[Jul 22, 10:07:42] New Socket Connection: /my.ip.address.masked
[Jul 22, 10:07:42] Webserver Response
[Jul 22, 10:07:42] Not Authorized.
[Jul 22, 10:07:42] Parsed response: RedirectResponse
[Jul 22, 10:07:42] Webserver Response took 1 ms
```

**Comment by Rsl1122** [comment]
Alright thanks

**Comment by SlimeDog** [comment]
Do you need more information from me?

**Comment by Rsl1122** [comment]
Ah no Thanks for the info. :)

**Comment by Rsl1122** [comment]
Https Server moved to a new issue, this issue has been resolved by removing the prompt temporarily.
