### ISSUE TITLE
Feature request: TPS graph colors

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#180]
**Description:**
Display TPS values in three configuration-determined colors, in three configuration-determined bands. For example, configuration:
```
TpsThresholdHigh: 18.00
TpsCeilingLow: 16.00
Colors.TPS.High: '00ff00'
Colors.TPS.Medium: '000000'
Colors.TPS.Low: 'ff0000'
```

Then, there are alerts...

**Comment by Rsl1122** [comment]
I can add a low tps alert messager, but I don't think Chart.js supports multiple colors for a line.
Might be mistaken. I'll look into it.

**Comment by Rsl1122** [comment]
Too difficult to implement multiple color graph. 
(Requires rewriting the code drawing the line for Javascript & I barely know js.)

**Comment by SlimeDog** [comment]
Thanks for looking.

**Comment by SlimeDog** [comment]
Is this possible with the switch to Highcharts?

**Comment by Rsl1122** [comment]
Yes.

**Comment by SlimeDog** [comment]
Cool. Waiting with bated breath. :)
