### ISSUE TITLE
Player playerChartWeek still line mode, should be scatter

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#183]
**Plan Version:** 3.5.4
**Server Version:** 1.12
**Database Type:** sqlite

**Description:**
Player 7 day activity table uses the old line version, which mis-displays the data.

**Steps to Reproduce:**

1. Navigate to Player Information page
2. Observe Activity chart

**Proposed Solution:**
Change to scatter version, like Analyze charts.

**Comment by Rsl1122** [comment]
I would have changed the source but TPS counter doesn't save who is online.
Will have to write a new method for making a scatter graph out of sessiondata.

**Comment by SlimeDog** [comment]
thanks.
