### ISSUE TITLE
Recent Logins links

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#186]
**Plan Version:** 3.5.4
**Server Version:** 1.12
**Database Type:** sqlite

**Issue Caused by:** Links using FQDNs instead of relative URLs

----

**Description:**
Links for players in Analysis Recent Logins list are FQDNs:
_my.server.com:8804_/player/_playerName_
These are incorrect on my test server, since they point to my production server.
How are the values for **%recentLogins%** generated?

**Steps to Reproduce:**

1. Navigate to Recent Logins
2. Hover to display links

**Proposed Solution:**
Use relative links: player/_playerName_

**Comment by SlimeDog** [comment]
Nevermind...misconfiguration. Values of %recentLogins% are generated based on config.yml values.

**Comment by Rsl1122** [comment]
Imma switch the links to use the relative link method.
