### ISSUE TITLE
Feature request: average CPU in period

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#195]
**Plan Version:** 3.5.5
**Server Version:** 1.12
**Database Type:** sqlite

New CPU charts are a great addition. Please add average CPU variables

- %averagecpuweek%
- %averagecpuday%

similar to TPS variables

- %averagetps% (should be %averagetpsweek% for clarity and consistency)
- %averagetpsday%

(I modified the headers to show the data, when available.)

**Comment by SlimeDog** [comment]
Thank you. The usual fast turnaround.

**Comment by Rsl1122** [comment]
Got to thank @fuzzlemann for that one :)
