### ISSUE TITLE
Smaller scatter points

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#199]
**Plan Version:** 3.5.5
**Server Version:** 1.12
**Database Type:** sqlite

How can I make the (scatter) points -- i.e., the virtual curve thickness -- smaller?

**Comment by Rsl1122** [comment]
borderWidth under data settings 
https://stackoverflow.com/posts/38395036/revisions

**Comment by SlimeDog** [comment]
Thanks.
