### ISSUE TITLE
AdvancedBans Support

### ISSUE THREAD

**Issue by Saboteurs** [Rsl1122/Plan-PlayerAnalytics#214]
I would love if you could att AdvancedBans support!

**Comment by Rsl1122** [comment]
I know this is a bit old ticket, but do you mean AdvancedBan? I couldn't find any other plugin with that exact name

**Comment by Rbot48** [comment]
It would be great if we could get the history and active warns of players from [AdvancedBan](https://github.com/DevLeoko/AdvancedBan) in the inspect page :)

**Comment by Rsl1122** [comment]
Closing the issue as the suggestion has been added to a multi-issue
