### ISSUE TITLE
Feature request: Local timezone in charts

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#215]
**Plan Version:** 3.6.0
**Server Version:** 1.12
**Database Type:** sqlite

**Description:**
Dates/times are displayed GMT.

**Proposed Solution:**
Display dates/times in local (or configured) timezone.

**Comment by Rsl1122** [comment]
Ah, yes. This was noticed but main focus was on converting all charts to use the new library first :)

**Comment by SlimeDog** [comment]
Agreed.

**Comment by Rsl1122** [comment]
http://api.highcharts.com/highcharts/global.timezoneOffset
