### ISSUE TITLE
Error 2.6.2 MySql

### ISSUE THREAD

**Issue by Bossbirdyman51** [Rsl1122/Plan-PlayerAnalytics#23]
Hi, 
thanks for the grat plugin !
Error with the last version of plugin 2.6.2
Error log : http://pastebin.com/qWPYmXRd

Thanks.

**Comment by Rsl1122** [comment]
Dem typos man xD

**Comment by Rsl1122** [comment]
Will fix in the next bugfix update

**Comment by Rsl1122** [comment]
Fixed:
https://www.spigotmc.org/resources/plan-player-analytics.32536/update?update=146302

**Comment by Bossbirdyman51** [comment]
Thanks and sorry for the typos

**Comment by Bossbirdyman51** [comment]
Ah okay, do you speak french no ?

**Comment by Rsl1122** [comment]
Sorry I don't speak French :)

**Comment by Bossbirdyman51** [comment]
Okay, and do you offer your service for dev ?

**Comment by Rsl1122** [comment]
Yeah, just depends on what :)
