### ISSUE TITLE
Player session PunchCard missing '12 am', instead reports as 1. Jan.

### ISSUE THREAD

**Issue by mibby** [Rsl1122/Plan-PlayerAnalytics#247]
Plan v3.6.2

![link](http://i.imgur.com/o6cD5xC.png)

**Comment by Fuzzlemann** [comment]
I cannot reproduce that error:
![image](https://user-images.githubusercontent.com/16463103/29250205-8e25fc0c-803e-11e7-89e2-7f5a78523fda.png)

We need more informaton, please send the Hastebin Dump Log (/plan m dump)

**Comment by mibby** [comment]
Dump failed on ```/plan m dump```.
> ```DumpLog.upload Caught java.io.IOException: Server returned HTTP response code: 400 for URL: https://hastebin.com/documents. It has been logged to Errors.txt```


Server session PunchCard (windows snap-resized to one side screen - 1280x1440)
![link2](http://i.imgur.com/LaLS24c.png)

Server session PunchCard (window fullscreen - 2560x1440)
![link3](http://i.imgur.com/rZyKdXs.png)

Different individual player session PunchCard (windows snap-resized to one side screen - 1280x1440)
![link4](http://i.imgur.com/WouvoNS.png)

Different individual player session PunchCard (windows snap-resized to one side screen - 1280x1440)
![link5](http://i.imgur.com/KFCUjux.png)


I also noticed some people have missing times in the x plot. I'm assuming it only adds a full 24-hour scale to the punchcard if they are online within a full 24 hour time period?

I'll update to  v3.6.3 and see if it resolves the issue.

**Comment by Rsl1122** [comment]
Yes the timestamps are all made by highcharts.

**Comment by mibby** [comment]
1. Jan still shows up as of v3.6.3 so updating didn't seem to fix the issue. 

```/plan m dump``` worked when typing in-game on the updated version so either it doesn't work from console due to the embedded chat json or was fixed in the latest release. Not sure what the dump would tell you though.
https://hastebin.com/usenadimob.http

**Comment by Rsl1122** [comment]
Possibly caused by the way highcharts handles dates when using custom labels, similar to here:
https://blog.emilecantin.com/web/highcharts/2014/10/26/highcharts-datetime-series.html

**Comment by mibby** [comment]
Anything I can do to correct this behavior or will you have to end up compensating for the way highcharts utilizes your labels? I use the default html formatting and labels..

**Comment by Rsl1122** [comment]
I'm just giving it UTC dates, will have to see what to do about it.

**Comment by mibby** [comment]
@Rsl1122 I updated to v3.6.4 but still see ```1. Jan``` in the main ```<ip>:<port>/server``` sessions tab and individual player inspect tab. Does the server / player have to be online at 12 AM to update the text graph?

**Comment by Rsl1122** [comment]
I tried to give the graph 24 instead of 0, but it seems that the issue is caused by something on Highcharts. I don't know if it can be fixed. 
I'll take another look at some point.

**Comment by Rsl1122** [comment]
Progress so far (The 24 instead of 0 solution)
![img](https://puu.sh/xfAId/d05f956225.png)

**Comment by Rsl1122** [comment]
If anyone comes accross this ticket while solving similar issue:
HighCharts requires a "day" dateTimeLabelFormats when formatting midnight.

```
dateTimeLabelFormats: {
                hour: '%I %P',
                day: '%H %P'
},
```
