### ISSUE TITLE
Feature request: World Playtime as table

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#248]
Spigot 1.12 and 1.12.1
Plan 3.6.3

Current output:
World Playtime graph, with pretty colors and labels

Proposed option:
A list of worlds, times, percentages; sometime like:

world | time | %
---------- | -------- | ------
world | 1:30:00 | 75.0%
world_nether | 0:10:00 | 8.3%
world_the_end | 0:20:00 | 16.7%
|  | 
Total | 2:00:00 | 100.0%

Times and percentages right-aligned, of course, and cognizant of _Customization.Formats.DecimalPoints_.

**Comment by Rsl1122** [comment]
I was thinking about adding the times to the tooltips of the slices if it is possible.

**Comment by SlimeDog** [comment]
Great, but I would actually prefer a table. :)

**Comment by SlimeDog** [comment]
Is it possible to construct a PlayerList type table from the current data feed?

**Comment by Rsl1122** [comment]
Not with current placeholders, but the data is in the database per player. 
That means that a table with players would be possible to make in the future, although it would be difficult to fit to the page with, say, more than 7 worlds. 

That said I currently feel like the storage of this data is inadequate and a better way would be possible with a different db structure (per session world times, each with what gamemode the user was in that world) 

Most likely all old data will be thrown away when the bungee version is developed. (Development will start after the next update)

**Comment by SlimeDog** [comment]
This would be excellent. Thoughts: Perhaps tabular display could be limited to a defined subset of worlds. Perhaps different subsets could be displayed in separate tables.

**Comment by Rsl1122** [comment]
I'll look into this after 4.0.0 update is finished.

**Comment by Rsl1122** [comment]
Is this suggestion still relevant? :)

**Comment by SlimeDog** [comment]
Per Aug 14 comment:
Great, but I would actually prefer a table. :)

I would prefer a table to the current pie chart, but it's certainly not the highest priority.

**Comment by Rsl1122** [comment]
Since I do not think this is going anywhere I have decided to open a more appealing implementation above (to me anyway) and close this issue.
