### ISSUE TITLE
Feature request: Better control of Highcharts output

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#249]
Plan 3.6.3

**World Playtime**
* Options for order of slices: alphabetic, percentage.
* Colors.

**Ticks Per Second**
* Order of sub charts.

**Resource Usage**
* Order of sub charts.

**World Load**
* Order of sub charts.

**Comment by Rsl1122** [comment]
Can't really add these config options for the line graphs:
- TPS graph reverse order breaks either Players Online graphs or date display on TPS graph
- Order is set in the dataset, not the chart - I think something else was defined in the chart like axis label

I'll look into the world pie.

**Comment by SlimeDog** [comment]
How about a _Dashboard_ page that includes the content of all three current _Performance_ charts, but stacked in a single chart and controlled by a single range selector?

- [ ] Players
- [ ] TPS
- [ ] CPU
- [ ] RAM
- [ ] Chunks
- [ ] Entities

**Comment by Rsl1122** [comment]
I'll see what I can do. 

Please note however that highstocks (the one with the range selectors) is more limited in terms of Y-axis & Y-axis labels. (One Y-axis per chart) 
It is possible to link the 3 chart's selector buttons together, and if the chart with all items is unusable, that will be done instead.

**Comment by SlimeDog** [comment]
Sounds good. That would solve the issue, which is to change the reporting range for all charts on the page. Since my expectation is that all results change with number of players, what I'm looking for is a dashboard with all the displays in the same timeframe.

**Comment by Rsl1122** [comment]
Here is an example of it in action:
http://puu.sh/xtRvO/bbcf2eedb4.gif

Please note that you probably have more interesting data than I have, since there are no players on this server. :)

**Comment by SlimeDog** [comment]
My server is still in test/development, so I have just two players, when I need them, to test things like this. :)

**Comment by Rsl1122** [comment]
Closing this one, #288 is still open.
