### ISSUE TITLE
Spacing of commands list

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#250]
Plan 3.6.3

List will (eventually) need vertical compression. There is too much space between lines.

**Comment by Rsl1122** [comment]
Could you send me a screenshot of what you mean with the space between the lines

**Comment by SlimeDog** [comment]
![plan](https://user-images.githubusercontent.com/17748923/29301991-242f25c4-8135-11e7-952e-7fdee8a01e26.png)

Lines could be packed much more tightly.

**Comment by Rsl1122** [comment]
Ah this is the 3.6.2 html version, change both command and player table to the one in 3.6.3 and that should fix the issue. (Adds a scrollbar & fixes issue where the table is stretched to 800px even with one row)

**Comment by SlimeDog** [comment]
I missed that in my **diff**. Mea culpa. That's much better.
