### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by Coll1234567** [Rsl1122/Plan-PlayerAnalytics#253]
Not sure if this is caused by plan, my configuration, or one of the other plugins I have but using /plan analyze always results in the following error: https://hastebin.com/jojefidoje.hs

Link: https://hastebin.com/aleyekufel

**Comment by Rsl1122** [comment]
Same cause as #232
Updated locale, fixed in the Plugin Bridge, got reverted before final build, some plugins cause this exception. 

No worries, it does not break anything other than the variable on plugins page it is related to.
