### ISSUE TITLE
Map Projection Selection (Html)

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#257]
Plan 3.6.3

Can we use different projections (eg., molleweide) with HighCharts maps? I read their documentation, but couldn't find the relevant bits.

**Comment by Rsl1122** [comment]
There is a script that loads the map data (projection) It is under the script that loads highmaps. 

Tutorial on setting the map collection:
https://www.highcharts.com/docs/maps/map-collection
Find different projections here:
http://code.highcharts.com/mapdata/

**Comment by Rsl1122** [comment]
Assumed answered, add comments for further assistance

**Comment by SlimeDog** [comment]
Thanks. The default projection you selected is the best of those available from highcharts. They don't have a Mollweide projection.

**Comment by Rsl1122** [comment]
Since it uses geojson it might be possible to use some provided by other sources. 
I found this that might be mollerweide. I'll test if it works after I get up from bed :D
https://github.com/d3/d3-geo/blob/master/test/data/world-50m.json

**Comment by Rsl1122** [comment]
Oh, it wasn't showing as a map on mobile, I guess the example used some other method of turning it into a different projection. Couldn't find any others.

**Comment by SlimeDog** [comment]
No worries. The default is just fine.
