### ISSUE TITLE
Error while reloading?

### ISSUE THREAD

**Issue by Louis-D** [Rsl1122/Plan-PlayerAnalytics#258]
**Description of the issue**
I reloaded the plugin using /plan reload to try to figure out if using ../ for the path will work and the plugin
crashed the entire server.

**Hastebin link**
Link: https://hastebin.com/pujacerupo.md

**Comment by Rsl1122** [comment]
> [16:43:10 INFO]: [Plan] Shutting down Webserver..
> [16:43:10 INFO]: [Plan] Saving cached data..
> [16:43:10 INFO]: [Plan] Player Analytics Disabled.
> [16:43:10 INFO]: [Plan] You're running the latest version
> [16:43:10 INFO]: [Plan] Using Locale: Default (EN)
> [16:43:10 INFO]: [Plan] Database init..
> [16:43:13 ERROR]: [Plan] main.java.com.djrapitops.plan.data.cache.DataCacheHandler Caught org.sqlite.SQLiteException: [SQLITE_BUSY] The database file is locked (database is locked). It has been logged to Errors.txt
> [16:43:13 ERROR]: [Plan] **main.java.com.djrapitops.plan.database.tables.VersionTable Caught org.sqlite.SQLiteException: [SQLITE_BUSY] The database file is locked (database is locked). It has been logged to Errors.txt**
> [16:43:13 ERROR]: [Plan] Failed to create table: plan_version
> **[16:43:13 ERROR]: [Plan] Database initialization has failed, disabling Plan.**
> [16:43:13 ERROR]: [Plan] Database initialization has failed, disabling Plan.
> [16:43:13 INFO]: [Plan] Disabling Plan v3.6.3
> [16:43:13 INFO]: [Plan] Shutting down Webserver..
> [16:43:13 INFO]: [Plan] Saving cached data..
> [16:43:13 INFO]: [Plan] Player Analytics Disabled.
> [16:43:13 WARN]: Unexpected exception while parsing console command "plan reload"

Disable causes Locale to be unloaded.
Plugin was disabled because database file was locked.
DB file was locked because reload occurred during a database transaction.
Check #238 if the "DB is locked" pops up again on enable.

I recommend restarting instead of reloading until I make something that detects active db transactions before the command reloads the plugin.
