### ISSUE TITLE
Players who change their name are not being updated to their current displayname.

### ISSUE THREAD

**Issue by mibby** [Rsl1122/Plan-PlayerAnalytics#261]
Plan v3.6.4

Players who change their name, their inspect table / playerlist tab ID is still their old name. Would it be possible to update player tables to their latest valid minecraft UUID name when they undergo a name change?

I.e. 
* Player is named BobTest
* Player shows as BobTest in the analysis in both the main playerlist player column and individual inspect.
* Player changes his name to TheMadBobTest through the mojang service to change account name.
* Player is still shown as BobTest in the analysis in both the main playerlist player column and individual inspect. Current name shows up as a nickname.

Not asking for their nickname to update the table for people who use /nick often, but rather just updating to what their actual UUID name matches to on look-up to be relevant and up-to-date with current account name to avoid look-up confusion.

**Comment by Rsl1122** [comment]
Good spot.
This is caused by bukkit data only being put to the database once.
