### ISSUE TITLE
Average CPU: Unavailable

### ISSUE THREAD

**Issue by Fader-GumGum** [Rsl1122/Plan-PlayerAnalytics#263]
Average CPU not showing on Windows system / server.
Using Plan v.3.6.4 with SQLite database and latest Spigot version (also on previous version it was not showing).
No errors in the server log.
Screenshot: https://i.imgur.com/RmDkaHX.png

**Comment by Rsl1122** [comment]
Yes, this is due to Java not being able to check the cpu on some machines. (Java doc for the method said that it is too resource expensive to check the cpu usage on some OS.) 

There is unfortunately nothing I can do about this issue.

**Comment by Fader-GumGum** [comment]
OK, thanks for the info.

**Comment by Fader-GumGum** [comment]
I found this site. Perhaps it can be useful: https://stackoverflow.com/a/27282046

**Comment by Rsl1122** [comment]
It appears that the class in the link provided is provided by the same party as the current one in use.
It returns -1 like the current one in use.
This means that it is not possible to use this class either.

Thanks to @Fuzzlemann for testing this out.
