### ISSUE TITLE
Is it possible to purge world data for worlds no longer existing?

### ISSUE THREAD

**Issue by mibby** [Rsl1122/Plan-PlayerAnalytics#276]
I have analytic data for an old world I had up. Recently I removed this world but the analytical data still persists. Is there any way to purge this data from the analytic tables since the world is no longer in use?

Deleting the world manually in plan_world creates an SQL query exception due to reliance in other tables. 
```
#1451 - Cannot delete or update a parent row: a foreign key constraint fails (`Plan`.`plan_world_times`, CONSTRAINT `plan_world_times_ibfk_2` FOREIGN KEY (`world_id`) REFERENCES `plan_worlds` (`world_id`))```

**Comment by Rsl1122** [comment]
DELETE FROM plan_world_times WHERE world_id=(SELECT plan_worlds.world_id FROM plan_worlds WHERE world_name=NAMEHERE);
DELETE FROM plan_worlds 
* WHERE world_name=NAMEHERE;

That should do it, tell me if there was a syntax error because I wrote this on mobile.

**Comment by mibby** [comment]
The syntax did error on line 1 when trying to select the ID, but I fixed it by manually defining the world_id number and putting the world name in quotes. Thanks! :)
