### ISSUE TITLE
Player playtime is tracking incorrectly.

### ISSUE THREAD

**Issue by mibby** [Rsl1122/Plan-PlayerAnalytics#278]
Plan v3.6.4

Getting reports that the player playtime counter is inaccurate.

> nobody's playtime is right. 
but login times and average session length seems accurate so we can workout total playtime with those
and its not even close
for example. my playtime says 4 days but my logins * average session says I have 9 days

> people I've seen online for hours only have minutes of activity logged.
in fact people's times are going backwards randomly
21 minutes logged for [player] the other day. 
but only 17 minutes logged now. 
he was online for a good 90 minutes yesterday alone. something isn't right

**Comment by Rsl1122** [comment]
The new System has been rewritten to use session length in 4.0.0

**Comment by mibby** [comment]
Great. Looking forward to v4.0's release! Hopefully it isn't too far out.

**Comment by Rsl1122** [comment]
Should come out sometime this month. :)

**Comment by mibby** [comment]
Oh snap, closing issues. Hopefully that means official v4 release is right around the corner!

**Comment by Rsl1122** [comment]
2 things + bug fixes.

**Comment by mibby** [comment]
Can't wait - I'm excited! :)
