### ISSUE TITLE
Data too long for column 'nickname' at row 1

### ISSUE THREAD

**Issue by PsychoLynx** [Rsl1122/Plan-PlayerAnalytics#28]
Hey! On my test server I am using nicknames as players' character names. Currently my character's nickname is "Lord Roland Ironfist the Mighty", which apparently is too long for Plan to handle :P

[Feb 26 13:43:44] main.java.com.djrapitops.plan.database.databases.MySQLDB Caught java.sql.BatchUpdateException: Data truncation: Data too long for column 'nickname' at row 1
[Feb 26 13:43:44]   sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[Feb 26 13:43:44]   sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[Feb 26 13:43:44]   sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[Feb 26 13:43:44]   java.lang.reflect.Constructor.newInstance(Unknown Source)
[Feb 26 13:43:44]   com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[Feb 26 13:43:44]   com.mysql.jdbc.Util.getInstance(Util.java:408)
[Feb 26 13:43:44]   com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1162)
[Feb 26 13:43:44]   com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1773)
[Feb 26 13:43:44]   com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1257)
[Feb 26 13:43:44]   com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:958)
[Feb 26 13:43:44]   main.java.com.djrapitops.plan.database.databases.SQLDB.saveNickList(SQLDB.java:920)
[Feb 26 13:43:44]   main.java.com.djrapitops.plan.database.databases.SQLDB.saveMultipleUserData(SQLDB.java:754)
[Feb 26 13:43:44]   main.java.com.djrapitops.plan.data.cache.DataCacheHandler$3.run(DataCacheHandler.java:168)
[Feb 26 13:43:44]   org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
[Feb 26 13:43:44]   org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[Feb 26 13:43:44]   com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[Feb 26 13:43:44]   java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[Feb 26 13:43:44]   java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[Feb 26 13:43:44]   java.lang.Thread.run(Unknown Source)
[Feb 26 13:43:44]

**Comment by Rsl1122** [comment]
`"CREATE TABLE IF NOT EXISTS " + nicknamesName + " ("
                    + nicknamesColumnUserID + " integer NOT NULL, "
                    + nicknamesColumnNick + " varchar(30) NOT NULL, "
                    + nicknamesColumnCurrent + " boolean NOT NULL DEFAULT 0, "
                    + "FOREIGN KEY(" + nicknamesColumnUserID + ") REFERENCES " + userName + "(" + userColumnID + ")"`
The current length restriction is 30 characters, spaces included.
**If you're using MySQL** you can run following statement in your MySQL to change the length restriction to 75:

> ALTER TABLE plan_nicknames MODIFY nickname VARCHAR(75) NOT NULL;

**If you're using sqlite** the alteration of the table is not possible, and a new table with a new restriction has to be made, I'll bump the length to 75 in the next update, but will not run the alter command (even if using mysql). After the update, run /plan manage backup sqlite, delete old database.db and then run /plan manage restore <dbfile>

**Comment by PsychoLynx** [comment]
Thanks, I am indeed using MySQL as my DB. I will do what you suggested for the time being :)
