### ISSUE TITLE
Session length distribution graph is incomplete

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#284]
Spigot 1.12.1 latest
PLAN 3.4.6

**Description of the issue**
Distribution is truncated at 120 minutes. I am running a test server, almost always logged in. Average session length is (reported as) 3:30:25, but anything longer than 120 minutes (2:00:00) is not displayed in the chart.

**Comment by Fuzzlemann** [comment]
![vqko9sz](https://user-images.githubusercontent.com/16463103/29991169-fbc0f3c2-8f82-11e7-9c3a-79d8bc471089.png)
Can confirm.

**Comment by Rsl1122** [comment]
Vertical scroll option would have been optimal but time was not invested in looking into it. 

This graph has been removed in 4.0.0 because it tends to approach log(x) like distribution.

**Comment by SlimeDog** [comment]
Thanks.
