### ISSUE TITLE
Variables not expanded

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#287]
Spigot 1.12.1 latest
Plan 3.9.9 (aka 4.0.0-DEV-53734b5

Deleted (i.e., backed up) config.yml and custom HTML files.
Loaded 3.9.9 on top of existing 3.6.4 database.
Duplicate entry was created in table plan_user_info. Deleted duplicate.
Created a session.
Refreshed analysis.html.

Observed that variables are not expanded. For example:

![plan](https://user-images.githubusercontent.com/17748923/30251734-b4552f96-961a-11e7-8f32-0f7b527c0d3c.png)

**Comment by Rsl1122** [comment]
This really looks like an exception occurred during analysis, please check errors txt

**Comment by SlimeDog** [comment]
Yes. PLAN had locked the database. Resolved by restarting the server (and therefore PLAN).
