### ISSUE TITLE
Performance chart has only one y-axis scale

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#288]
Spigot 1.12.1 latest
PLAN 3.9.9/4.0.0-DEV

Performance chart has all data on a single Y-axis scale. The various data have vastly different actual scales. Preference: separate chart on the same X-axis, basically stacked charts. If possible.

**Comment by Rsl1122** [comment]
Done on some level. (Range selectors not linked yet - turns out it is more complex than I thought)

![preview](https://i.gyazo.com/eb30485aff905fc758855c535fff7e2e.gif)

**Comment by SlimeDog** [comment]
Good start, but all of the charts need to have Players Online. That data flow is needed to make sense of all the others.

**Comment by Rsl1122** [comment]
Hm, I guess you're right
