### ISSUE TITLE
Single player data not displayed

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#289]
Spigot 1.12.1
PLAN 3.9.9/4.0.0-DEV

I have only one player. Pie charts and map show no data. Similarly, world pie chart shows no data until I visit a second world. With only 1 data point, pie charts should display 100%, and geolocation map should display the single player data.

**Comment by Rsl1122** [comment]
I think this is due to the world pie in the first case using the world time data of the active session, where the time is updated when game mode or world changes.

I don't know about the geolocation map, that part might be broken, could you send the contents of the IP table?

**Comment by SlimeDog** [comment]
plan_ips is empty. That would account for the lack of map data. No idea why it's empty.

**Comment by Rsl1122** [comment]
I probably forgot to add a processor for it :D

**Comment by Rsl1122** [comment]
Found a bug that caused the IPProcessor not to be called. Thanks :)
