### ISSUE TITLE
ASkyBlock island name incorrect

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#291]
Spigot 1.12.x and previous
Plan 3.6.4 and previous
ASkyBlock 3.0.7

PLAN displays
```
Island name: rambeauÂ§r
```
It should be
```
Island name: rambeau
```
of course. I can find no reference to _rambeauÂ§r_ in the ASkyBlock files. The island name is displayed as _rambeau_ in the Top10 GUI.

Help?

**Comment by Rsl1122** [comment]
Something related to character encodings, plan attempts to use UTF-8 while plugins might not be using UTF-8 (And instead use system default encoding)
I'll have to see if this issue can be solved

**Comment by SlimeDog** [comment]
Thanks. I'll ask Tastybento for information.

**Comment by Rsl1122** [comment]
Original issue #168

**Comment by tastybento** [comment]
ASkyBlock in this timings is the ASkyBlock world. 

QuickBoard looks like it's taking quite a few ticks.

Apart form that, I can't see much else.

**Comment by SlimeDog** [comment]
"It's not ASkyBlock" from ASkyBlock dev. :)

**Comment by Rsl1122** [comment]
Very useful xD

**Comment by SlimeDog** [comment]
Where is PLAN retrieving the island name? If the name is stored in Unicode, there might be a Unicode null (001) or some other data before the ASCII null (000). Just a thought.

**Comment by Rsl1122** [comment]
It's probably stored in ISO-8820-1 or similar so fixing #331 might fix this issue

**Comment by SlimeDog** [comment]
Excellent.

**Comment by SlimeDog** [comment]
Spigot 1.12.2 latest
Plan 4.1.4

```
Island Name: rambeau§r
```

Even if I change the island name explicitly with **/is name rambeau** (and confirm that it is displayed correctly in islandnames.yml). Even if I change it to something entirely different (eg, _xyzzy_).
