### ISSUE TITLE
SQL error or missing database

### ISSUE THREAD

**Issue by Alphexon** [Rsl1122/Plan-PlayerAnalytics#3]
My console is getting spammed with this error periodically. Running Spigot 1.11.2 and Plan 2.2.0.

http://pastebin.com/KDSKv9Nt

**Comment by Rsl1122** [comment]
Hello is it just the 
[Server] WARN at com.djrapitops.plan.database.databases.SQLDB.saveLocationList(SQLDB.java:744)
that keeps popping up or are there other save___List as well?

**Comment by Rsl1122** [comment]
Error should have been fixed with the newest version.
https://www.spigotmc.org/resources/plan-player-analytics.32536/update?update=141310
