### ISSUE TITLE
Console Reporting Error

### ISSUE THREAD

**Issue by NyhmsQuest** [Rsl1122/Plan-PlayerAnalytics#32]
Console reported this error here:

[Feb 27 22:14:10] main.java.com.djrapitops.plan.utilities.Analysis$1 Caught java.lang.NullPointerException
[Feb 27 22:14:10]   main.java.com.djrapitops.plan.utilities.Analysis$1.lambda$run$3(Analysis.java:98)
[Feb 27 22:14:10]   java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[Feb 27 22:14:10]   java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
[Feb 27 22:14:10]   java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[Feb 27 22:14:10]   java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
[Feb 27 22:14:10]   java.util.concurrent.CountedCompleter.exec(Unknown Source)
[Feb 27 22:14:10]   java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[Feb 27 22:14:10]   java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
[Feb 27 22:14:10]   java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)

**Comment by Rsl1122** [comment]
Hello.
The NPE was caught and you should have seen this message:
"Some data might be corrupted: <uuid>"
The Gamemode saving seems to fail sometimes, I'm looking into what is causing it. (Cause of data corruption). #33
The error doesn't cause the plugin to fail, but it will ignore the data of that player from the analysis.

What server version are you running? (1.7.X has been causing issues in the past)

**Comment by Rsl1122** [comment]
Okay, I'll try to figure out the reason for corruption. Are there any other exceptions in the logs prior this exception? 
If there are please comment them to #33
