### ISSUE TITLE
Duplicate sessions

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#322]
Spigot 1.12.2
PLAN 4.0.1

Duplicate sessions (and bad analysis):
```
Player  | Started       | Length    | World - Time
rambeau | Oct 02, 14:29 | 1h 39m 6s | world_blackdog (100%)
rambeau | Oct 02, 10:09 | 10s       | world_blackdog (100%)
rambeau | Oct 02, 09:26 | 37m 45s   | - (ï¿½%)
rambeau | Oct 02, 09:26 | 37m 45s   | world_blackdog (100%)
rambeau | Oct 02, 09:26 | 37m 45s   | - (ï¿½%)
rambeau | Oct 02, 09:25 | 28s       | world_blackdog (100%)
```

**Comment by Rsl1122** [comment]
Could you send the contents of sessions table (db)

**Comment by SlimeDog** [comment]
```
sql> select * from plan_sessions ;
id          user_id     server_id   session_start  session_end    mob_kills   deaths    
----------  ----------  ----------  -------------  -------------  ----------  ----------
1           1           1           1506961536588  1506961564602  0           0         
2           1           1           1506961572809  1506963838655  0           0         
3           1           1           1506961572809  1506963838657  0           0         
4           1           1           1506961572809  1506963838657  0           0         
5           1           1           1506964149813  1506964160199  0           0         
6           1           1           1506979767943  1506985714685  39          0         
7           1           1           1507005149705  1507009406719  7           0         
8           1           1           1507009416774  1507009426713  0           0 
```

**Comment by Rsl1122** [comment]
Dangit

**Comment by Rsl1122** [comment]
Any exceptions related to sessions in the Errors.txt?

**Comment by Rsl1122** [comment]
Possibly related bug:
If /reload is used session is not saved until server is shut down. Then it saves all sessions that have been left unsaved with the time of server shut down.

**Comment by SART-Jack** [comment]
I was just about to report the same issue. I did not use "/reload", but I was using "/plan reload" quite frequently while I set up the plugin. I can also provide any additional information you need.

**Comment by Rsl1122** [comment]
Did you shut down the server before you noticed the duplicate sessions?

**Comment by SART-Jack** [comment]
I wasn't paying close enough attention. I tried to recreate the process just now:

1. Reloaded the plugin on the Bukkit server (/plan reload) a few times - No new sessions appeared on the web panel
2. Restarted the Bukkit server - All new sessions appeared once (no duplicates) on the panel
3. Restarted the Bungee server - No duplicates appeared on the panel

I'll keep a better eye on it to see what causes the problem.

**Comment by Rsl1122** [comment]
I've been trying to replicate the problem and I think it is somehow related to the server shutdown hook that saves unsaved sessions.

What I have tried:

- Join, /reload, leave, join, shutdown:
Both sessions have same end date (first session doesn't appear before reboot)
- Join, /reload, leave, shutdown:
Session has end date of shutdown even though it's supposed to be saved on leave (again doesn't appear before reboot)

I'll update when I've tested more.

**Comment by SlimeDog** [comment]
I never use **/reload**. I use (console) **/stop** when testing things. In production I use a home-grown  **/shutdown** Skript that **/kicks** players.

**Comment by Rsl1122** [comment]
Produced a single duplicate when the player left during /plan reload

Following error occurred at the same time:
```
ProcessQueueConsumer:EndSessionProcessor Caught java.lang.IllegalStateException: Session was not Saved!
  main.java.com.djrapitops.plan.database.tables.SessionsTable.saveSession(SessionsTable.java:81)
  main.java.com.djrapitops.plan.systems.cache.SessionCache.endSession(SessionCache.java:45)
  main.java.com.djrapitops.plan.systems.processing.player.EndSessionProcessor.process(EndSessionProcessor.java:28)
  main.java.com.djrapitops.plan.systems.queue.ProcessConsumer.consume(ProcessingQueue.java:55)
  main.java.com.djrapitops.plan.systems.queue.ProcessConsumer.consume(ProcessingQueue.java:40)
  main.java.com.djrapitops.plan.systems.queue.Consumer.run(Consumer.java:35)
  com.djrapitops.plugin.task.RunnableFactory$1.run(RunnableFactory.java:37)
  org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
  org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
  com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
```

**Comment by SART-Jack** [comment]
I'm interested about your comment on high database load, however in my case it may have been high overall MySQL server load, not just of the Plan database.

My duplicate records occurred when my MySQL server had max_connections set to 100. While testing Plan, I encountered the "too many connections" error and raised the max_connections to 200. I have had no duplicate records since, as far as I can see.

**Comment by Rsl1122** [comment]
Attempted to delay processors, did not fix the issue.
Probably related to reload adding more listeners, I'll try some more fixes

**Comment by Rsl1122** [comment]
Fixed by not registering listeners when reloading the plugin.
(My god how dumb mistake)

**Comment by Rsl1122** [comment]
Now that it's fixed I'll make some sort of command to remove faulty sessions
