### ISSUE TITLE
Geolocation unknown

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#323]
Spigot 1.12.2
PLAN 4.0.1

Geolocation map shows no users.

Version 10 database (PLAN 4.0.1):
```
sql> select * from plan_ips ;
user_id     ip                geolocation
----------  ----------------  -----------
1           /108.226.240.191  Not Known 
```
Version 8 database (PLAN 3.6.4):
```
sql> select * from plan_ips ;
user_id     ip           
----------  -------------
1           108.226.240.1

sql> select id,geolocation from plan_users ;
id          geolocation  
----------  -------------
1           United States
```

**Comment by Rsl1122** [comment]
Probably caused by the /

**Comment by SlimeDog** [comment]
Yes, but the slash was introduced by the database conversion. So...bug.

**Comment by SlimeDog** [comment]
I corrected the IP address. Will PLAN correct the geolocation, or should I correct that as well?

**Comment by Rsl1122** [comment]
The database conversion clears the ip table - This is a bug in getting the IP in the new system
Unfortunately it will not correct the geolocation and migth even add the one with the slash back in after you join again.

**Comment by Rsl1122** [comment]
Seems like it was a simple mistake of using toString instead of getHostAddress.

**Comment by SlimeDog** [comment]
Cool.
