### ISSUE TITLE
Alternate names

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#324]
Spigot 1.12.2
PLAN 4.0.2

I am not aware of any use of names with colors, yet:

![untitled](https://user-images.githubusercontent.com/17748923/31111135-bb30cae8-a7c0-11e7-8654-346c55d7ac4f.png)

**Comment by SlimeDog** [comment]
I removed the offending entry from plan_nicknames and the related entries from plan_actions. As expected, the "Changed Name" actions are no longer reported.

**Comment by Rsl1122** [comment]
Going to change the action anyway (new name used for the first time instead of changed name)
