### ISSUE TITLE
Feature request: Change "click to expand" to a navigation icon (down-arrow)

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#325]
Spigot 1.12.2
PLAN 4.0.1

Too much vertical real estate is consumed by "click to expand" -- for example, in the Player Sessions list. Please consider a hover pop-up, so that each session is one line, thereby seeing more on the page before scrolling. Similarly for similar situations.

**Comment by Rsl1122** [comment]
Oo, I could place a downward facing arrow there instead

**Comment by SlimeDog** [comment]
That would be excellent.

**Comment by SlimeDog** [comment]
Down-arrow to expand, up-arrow to dismiss the expansion.

**Comment by SlimeDog** [comment]
Thanks. Looks good.
