### ISSUE TITLE
Russian symbols

### ISSUE THREAD

**Issue by SPYmeYT** [Rsl1122/Plan-PlayerAnalytics#331]
Russian symbols are replacing by bad file encoding. Fix it!)

**Comment by Rsl1122** [comment]
Could you at least give me some context of where the russian symbols are used

**Comment by SPYmeYT** [comment]
Сервер (=Server)
Displaying as Ð¡ÐµÑ€Ð²ÐµÑ€

**Comment by Rsl1122** [comment]
Attempted to set HTTP header.

`content-type: text/html; charset: ISO-8851-1`
or
`content-type: text/html; charset: UTF-8`

Result:
![Result](http://puu.sh/xRtWM/9ef6d15e26.png)

**Comment by SPYmeYT** [comment]
It's a plugin bug, because when i opening file on my computer i see russian letters.

**Comment by Rsl1122** [comment]
In order to work on this issue, solution to #472 needs to be revised.
