### ISSUE TITLE
WorldPlayTime pie colors are inconsistent

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#333]
PLAN 4.0.1

I would like to assign specific colors to specific worlds. It looks like the world order in worldPie is reverse alphabetic. Is that guaranteed?

Could it be changed to straight alphabetic?

**Comment by Rsl1122** [comment]
It would require a really specific script (js) and making a configurable one seems like a nightmare.

**Comment by SlimeDog** [comment]
If sort order cannot be altered easily, please close this issue.

**Comment by Rsl1122** [comment]
It'd require something like this but with placeholders instead of pre made script:
https://stackoverflow.com/questions/13875315/highcharts-dynamically-define-colors-in-pie-chart

If I run out of cool things to do I'll do it :D

**Comment by SlimeDog** [comment]
I can't imagine that you'll ever run out of cool things to do.

**Comment by SlimeDog** [comment]
Now that I've visited more worlds in my test bed, it is clear that world order in the worldPie is completely arbitrary. :(

**Comment by Rsl1122** [comment]
Yeah it's not very readable when the colors aren't the same for each world. One option might be to include all 0 time worlds in the chart as well, making the slice colors constant (This is in use on the game mode drill down)

**Comment by SlimeDog** [comment]
That would work. But you don't have a list of all worlds, currently. Table plan_worlds contains only the worlds visited. Of course, you could add them, or I could.

**Comment by SlimeDog** [comment]
And sort order is still an issue. I 4.0.2 and previous, the sort order algorithm is unclear; to a human it looks arbitrary. It should be either (a) alphabetical or (b) descending percentage.

**Comment by Rsl1122** [comment]
Not sorted in any way, for each on a Map Keyset.
(Set has no order)

**Comment by SlimeDog** [comment]
Yikes!

**Comment by Rsl1122** [comment]
In java Set is just a collection of things like a pile of things.
Lists and arrays are ordered with a box for each thing.

I can easily add alphabetical order into it so I'll probably do that while fixing this.

**Comment by SlimeDog** [comment]
Thanks for the explanation. So you want (well, I want) this to be an array (or list), so it can be ordered. It will need to be, to be presented as an ordered list, in a table, in any event.

**Comment by SlimeDog** [comment]
The _java.util.SortedSet_ interface is a subtype of the _java.util.Set interface_. It behaves like a normal set with the exception that the elements are sorted internally. This means that when you iterate the elements of a SortedSet the elements are returned in the sorted order.

The order of the sorting is either the natural sorting order of the elements (if they implement _java.lang.Comparable_), or the order determined by a _Comparator_ that you can give to the _SortedSet_.

By default the elements are iterated in ascending order, starting with the "smallest" and moving towards the "largest". But it is also possible to iterate the elements in descending order using the method _TreeSet.descendingIterator()_.
