### ISSUE TITLE
Feature request: Configure N most recent sessions

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#338]
PLAN 4.0.1

Please add capability to configure the number of most recent sessions reported. Imposing a reasonable maximum, to avoid web server overload, would be fine. I'm looking for a reduced number, on my very small server.

**Comment by Rsl1122** [comment]
Inspect or Analysis page or both?

**Comment by SlimeDog** [comment]
Both please. The lists should be identical. :)
