### ISSUE TITLE
Mob kills

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#339]
PLAN 4.0.1 sqlite

How are mob kills calculated? Many of my sessions have 0 reported, and then one will have 50+. I kill mobs in almost every session -- it's part of my testing for some other plugins -- so these numbers don't seem right. I have not counted religiously. I will do.

**Comment by SlimeDog** [comment]
It looks like the mob counts are alright, at least in non-duplicated sessions. So resolution of that issue should cover this one.

**Comment by Rsl1122** [comment]
Yeah they're stored with sessions and a SUM statement is used for total
