### ISSUE TITLE
Data too long for column 'command'

### ISSUE THREAD

**Issue by BlackBeltPanda** [Rsl1122/Plan-PlayerAnalytics#34]
Been setting this error in "Errors.txt" pretty frequently:
`main.java.com.djrapitops.plan.data.cache.DataCacheHandler Caught java.sql.BatchUpdateException: Data truncation: Data too long for column 'command' at row 1
  sun.reflect.GeneratedConstructorAccessor396.newInstance(Unknown Source)
  sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
  com.mysql.jdbc.Util.getInstance(Util.java:408)
  com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1162)
  com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1773)
  com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1257)
  com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:958)
  main.java.com.djrapitops.plan.database.databases.SQLDB.saveCommandUse(SQLDB.java:431)
  main.java.com.djrapitops.plan.data.cache.DataCacheHandler.saveCacheOnDisable(DataCacheHandler.java:190)
  main.java.com.djrapitops.plan.Plan.lambda$onDisable$6(Plan.java:165)
  java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
  java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)
`

**Comment by Rsl1122** [comment]
It means that someone used a command over 20 characters long. (or 19 + slash)
With command here I mean the first word after the slash, without any arguments. eg _/plan_ refonregibng

Similar to #28 

**If you're using MySQL** you can run following statement in your MySQL to change the length restriction to 75:

> ALTER TABLE plan_commandusages MODIFY command VARCHAR(75) NOT NULL;

**If you're using sqlite** the alteration of the table is not possible, and a new table with a new restriction has to be made. 
In the next update I'll block saving of any command over 19 characters, because it most likely isn't a real command

**Comment by BlackBeltPanda** [comment]
Ah, a lot of them were probably from me making changes to my permission groups. The commands could typically look like:

"/pex group Group1 add plugin.permission.(first|second|third|someother|permission)"

**Comment by Rsl1122** [comment]
That's what I was trying to say, it only saves the first part eg. /pex

**Comment by Rsl1122** [comment]
Fixed in 549cefd098d25522d4a91ded02d6d9577ef722e7
