### ISSUE TITLE
World groups

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#340]
I wonder if it is possible to group some worlds together. As an example: I have eleven main worlds, six of which have nether and the_end components. So I have a total of 23 worlds. That makes the worldPie very noisy. I'm thinking that having the option to group -- for example -- world, world_nether, and world_the_end together as world would make the visualization a lot more manageable.

Just a thought...

**Comment by SlimeDog** [comment]
Of course, this becomes moot with [#248](https://github.com/Rsl1122/Plan-PlayerAnalytics/issues/248).

**Comment by Rsl1122** [comment]
It's either the pie that is noisy or the code that renders the pie :D (Not sure if 2 drill downs are possible)

**Comment by SlimeDog** [comment]
I don't think two drill-downs are necessary. If I choose to group worlds, then I should expect them to be grouped. If "world" contains three worlds (including nether and the_end), that's my choice, and I have to live with it. :)

I suppose the hover lore could list all of the grouped worlds, but even that isn't necessary.

**Comment by Rsl1122** [comment]
Oh you meant that way - that would be a lot simpler to implement
