### ISSUE TITLE
LogProgressOnConsole not working in 4.0.1

### ISSUE THREAD

**Issue by g4me-time** [Rsl1122/Plan-PlayerAnalytics#341]
Since I updated to 4.0.1 the _LogProgressOnConsole_ in the _config.yml_ seems to have no effect. Every time the _/plan analysis_ command is executed, the progress is shown on the console even if the _LogProgressOnConsole_ is set to _false_. I'm not shure whether this is intentional or not, because the the option is no longer listet on [Bukkit-Configuration](https://github.com/Rsl1122/Plan-PlayerAnalytics/wiki/Bukkit-Configuration) . 

So if it was removed intentionally, please add this functionality again & is it is a bug, please fix ;)

Link: https://hastebin.com/fefolidodu

**Comment by Rsl1122** [comment]
Whoops
