### ISSUE TITLE
Link server session to player sessions?

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#342]
PLAN 4.0.1

Would it be possible to link the sessions in the server listing to player sessions? At present they link to the player (when you click on the player name), but not to the specific session.

**Comment by Rsl1122** [comment]
Maybe.
It requires linking to /player/PlayerName#idOfSessionElement

**Comment by SlimeDog** [comment]
Yep. Please.

**Comment by Rsl1122** [comment]
Seems like it is not possible.
It completely breaks the Tab script (Moves Sessions tab position to the place of Information, and rest to the left similarly)

**Comment by SlimeDog** [comment]
Thanks for trying.
