### ISSUE TITLE
PluginData: MinigamesLib

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#343]
PLAN 4.0.1

```
That's all..
Do you have more plugins? ._.
```

MinigamesLib games. Tracking wins and losses.

**Comment by Rsl1122** [comment]
Closing the issue as the suggestion has been added to a multi-issue

**Comment by Rsl1122** [comment]
Unfortunately there wasn't an API call for the losses, only wins.

Support for the plugins listed on [MinigameAPI github page](https://github.com/MysticCity/MinigamesAPI) will be available in 4.8.0

**Comment by SlimeDog** [comment]
This request was made when it seemed that MinigamesLib was an active plugin. Unfortunately, it seems to be abandoned. :(

**Comment by Rsl1122** [comment]
Yes it seems that way unfortunately.
I decided to implement it anyway in case some servers are still using it.

**Comment by SlimeDog** [comment]
Thanks. I gave up on it.
