### ISSUE TITLE
Chat Logs

### ISSUE THREAD

**Issue by Handhaving** [Rsl1122/Plan-PlayerAnalytics#344]
Plan | Player Analytics 4.0.1

Global chatlogs, and player chat logging.

**Comment by Rsl1122** [comment]
Chat logs will not be a thing on Player Analytics.

Although useful to server owners, I do not want Plan to feel too intrusive about player data.
Collecting all chat is essentially that, and would cause the plugin to appear to the players as "The Big Brother".

If enough people pester me about it in the long run I might make a standalone tool for reading a lot of chat logs, but even then it will not be related to Plan.

**Comment by SeDark** [comment]
It would be nice if you created a plugin like this for bungeecord

https://github.com/EthanWaite/BungeeWeb

Sorry to respond in this post, is not to create a new one with the same
