### ISSUE TITLE
Feature request: Datetime format

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#345]
PLAN 4.0.1+

If a session is less than a minute, display 00:ss (where "ss" is the seconds), in whatever format is dictated by config.yml.

**Comment by SlimeDog** [comment]
The request was for any value up to 59 seconds, not just 0 seconds. The idea was that it would be rendered as "00:59" instead of "59".

**Comment by Rsl1122** [comment]
Whoops misread, my mistake

**Comment by SlimeDog** [comment]
No worries. It's a conversation. :)

**Comment by SlimeDog** [comment]
You are incredibly responsive, compared with most other devs (there are a few others). I appreciate that people often do this sort of work to gain java experience. But many young people don't seem to realize that a commitment, even implied, is important. When a plugin has a following in the tens of thousands, just dropping it on the floor, without publishing the source, is very bad form. So, your commitment is very much appreciated. Thus the donations.

**Comment by Rsl1122** [comment]
Added a %hours% placeholder to Minutes and %minutes% placeholder to seconds.
So that %hours% is replaced with the format of Hours setting if the hours is.

Example:
Hours: %zero%%hours%:
Minutes: %hours%%zero%%minutes%:
Seconds: %minutes%zero%seconds%

Result: 00:00:59

**Comment by SlimeDog** [comment]
I cannot get this to work. Can you check the example, please?

Note that I would have expected
```
Seconds: %minutes%%zero%%seconds%
```
but neither worked.

**Comment by Rsl1122** [comment]
Coding mistakes.

**Comment by SlimeDog** [comment]
Confirmed fixed in Plan 4.0.4. Thank you.
