### ISSUE TITLE
Improve Bungee Standalone usability

### ISSUE THREAD

**Issue by Rsl1122** [Rsl1122/Plan-PlayerAnalytics#349]
Following things need to be implemented for Bungee in order to use the plugin standalone:

- Command to view network link
- Command to register WebUser (HTTPS)
- Refresh Network page periodically if no bukkit servers are connected.

**Comment by mibby** [comment]
> Refresh Network page periodically if no bukkit servers are connected

I'm assuming this is for the player count? As the current /network page player count does not seem to move from the initial start-up analysis while individual server analysis do refresh every 60 seconds.
