### ISSUE TITLE
Data too long for column 'additional_info' at row 1

### ISSUE THREAD

**Issue by mibby** [Rsl1122/Plan-PlayerAnalytics#353]
Plan v4.0.2

Created new sql database due to existing migration issues.
```
main.java.com.djrapitops.plan.systems.processing.NewNickActionProcessor Caught com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'additional_info' at row 1
  com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3971)
  com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
  com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
  com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
  com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
  com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
  com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
  com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
  com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
  com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
  org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:98)
  org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:98)
  main.java.com.djrapitops.plan.database.processing.ExecStatement.execute(ExecStatement.java:27)
  main.java.com.djrapitops.plan.database.tables.Table.execute(Table.java:191)
  main.java.com.djrapitops.plan.database.tables.ActionsTable.insertAction(ActionsTable.java:78)
  main.java.com.djrapitops.plan.systems.processing.NewNickActionProcessor.process(NewNickActionProcessor.java:44)
  main.java.com.djrapitops.plan.systems.queue.ProcessConsumer.consume(ProcessingQueue.java:55)
  main.java.com.djrapitops.plan.systems.queue.ProcessConsumer.consume(ProcessingQueue.java:40)
  main.java.com.djrapitops.plan.systems.queue.Consumer.run(Consumer.java:35)
  com.djrapitops.plugin.task.RunnableFactory$1.run(RunnableFactory.java:37)
  org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
  org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
  com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  java.lang.Thread.run(Thread.java:748)
----

```

**Comment by Rsl1122** [comment]
Please `describe plan_actions;`

**Comment by mibby** [comment]
It's a new database so it should have everything in the v11 schema. 

* user_id / int(11)
* server_id / int(11)
* date / bigint(20)
* action_id / int(11)
* additional_info / varchar(100)

What occurred;
* Started Plan with the server for the first time with a new database.
* Created sql tables.
* Staff logged in.
* Staff tried to get their activity after a couple of minutes with ```/plan qinspect <player>```.
* It was unable to find them and output their data.
* Staff forced an analyze in case it wasn't reanalyzing / updating after 60 seconds (default config) with ```/plan analyze```
* Staff tried to get their info again with same command - was unable to as it still said this player doesn't exist.

He does have a custom nickname that is also colored and sometimes formatted with bolding. Perhaps lookup requires the exact name specification and formatting now of their current nickname instead of being able to lookup their default account name?

**Comment by mibby** [comment]
Correction, it seems ```/plan qinspect``` just doesn't work whatsoever anymore.

**Comment by Rsl1122** [comment]
Qinspect and qanalyze commands were disabled due to the implementation being very complex on Bungee systems.

**Comment by mibby** [comment]
Oh, that's a bit unfortunate. They were quite useful features and good to have to give players access to outputting their own data in chat without giving access to the external web panel. Nice for quick info output too.

**Comment by Rsl1122** [comment]
If you have https set up they only have access to pages that match their permissions

**Comment by mibby** [comment]
Interesting. I assume it is done by matching the connecting IP to a player? As I don't suppose a simple web request would know who specifically is trying to reach the address and what they would have access to.

I still find qinspect to be quite useful however for quick in-game output and not requiring redirecting to a site link. So hopefully that is something that will stay around and eventually be fixed.

**Comment by Rsl1122** [comment]
Nah there is a login :D

**Comment by Rsl1122** [comment]
Yeah I can add it back once I figure out how, it'll require sending quite many variables over WebAPI after all
