### ISSUE TITLE
Feature request: Player Session page reflect Server Session page

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#354]
Please make Player Session content a table, like Server Session page.

Consistency is the hobgoblin of small minds. :)

**Comment by Rsl1122** [comment]
I'd rather make it the other way around.

Okay, so I'll add a config setting that affects both and makes both the same. - Either table or the accordion.
Possibly improve presentation of both as well.

**Comment by SlimeDog** [comment]
Either way is fine. Table seems easier to customize, but that may just reflect my experience. The accordion consumes a lot of vertical space per line, but I supposed that can be managed. I haven't found the settings yet. Mea culpa.

**Comment by Rsl1122** [comment]
Yeah I'll add them in the future :D
