### ISSUE TITLE
Server list command has wrong help text

### ISSUE THREAD

**Issue by takerukoushirou** [Rsl1122/Plan-PlayerAnalytics#358]
The help text for the `servers` command is the same as for the `reload` command:
<img width="1142" alt="screen shot 2017-10-10 at 21 58 51" src="https://user-images.githubusercontent.com/371735/31408086-9ba59e68-ae07-11e7-8897-70c45cc5a7a2.png">

**Comment by Rsl1122** [comment]
Whoops, forgot it after copying :)
