### ISSUE TITLE
Re-implement qinspect output.

### ISSUE THREAD

**Issue by mibby** [Rsl1122/Plan-PlayerAnalytics#365]
Plan v4.0.2

RE: https://github.com/Rsl1122/Plan-PlayerAnalytics/issues/353#issuecomment-336030340

Splitting ticket since above is a separate issue.

**Comment by Rsl1122** [comment]
Complexity reduced by addition of PlayerProfile, which allows for any server to calculate qinspect output.

**Comment by mibby** [comment]
@Rsl1122 Is this re-implemented fully? When typing ```/plan qinspect <name>``` on Plan 4.1.2, it only outputs ```[Plan] This Player doesn't exist.```. Even with doing my name while online.

**Comment by Rsl1122** [comment]
Oh wow I forgot to register the subcommand.
One line fix for the next version (out sometime this week)
