### ISSUE TITLE
LiteBans detection is broken

### ISSUE THREAD

**Issue by mibby** [Rsl1122/Plan-PlayerAnalytics#367]
Is there a command to add a plugin hook to Plan to refresh the config? I recently swapped over to LiteBans but the Plan config didn't add any new settings.

**Comment by Rsl1122** [comment]
It should add the config settings when the plugin is hooked automatically on enable

**Comment by mibby** [comment]
It didn't. I assume it isn't hooking the plugin because the config setting doesn't exist. Only creating plugin hook settings for new Plan configs.
