### ISSUE TITLE
Feature request: Date formatting

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#369]
Spigot 1.12.2 latest
Plan 4.0.2

Please consider a configuration option to format dates. I would be used by (among others) Session list. An example:
```
Customization:
  Formatting:
    Date: 'yyyy-mm-dd'
```
where format codes are from the following set (or something similar):
```
-     hyphen
/     slash/stroke
.     dot
yy    two-digit Julian year (currently 17)
yyyy  four-digit Julian year (currently 2017)
m     numeric month (1-12)
mm    two-digit numeric month (01-12)
mmm   three-character month name (Jan-Dec), possibly localized
mmmm  full month name (January-December), possibly localized
d     numeric day (1-31)
dd    two-digit numeric day (01-31)
```

**Comment by SlimeDog** [comment]
Alternatively, you could offer only a few common options:

> mmm dd (current format in Sessions lists, for example)
> yyyy-mm-dd
> dd/mm/yyyy
> dd-mm-yyyy
> dd.mm.yyy

**Comment by Rsl1122** [comment]
Implemented settings for [SimpleDateFormat](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html) patterns. as well as "Today" "Yesterday" "Wednesday" (For last few days).

**Comment by SlimeDog** [comment]
Works great! Thanks.
