### ISSUE TITLE
Feature request: Numeric formatting

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#370]
Plan 4.0.2

In many (perhaps most) cases, numeric data should be right-justified. This could be a configurable option, if others disagree. Examples include:

- Server:Sessions:Length
- Server:Players:Sessions
- Server:Commands:Times Used
- Server:Plugins:{many numeric fields}

Perhaps the columns for Server:Commands should be reversed, given the table width for only two columns.

Related issue: Tabular columns should have a few pixels of left- and right-padding.

**Comment by Rsl1122** [comment]
I think this can be accomplished by editing the style in the css, not sure.

**Comment by SlimeDog** [comment]
You mean for the padding; probably. The right-justification?

**Comment by Rsl1122** [comment]
I'll try to find if there is a table rule like for the alternating line colors on tables that could do this

**Comment by SlimeDog** [comment]
Confirmed that table.td padding can be adjusted in main.css.

**Comment by Rsl1122** [comment]
Possibly improved by #431 (New html)

**Comment by Rsl1122** [comment]
I'll close this for now.
