### ISSUE TITLE
Feature request: Performance charts on reload

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#372]
Spigot 1.12.2 latest
Plan 4.0.2

If possible, I would like the performance chart to retain the current selection (for example, CPU&RAM) when the page is refreshed.

**Comment by Rsl1122** [comment]
Probably

**Comment by Rsl1122** [comment]
I was about to say that it was not possible but then I found some neat API doc that had good stuff on it.

**Comment by SlimeDog** [comment]
Thank you.
