### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by wupasscat** [Rsl1122/Plan-PlayerAnalytics#384]
Instructions for issue reporting:
- Write description of the issue
- Use `/plan m dump` & Copy the hastebin address here

For suggestions use any format you want. :)

----

**Description of the issue**
Displays an internal error when I type /plan

**Hastebin link**
Link: 
https://hastebin.com/iheqinuheq.vbs

**Comment by Rsl1122** [comment]
Seems like the Exception was an Uncaught exception and thus was not logged to internal Error log, please post the stacktrace from Server log

Additional helpful info: 
- Server Version

**Comment by Rsl1122** [comment]
Could not reproduce on Spigot 1.12, Attempted:
- /plan on console
- /plan as a player with OP
- /plan as a player with 0 permissions

**Comment by wupasscat** [comment]
Server Type: Spigot 1.12
I tried it on the console and this is what I got: `[Server] WARN Unexpected exception while parsing console command "plan"` I also tried it in-game

**Comment by wupasscat** [comment]
this is the console output for running as player: [hastebin](https://hastebin.com/fizirirexe.vbs)

**Comment by Rsl1122** [comment]
Are you running Genie (Another plugin of mine) as well?
Linkage error suggests some sort of class version incompatibility. 
If you aren't running Genie try redownloading Plan

**Comment by wupasscat** [comment]
No, I don't have Genie installed do I need that? But i'll try redownloading

**Comment by wupasscat** [comment]
YAY! thanks it works
