### ISSUE TITLE
Sessions list is padded excessively

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#385]
Spigot 1.12.2 latest
Plan 4.0.3

**Description of the issue**
Rows are padded more than necessary. I would like to compress it vertically. I tried changing .session-col.padding, but no joy.

![untitled](https://user-images.githubusercontent.com/17748923/32146677-32a11704-bc98-11e7-9360-3b59938c2135.png)

**Comment by Rsl1122** [comment]
Possibly related to #380

**Comment by SlimeDog** [comment]
Possibly. :)

**Comment by Rsl1122** [comment]
I can't get that scrollbar to appear, do you have over 50 sessions?

**Comment by Rsl1122** [comment]
Also for the text padding the padding stuff should be placed to
```
.session-header h3 {
    margin: 0;
}
.session-header p {
    margin: 0;
}
```

**Comment by SlimeDog** [comment]
```
sql> select count(*) from plan_sessions
98
```

As released, main.css
```
.session-header h3 {
    margin: 0;
}
.session-header p {
    margin: 0;
}
.session {

}
```
Note that .session is empty, btw.

**Comment by Rsl1122** [comment]
Okay so I went on my Html editor and fiddled around a bit with the padding, Following stuff can reduce the vertical padding:

.session-header h3 {
    margin: 0;
    **font-size: 17px;**
    **font-weight: 500;**
}

.session-col {
    width: 100%;
    background: #fff;
    color: #000;
    margin: 0px 2px;
    display: flex;
    flex-direction: column;
    **padding: 5px 10px;**
}

If you tried one of these before and it had no effect, main.css might have been in the PageCache and thus was not updated on page reload.

**Comment by SlimeDog** [comment]
Thanks. I think main.css was cached last time; I should have thought of that. With patience, I was able to massage Sessions to my liking.
