### ISSUE TITLE
SessionsAsTable is broken

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#387]
Spigot 1.12.2 latest
Play 4.0.3
Default pages (ie., deleted my custom pages)

**Description of the issue**
Set
```
  Display:
    SessionsAsTable: true
```

Output on the page is
![untitled](https://user-images.githubusercontent.com/17748923/32148645-6776a556-bcb7-11e7-999d-7b51e55131ab.png)

**Comment by Rsl1122** [comment]
I guess I shouldn't give deadline dates anymore.
