### ISSUE TITLE
Feature request: Count only player-specific kicks

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#389]
Our shutdown SOP is **/kickall** followed by orderly shutdown. It appears that **/kickall** invocations are counted as player-specific kicks. If possible, please provide option to not include **/kickall** invocations as player-specific kicks; in other words, not recorded in _plan_users.times_kicked_.

**Comment by Rsl1122** [comment]
KickEvent doesn't have a specific way of getting what invoked the event.
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/player/PlayerKickEvent.html

Does /kickall have some sort of specific kick message?

**Comment by SlimeDog** [comment]
```
>kickall
[09:35:17 INFO]: CONSOLE issued server command: /kickall 
[09:35:17 INFO]: Kicked all players from server.
```
or
```
>essentials:kickall
[09:35:17 INFO]: CONSOLE issued server command: /essentials:kickall 
[09:35:17 INFO]: Kicked all players from server.
```

**Comment by Rsl1122** [comment]
I mean the message that the player sees, as that is accessible from the event

**Comment by SlimeDog** [comment]
Nothing in-game, insofar as I can tell. After disconnect, screen displays
```
Connection Lost
Kicked from server.
[button: Back to title screen]
```
but the second line is customizable by the invoker.

![untitled](https://user-images.githubusercontent.com/17748923/32184714-576955d4-bd5a-11e7-9284-102490b1839f.png)

**Comment by Rsl1122** [comment]
Ah so that can't be used, cheers

**Comment by SlimeDog** [comment]
If there is nothing that can be caught, so be it. I'll live. :)

**Comment by SlimeDog** [comment]
How about an admin command to stop recording kicks for the duration? I could add that to our shutdown protocol.

onEnable should enable the counter, of course (ie., on server start-up or **/plan reload**).

**Comment by Rsl1122** [comment]
Would do the trick

**Comment by SlimeDog** [comment]
You are *)(&@$ fast!

**Comment by Rsl1122** [comment]
Woke up, read an easy to implement solution on your comment, ate breakfast, implemented the solution (Single subcommand and a single true/false variable)  :)

This subcommand can also be expanded in the future to disable other features temporarily :D
