### ISSUE TITLE
Feature request: World aliases

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#390]
```
ALTER TABLE plan_worlds ADD world_alias VARCHAR(100);
```
Populate it with Multiverse-Core.alias, if it exists and is NULL. It could also be populated via SQL inserts.
```
SELECT IFNULL(world_alias,world_name)
FROM   plan_worlds
...
```
for worldPie and elsewhere. With appropriate sorting, of course.

**Comment by SlimeDog** [comment]
Here is an example where (shorter) aliases would be useful to save screen real estate. My aliases are simply removal of _world__ in all cases except _world_nether_ and _world_the_end_. It would also slightly reorder the alphabetic list, since the three _world*_ would sort together.

![untitled](https://user-images.githubusercontent.com/17748923/32232697-dc58f31a-be15-11e7-8593-17fa4df94518.png)

**Comment by Rsl1122** [comment]
Woah :O

**Comment by Rsl1122** [comment]
Ah I can solve both this and world grouping by making a config setting per world aliases

**Comment by SlimeDog** [comment]
Excellent! World grouping would be very useful, I expect. I look forward to it.
