### ISSUE TITLE
pom contains 0 maven repos

### ISSUE THREAD

**Issue by RoboMWM** [Rsl1122/Plan-PlayerAnalytics#40]
So... how are we supposed to build this if you don't have any of the required maven repos included in the pom...

**Comment by Rsl1122** [comment]
https://www.spigotmc.org/resources/advanced-achievements.6239/
https://www.spigotmc.org/resources/essentialsx.9089/
https://www.spigotmc.org/resources/factions.1900/
https://dev.bukkit.org/projects/ontime
https://www.spigotmc.org/resources/superbvote.11626/
http://towny.palmergames.com/

Added craftbukkit repo in commit ef57c59d43bce8fe343aadb80cfcb41956052a30
