### ISSUE TITLE
Feature request: Restrict worldPie legends

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#402]
Spigot 1.12.2 latest
Plan 4.0.4
WorldAliases enabled

Each session worldPie legend displays all world aliases (assuming that there has been at least one session in each world). It would be nice if the legend for any session worldPie displayed only the worlds that were included in that particular session. In other worlds, that the legend matched the contents of the pie.

**Comment by Rsl1122** [comment]
The Legend displays all slices which have data, even ones with 0
Removing ones with 0 would cause inconsistencies in colors.

Needs a custom js script for legend on highcharts

**Comment by SlimeDog** [comment]
OK. I've regroup the worlds, so only 11 aliases now. Not so bad. I'll probably settle on 10 aliases.

**Comment by Rsl1122** [comment]
May work once #377 has been implemented
