### ISSUE TITLE
Plugins.Factions.leader links fail

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#406]
Plan 4.0.5 and previous

Leader value is _**rambeau_. It is an active link, but _**rambeau_ is not a valid player name, so the link http://blackdog.straight8.com:8804/player/**rambeau fails.

**Comment by Rsl1122** [comment]
Removed leader links with the Faction table.
I'll add a new Player Table with plugin data (Extremely flexible) that will include the proper link.
