### ISSUE TITLE
Customization support: External navigation link

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#407]
Plan 4.0.4 + sidebar nav

All works great with the standard navigation targets. But if I add an external URL, for example
```
            <a class="nav-button" href="https://${serverName}.straight8.com/"><div title="Public" class="sidenav-button">
                <div><i style="padding:0 5px 0 5px;" class="fa fa-cubes"></i><span style="font-size:16px;"> Public</span></div>
            </div></a>
```
the link works, but the page content is not displayed. Ideas?

**Comment by Rsl1122** [comment]
Remove the nav-button class, it is used to count the tabs. (If it looks bad add a separate class with same contents to css)

**Comment by Rsl1122** [comment]
Oh I think it's empty no need to copy contents

**Comment by SlimeDog** [comment]
Like a charm. Thanks.
