### ISSUE TITLE
Litebans html was removed because it contained too many characters to be responsive.

### ISSUE THREAD

**Issue by mibby** [Rsl1122/Plan-PlayerAnalytics#410]
Plan v4.0.5
Bungee + 2 Bukkit Servers

Checking the plugins tab on one of the Bukkit servers, noticed the LiteBans integration could not be displayed.

![link](https://i.imgur.com/Y5sotBC.png)

**Comment by Rsl1122** [comment]
Related to issue #399

**Comment by mibby** [comment]
@Rsl1122 Doesn't seem to have gotten much better with 4.0.7.

![link2](https://i.imgur.com/KKD3FFZ.png)

**Comment by Rsl1122** [comment]
Nothing was changed related to this.

**Comment by Rsl1122** [comment]
Issue closed because it is no longer relevant (PluginData parsing has changed drasticly)
