### ISSUE TITLE
WebServer runs into NullPointerException (Resource not found) after improper server restart after plugin update

### ISSUE THREAD

**Issue by wupasscat** [Rsl1122/Plan-PlayerAnalytics#415]
Instructions for issue reporting:
- Write description of the issue
- Use `/plan m dump` & Copy the hastebin address here

For suggestions use any format you want. :)

----

**Description of the issue**
I just installed Plan 4.0.5 and tried to go on the Plan web panel. All it does is say "ERR_EMPTY_RESPONSE". 

**Hastebin link**
Link: 
https://hastebin.com/uhepoziril.pl

**Comment by wupasscat** [comment]
oh and I couldn't do `/plan m dump`, so I copied the errors.txt file

**Comment by Rsl1122** [comment]
This error suggests that reload was used instead of a full server restart.
Try restarting the server completely.

**Comment by wupasscat** [comment]
Ok, I used a plugin loader to update i'll restart the server though
