### ISSUE TITLE
Customization request: SessionsAsTable

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#418]
Plan 4.0.5 with 4.1.0 sidebar addition

With config _SessionsAsTable:false_ (the default), display is as expected.
![untitled](https://user-images.githubusercontent.com/17748923/32473848-7477c7f4-c31e-11e7-86fd-1ecc6405a9ec.png)

With config _SessionsAsTable:true_ (and the containing scrollbar removed), the table does not consume the entire column.
![untitled](https://user-images.githubusercontent.com/17748923/32473904-ab41488c-c31e-11e7-8253-2c8b016f4a54.png)

Unlike other server.html tables -- _${tableBodyRecentLogins}_, _${tableBodyPlayerList}_, and _${tableBodyCommands}_ -- _SessionsAsTable:true_ presents an overlay on the nontabular display _${contentSessions}_.

There are two ways to address this issue. (1) Fix whatever is causing the current issue. (2) Create a parallel _${tableBodySessions}_ similar to the other tableBody calls, which can be utilized by customizers.

**Comment by Rsl1122** [comment]
I think it's missing the "table-sortable" class

**Comment by SlimeDog** [comment]
Confirmed that, when properly configured, ${tableBodySessions} works for the Server sessions list. It it unrecognized for the Player sessions list.
