### ISSUE TITLE
IP Timestamp table

### ISSUE THREAD

**Issue by Rsl1122** [Rsl1122/Plan-PlayerAnalytics#422]
A table where IP and the last time it was seen used to the Player inspect page.

So:

IP | Geolocation | Last seen in use
-- | -- | --
1.2.3.4 | United States | 12 May 2017 20:44
3.4.5.6 | United States | 5 May 2017 20:12

**Comment by spannerman79** [comment]
So that those that are in the EU can comply with EU laws have an option to be able to anonymize the IP collected to *at least* one byte.

Example: `192.168.0.10 -> 192.168.0.xx`

**Comment by Rsl1122** [comment]
Great shout
