### ISSUE TITLE
Improvement for age and gender detection

### ISSUE THREAD

**Issue by Eyremba** [Rsl1122/Plan-PlayerAnalytics#43]
I think you didn't see this issue here: https://github.com/Rsl1122/Plan-Player-Demographics/issues/1

So because it was moved from Player Demographics to this one here, I linked it above.

**Comment by Rsl1122** [comment]
`// Create lists String[] triggersA = {"i\\'m", "am", "im"}; String[] femaleA = {"female", "girl", "gurl", "woman", "gal", "mrs", "she", "miss"}; String[] maleA = {"male", "boy", "man", "boe", "sir", "mr", "guy", "he"}; String[] ageA = {"years", "year-old", "old"}; String[] ignoreA = {"sure", "think", "with", "are"};`

I could help you to add also support for the german language.

For triggersA add "bin"
For femaleA add "weiblich", "feminin", "mädchen", "frau"
For maleA add "männlich", "maskulin", "junge", "mann"
For ageA add "jahr", "jahre"

Also, someone could write something like "I'm 17".
Maybe you could catch such things to, just listen if the chat message starts with a trigger and ends directly with a number.

**Comment by Rsl1122** [comment]
Hey could you also translate https://github.com/Rsl1122/Plan-PlayerAnalytics/tree/master/Plan/localization
That'd really help me out since I don't know any german :)

I think it should catch "I'm 17", because it ignores the CaSiNg of the words & age triggers are not in use with Plan, and all texts with trigger and a number are considered age.

**Comment by Eyremba** [comment]
> Hey could you also translate https://github.com/Rsl1122/Plan-PlayerAnalytics/tree/master/Plan/localization
That'd really help me out since I don't know any german :)

Yes. Unfortunately, I have no time today, but I will try to translate it tomorrow. :)

**Comment by Rsl1122** [comment]
Alright Cheers :)
