### ISSUE TITLE
${tableBodySessions} unrecognized in player.html

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#435]
Plan 4.0.7
Spigot 1.12.2 latest

${tableBodySessions} is unrecognized for the Player sessions list. It works for the Server sessions list.

**Comment by Rsl1122** [comment]
Extra table is not parsed for inspect page, needs SessionsAsTable: true for tables.

"Won't be fixed" because new version has SessionsAsTable: true properly working for inspect page on the new Html.

**Comment by SlimeDog** [comment]
Thanks, that works with 4.0.7, although the "extra table" allowed me to specify the headers.

**Comment by Rsl1122** [comment]
Ah, yep.
It's quite difficult to make the custom parsed components customizable without making the code doing the job completely unreadable. (not that they would be very readable atm anyway)
