### ISSUE TITLE
NoClassDefFoundError: br/net/fabiozumbi12/RedProtect/API/RedProtectAPI

### ISSUE THREAD

**Issue by Rbot48** [Rsl1122/Plan-PlayerAnalytics#447]
```
WARN ProcessQueueConsumer: Caught: java.lang.NoClassDefFoundError: br/net/fabiozumbi12/RedProtect/API/RedProtectAPI
```

RedProtect has recently updated its API and it's now br.net.fabiozumbi12.RedProtect.Bukkit.API.RedProtectAPI.

**Comment by Rsl1122** [comment]
Wow, I made this like 3 days ago :D

**Comment by Rbot48** [comment]
That's odd O.o
I'm using the latest version of RedProtect and Plan

**Comment by Rsl1122** [comment]
My bad it was 6 days ago (#423), but still. :P

**Comment by Rbot48** [comment]
Redownloading RedProtect seems to have solved the issue, closing it for now. Thanks

**Comment by Rsl1122** [comment]
Very odd, well - great that it works now :)
