### ISSUE TITLE
IllegalArgumentException When Command Stored Ending With Backslash

### ISSUE THREAD

**Issue by MattJF90** [Rsl1122/Plan-PlayerAnalytics#45]
**Plan Version:** 2.82

**Description:**
When executing "/plan analyze" or starting the server, an IllegalArgumentException is thrown with the description "character to be escaped is missing".

Based on the stack trace, this is likely caused by a command being entered with a single backslash at the end. For example "/\\".

As a result, once a command of this type has been executed by any player (even if it's not a valid command), the plugin will store this command and will no longer be able to analyze data.

**Steps to Reproduce:**
1.  [As Any Player] Enter a command which ends in a single backslash. For example, "/\\".
2. [As OP] Execute "/plan analyze" or restart the server.

**Impact:**
Any player on the server is able to cause Plan to crash.

**Proposed Solution:**
Ensure that any strings which are read in are properly escaped, especially with regex.

**Stack Trace (Errors.txt):**
```
[Mar 10 21:33:20] SortableCommandUseTableCreator Caught java.lang.IllegalArgumentException: character to be escaped is missing
[Mar 10 21:33:20]   java.util.regex.Matcher.appendReplacement(Matcher.java:809)
[Mar 10 21:33:20]   java.util.regex.Matcher.replaceAll(Matcher.java:955)
[Mar 10 21:33:20]   java.lang.String.replaceAll(String.java:2223)
[Mar 10 21:33:20]   main.java.com.djrapitops.plan.ui.Html.parse(Html.java:106)
[Mar 10 21:33:20]   main.java.com.djrapitops.plan.ui.tables.SortableCommandUseTableCreator.createSortedCommandUseTable(SortableCommandUseTableCreator.java:32)
[Mar 10 21:33:20]   main.java.com.djrapitops.plan.utilities.AnalysisUtils.createTableOutOfHashMap(AnalysisUtils.java:47)
[Mar 10 21:33:20]   main.java.com.djrapitops.plan.utilities.Analysis$1.createCommandUseTable(Analysis.java:174)
[Mar 10 21:33:20]   main.java.com.djrapitops.plan.utilities.Analysis$1.run(Analysis.java:159)
[Mar 10 21:33:20]   org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
[Mar 10 21:33:20]   org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[Mar 10 21:33:20]   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[Mar 10 21:33:20]   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[Mar 10 21:33:20]   java.lang.Thread.run(Thread.java:745)
```

**Comment by Rsl1122** [comment]
So glad I moved all replace actions to a single method earlier :D
Fixed by stopping using regex for replacing
