### ISSUE TITLE
Some error with GriefPrevention & Factions

### ISSUE THREAD

**Issue by Fader-GumGum** [Rsl1122/Plan-PlayerAnalytics#451]
After starting the server i'm getting the following error:

```
[10:25:13] [Craft Scheduler Thread - 24/INFO]: [Plan] Cleaning the database.
[10:25:13] [Craft Scheduler Thread - 24/INFO]: [Plan] Clean complete.
[10:25:39] [Craft Scheduler Thread - 25/INFO]: [Plan] Analysis | Starting Boot Analysis..
[10:25:39] [Craft Scheduler Thread - 25/INFO]: [Plan] Analysis | Beginning analysis of user data..
[10:25:39] [Craft Scheduler Thread - 25/INFO]: [Plan] Analysis | Fetching Data..
[10:25:39] [Craft Scheduler Thread - 25/INFO]: [Plan] Analysis | Data Fetched (300 users, took 484ms), beginning Analysis of data..
[10:25:40] [Craft Scheduler Thread - 25/INFO]: [Plan] Analysis | Analyzing additional data sources (3rd party)
[10:25:40] [Craft Scheduler Thread - 25/ERROR]: [Plan] A PluginData-source caused an exception: GriefPrevention
[10:25:40] [Craft Scheduler Thread - 25/WARN]: [Plan] main.java.com.djrapitops.plan.utilities.analysis.Analysis Caught: java.lang.IllegalStateException: Duplicate key 300
[10:25:41] [ForkJoinPool.commonPool-worker-1/ERROR]: [Plan] A PluginData-source caused an exception: Factions
[10:25:41] [ForkJoinPool.commonPool-worker-1/WARN]: [Plan] main.java.com.djrapitops.plan.utilities.analysis.Analysis Caught: java.lang.NullPointerException
[10:25:42] [Craft Scheduler Thread - 25/INFO]: [Plan] Analysis | Analysis Complete. (took 3027 ms) 
```

Running Spigot 1.12.2 and Plan 4.1.2

**Comment by Rsl1122** [comment]
Please send the contents of Errors.txt

**Comment by Fader-GumGum** [comment]
Hereby the Errors.txt content:

> main.java.com.djrapitops.plan.systems.webserver.ResponseHandler Caught java.lang.NullPointerException
  main.java.com.djrapitops.plan.systems.info.parsing.AnalysisPageParser.parse(AnalysisPageParser.java:36)
  main.java.com.djrapitops.plan.systems.info.BukkitInformationManager.getAnalysisHtml(BukkitInformationManager.java:194)
  main.java.com.djrapitops.plan.systems.webserver.response.AnalysisPageResponse.<init>(AnalysisPageResponse.java:14)
  main.java.com.djrapitops.plan.systems.webserver.ResponseHandler.lambda$serverResponse$5(ResponseHandler.java:199)
  main.java.com.djrapitops.plan.systems.webserver.PageCache.loadPage(PageCache.java:53)
  main.java.com.djrapitops.plan.systems.webserver.ResponseHandler.serverResponse(ResponseHandler.java:199)
  main.java.com.djrapitops.plan.systems.webserver.ResponseHandler.rootPageResponse(ResponseHandler.java:183)
  main.java.com.djrapitops.plan.systems.webserver.ResponseHandler.getResponse(ResponseHandler.java:75)
  main.java.com.djrapitops.plan.systems.webserver.RequestHandler.handle(RequestHandler.java:36)
  com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
  sun.net.httpserver.AuthFilter.doFilter(Unknown Source)
  com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
  sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(Unknown Source)
  com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
  sun.net.httpserver.ServerImpl$Exchange.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
----
main.java.com.djrapitops.plan.utilities.analysis.Analysis Caught java.lang.NullPointerException
  com.djrapitops.plugin.utilities.Format.capitalize(Format.java:110)
  com.djrapitops.pluginbridge.plan.vault.PermGroupTable.getTableLines(PermGroupTable.java:68)
  com.djrapitops.pluginbridge.plan.vault.PermGroupTable.getHtmlReplaceValue(PermGroupTable.java:44)
  main.java.com.djrapitops.plan.utilities.analysis.Analysis.lambda$analyzeAdditionalPluginData$3(Analysis.java:166)
  java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
  java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
  java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
  java.util.stream.AbstractPipeline.copyInto(Unknown Source)
  java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
  java.util.concurrent.CountedCompleter.exec(Unknown Source)
  java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
  java.util.concurrent.ForkJoinPool.helpComplete(Unknown Source)
  java.util.concurrent.ForkJoinPool.externalHelpComplete(Unknown Source)
  java.util.concurrent.ForkJoinTask.externalAwaitDone(Unknown Source)
  java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
  java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
  java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)
  java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source)
  java.util.stream.AbstractPipeline.evaluate(Unknown Source)
  java.util.stream.ReferencePipeline.forEach(Unknown Source)
  main.java.com.djrapitops.plan.utilities.analysis.Analysis.analyzeAdditionalPluginData(Analysis.java:158)
  main.java.com.djrapitops.plan.utilities.analysis.Analysis.analyzeData(Analysis.java:118)
  main.java.com.djrapitops.plan.utilities.analysis.Analysis.analyze(Analysis.java:89)
  main.java.com.djrapitops.plan.utilities.analysis.Analysis$1.run(Analysis.java:67)
  com.djrapitops.plugin.task.RunnableFactory$1.run(RunnableFactory.java:37)
  org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
  org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
----
main.java.com.djrapitops.plan.utilities.analysis.Analysis Caught java.lang.NullPointerException
  com.djrapitops.plugin.utilities.Format.capitalize(Format.java:110)
  com.djrapitops.pluginbridge.plan.vault.PermGroupTable.getTableLines(PermGroupTable.java:68)
  com.djrapitops.pluginbridge.plan.vault.PermGroupTable.getHtmlReplaceValue(PermGroupTable.java:44)
  main.java.com.djrapitops.plan.utilities.analysis.Analysis.lambda$analyzeAdditionalPluginData$3(Analysis.java:166)
  java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
  java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
  java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
  java.util.stream.AbstractPipeline.copyInto(Unknown Source)
  java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
  java.util.concurrent.CountedCompleter.exec(Unknown Source)
  java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
  java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
  java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
  java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
----
main.java.com.djrapitops.plan.systems.cache.DataCache Caught org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (cannot commit - no transaction is active)
  org.sqlite.core.DB.newSQLException(DB.java:909)
  org.sqlite.core.DB.newSQLException(DB.java:921)
  org.sqlite.core.DB.throwex(DB.java:886)
  org.sqlite.core.DB.exec(DB.java:155)
  org.sqlite.jdbc3.JDBC3Connection.commit(JDBC3Connection.java:174)
  main.java.com.djrapitops.plan.database.databases.SQLDB.commit(SQLDB.java:294)
  main.java.com.djrapitops.plan.database.tables.Table.commit(Table.java:174)
  main.java.com.djrapitops.plan.database.tables.Table.execute(Table.java:192)
  main.java.com.djrapitops.plan.database.tables.SessionsTable.saveSessionInformation(SessionsTable.java:100)
  main.java.com.djrapitops.plan.database.tables.SessionsTable.saveSession(SessionsTable.java:80)
  main.java.com.djrapitops.plan.systems.cache.SessionCache.endSession(SessionCache.java:45)
  main.java.com.djrapitops.plan.systems.processing.player.EndSessionProcessor.process(EndSessionProcessor.java:28)
  main.java.com.djrapitops.plan.systems.queue.ProcessConsumer.consume(ProcessingQueue.java:55)
  main.java.com.djrapitops.plan.systems.queue.ProcessConsumer.consume(ProcessingQueue.java:40)
  main.java.com.djrapitops.plan.systems.queue.Consumer.run(Consumer.java:35)
  com.djrapitops.plugin.task.RunnableFactory$1.run(RunnableFactory.java:37)
  org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
  org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
----
main.java.com.djrapitops.plan.systems.processing.player.FirstLeaveProcessor Caught org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (cannot commit - no transaction is active)
  org.sqlite.core.DB.newSQLException(DB.java:909)
  org.sqlite.core.DB.newSQLException(DB.java:921)
  org.sqlite.core.DB.throwex(DB.java:886)
  org.sqlite.core.DB.exec(DB.java:155)
  org.sqlite.jdbc3.JDBC3Connection.commit(JDBC3Connection.java:174)
  main.java.com.djrapitops.plan.database.databases.SQLDB.commit(SQLDB.java:294)
  main.java.com.djrapitops.plan.database.tables.Table.commit(Table.java:174)
  main.java.com.djrapitops.plan.database.tables.Table.execute(Table.java:192)
  main.java.com.djrapitops.plan.database.tables.ActionsTable.insertAction(ActionsTable.java:78)
  main.java.com.djrapitops.plan.systems.processing.player.FirstLeaveProcessor.process(FirstLeaveProcessor.java:35)
  main.java.com.djrapitops.plan.systems.queue.ProcessConsumer.consume(ProcessingQueue.java:55)
  main.java.com.djrapitops.plan.systems.queue.ProcessConsumer.consume(ProcessingQueue.java:40)
  main.java.com.djrapitops.plan.systems.queue.Consumer.run(Consumer.java:35)
  com.djrapitops.plugin.task.RunnableFactory$1.run(RunnableFactory.java:37)
  org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
  org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
----
main.java.com.djrapitops.plan.systems.processing.NewNickActionProcessor Caught org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (cannot commit - no transaction is active)
  org.sqlite.core.DB.newSQLException(DB.java:909)
  org.sqlite.core.DB.newSQLException(DB.java:921)
  org.sqlite.core.DB.throwex(DB.java:886)
  org.sqlite.core.DB.exec(DB.java:155)
  org.sqlite.jdbc3.JDBC3Connection.commit(JDBC3Connection.java:174)
  main.java.com.djrapitops.plan.database.databases.SQLDB.commit(SQLDB.java:294)
  main.java.com.djrapitops.plan.database.tables.Table.commit(Table.java:174)
  main.java.com.djrapitops.plan.database.tables.Table.execute(Table.java:192)
  main.java.com.djrapitops.plan.database.tables.ActionsTable.insertAction(ActionsTable.java:78)
  main.java.com.djrapitops.plan.systems.processing.NewNickActionProcessor.process(NewNickActionProcessor.java:44)
  main.java.com.djrapitops.plan.systems.queue.ProcessConsumer.consume(ProcessingQueue.java:55)
  main.java.com.djrapitops.plan.systems.queue.ProcessConsumer.consume(ProcessingQueue.java:40)
  main.java.com.djrapitops.plan.systems.queue.Consumer.run(Consumer.java:35)
  com.djrapitops.plugin.task.RunnableFactory$1.run(RunnableFactory.java:37)
  org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
  org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
----
main.java.com.djrapitops.plan.systems.processing.player.NameProcessor Caught org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (cannot commit - no transaction is active)
  org.sqlite.core.DB.newSQLException(DB.java:909)
  org.sqlite.core.DB.newSQLException(DB.java:921)
  org.sqlite.core.DB.throwex(DB.java:886)
  org.sqlite.core.DB.exec(DB.java:155)
  org.sqlite.jdbc3.JDBC3Connection.commit(JDBC3Connection.java:174)
  main.java.com.djrapitops.plan.database.databases.SQLDB.commit(SQLDB.java:294)
  main.java.com.djrapitops.plan.database.tables.Table.commit(Table.java:174)
  main.java.com.djrapitops.plan.database.tables.Table.execute(Table.java:192)
  main.java.com.djrapitops.plan.database.tables.UsersTable.updateName(UsersTable.java:193)
  main.java.com.djrapitops.plan.systems.processing.player.NameProcessor.process(NameProcessor.java:53)
  main.java.com.djrapitops.plan.systems.queue.ProcessConsumer.consume(ProcessingQueue.java:55)
  main.java.com.djrapitops.plan.systems.queue.ProcessConsumer.consume(ProcessingQueue.java:40)
  main.java.com.djrapitops.plan.systems.queue.Consumer.run(Consumer.java:35)
  com.djrapitops.plugin.task.RunnableFactory$1.run(RunnableFactory.java:37)
  org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
  org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
----
main.java.com.djrapitops.plan.systems.processing.player.IPUpdateProcessor Caught org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (cannot commit - no transaction is active)
  org.sqlite.core.DB.newSQLException(DB.java:909)
  org.sqlite.core.DB.newSQLException(DB.java:921)
  org.sqlite.core.DB.throwex(DB.java:886)
  org.sqlite.core.DB.exec(DB.java:155)
  org.sqlite.jdbc3.JDBC3Connection.commit(JDBC3Connection.java:174)
  main.java.com.djrapitops.plan.database.databases.SQLDB.commit(SQLDB.java:294)
  main.java.com.djrapitops.plan.database.tables.Table.commit(Table.java:174)
  main.java.com.djrapitops.plan.database.tables.Table.execute(Table.java:192)
  main.java.com.djrapitops.plan.database.tables.IPsTable.insertIp(IPsTable.java:97)
  main.java.com.djrapitops.plan.database.tables.IPsTable.saveIP(IPsTable.java:93)
  main.java.com.djrapitops.plan.systems.processing.player.IPUpdateProcessor.process(IPUpdateProcessor.java:33)
  main.java.com.djrapitops.plan.systems.queue.ProcessConsumer.consume(ProcessingQueue.java:55)
  main.java.com.djrapitops.plan.systems.queue.ProcessConsumer.consume(ProcessingQueue.java:40)
  main.java.com.djrapitops.plan.systems.queue.Consumer.run(Consumer.java:35)
  com.djrapitops.plugin.task.RunnableFactory$1.run(RunnableFactory.java:37)
  org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
  org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
----
main.java.com.djrapitops.plan.systems.processing.player.NameProcessor Caught org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (cannot commit - no transaction is active)
  org.sqlite.core.DB.newSQLException(DB.java:909)
  org.sqlite.core.DB.newSQLException(DB.java:921)
  org.sqlite.core.DB.throwex(DB.java:886)
  org.sqlite.core.DB.exec(DB.java:155)
  org.sqlite.jdbc3.JDBC3Connection.commit(JDBC3Connection.java:174)
  main.java.com.djrapitops.plan.database.databases.SQLDB.commit(SQLDB.java:294)
  main.java.com.djrapitops.plan.database.tables.Table.commit(Table.java:174)
  main.java.com.djrapitops.plan.database.tables.Table.execute(Table.java:192)
  main.java.com.djrapitops.plan.database.tables.NicknamesTable.saveUserName(NicknamesTable.java:152)
  main.java.com.djrapitops.plan.systems.processing.player.NameProcessor.process(NameProcessor.java:55)
  main.java.com.djrapitops.plan.systems.queue.ProcessConsumer.consume(ProcessingQueue.java:55)
  main.java.com.djrapitops.plan.systems.queue.ProcessConsumer.consume(ProcessingQueue.java:40)
  main.java.com.djrapitops.plan.systems.queue.Consumer.run(Consumer.java:35)
  com.djrapitops.plugin.task.RunnableFactory$1.run(RunnableFactory.java:37)
  org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
  org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
----
main.java.com.djrapitops.plan.systems.processing.player.IPUpdateProcessor Caught org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (cannot commit - no transaction is active)
  org.sqlite.core.DB.newSQLException(DB.java:909)
  org.sqlite.core.DB.newSQLException(DB.java:921)
  org.sqlite.core.DB.throwex(DB.java:886)
  org.sqlite.core.DB.exec(DB.java:155)
  org.sqlite.jdbc3.JDBC3Connection.commit(JDBC3Connection.java:174)
  main.java.com.djrapitops.plan.database.databases.SQLDB.commit(SQLDB.java:299)
  main.java.com.djrapitops.plan.database.tables.Table.commit(Table.java:174)
  main.java.com.djrapitops.plan.database.tables.Table.execute(Table.java:192)
  main.java.com.djrapitops.plan.database.tables.IPsTable.insertIp(IPsTable.java:103)
  main.java.com.djrapitops.plan.database.tables.IPsTable.saveIP(IPsTable.java:99)
  main.java.com.djrapitops.plan.systems.processing.player.IPUpdateProcessor.process(IPUpdateProcessor.java:33)
  main.java.com.djrapitops.plan.systems.queue.ProcessConsumer.consume(ProcessingQueue.java:55)
  main.java.com.djrapitops.plan.systems.queue.ProcessConsumer.consume(ProcessingQueue.java:40)
  main.java.com.djrapitops.plan.systems.queue.Consumer.run(Consumer.java:35)
  com.djrapitops.plugin.task.RunnableFactory$1.run(RunnableFactory.java:37)
  org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
  org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
----
main.java.com.djrapitops.plan.systems.processing.NewNickActionProcessor Caught org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (cannot commit - no transaction is active)
  org.sqlite.core.DB.newSQLException(DB.java:909)
  org.sqlite.core.DB.newSQLException(DB.java:921)
  org.sqlite.core.DB.throwex(DB.java:886)
  org.sqlite.core.DB.exec(DB.java:155)
  org.sqlite.jdbc3.JDBC3Connection.commit(JDBC3Connection.java:174)
  main.java.com.djrapitops.plan.database.databases.SQLDB.commit(SQLDB.java:299)
  main.java.com.djrapitops.plan.database.tables.Table.commit(Table.java:174)
  main.java.com.djrapitops.plan.database.tables.Table.execute(Table.java:192)
  main.java.com.djrapitops.plan.database.tables.ActionsTable.insertAction(ActionsTable.java:84)
  main.java.com.djrapitops.plan.systems.processing.NewNickActionProcessor.process(NewNickActionProcessor.java:42)
  main.java.com.djrapitops.plan.systems.queue.ProcessConsumer.consume(ProcessingQueue.java:55)
  main.java.com.djrapitops.plan.systems.queue.ProcessConsumer.consume(ProcessingQueue.java:40)
  main.java.com.djrapitops.plan.systems.queue.Consumer.run(Consumer.java:35)
  com.djrapitops.plugin.task.RunnableFactory$1.run(RunnableFactory.java:37)
  org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
  org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
----
main.java.com.djrapitops.plan.systems.cache.DataCache Caught org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (cannot commit - no transaction is active)
  org.sqlite.core.DB.newSQLException(DB.java:909)
  org.sqlite.core.DB.newSQLException(DB.java:921)
  org.sqlite.core.DB.throwex(DB.java:886)
  org.sqlite.core.DB.exec(DB.java:155)
  org.sqlite.jdbc3.JDBC3Connection.commit(JDBC3Connection.java:174)
  main.java.com.djrapitops.plan.database.databases.SQLDB.commit(SQLDB.java:299)
  main.java.com.djrapitops.plan.database.tables.Table.commit(Table.java:174)
  main.java.com.djrapitops.plan.database.tables.Table.execute(Table.java:192)
  main.java.com.djrapitops.plan.database.tables.SessionsTable.saveSessionInformation(SessionsTable.java:100)
  main.java.com.djrapitops.plan.database.tables.SessionsTable.saveSession(SessionsTable.java:80)
  main.java.com.djrapitops.plan.systems.cache.SessionCache.endSession(SessionCache.java:45)
  main.java.com.djrapitops.plan.systems.processing.player.EndSessionProcessor.process(EndSessionProcessor.java:28)
  main.java.com.djrapitops.plan.systems.queue.ProcessConsumer.consume(ProcessingQueue.java:55)
  main.java.com.djrapitops.plan.systems.queue.ProcessConsumer.consume(ProcessingQueue.java:40)
  main.java.com.djrapitops.plan.systems.queue.Consumer.run(Consumer.java:35)
  com.djrapitops.plugin.task.RunnableFactory$1.run(RunnableFactory.java:37)
  org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
  org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
----

**Comment by Fader-GumGum** [comment]
Here the errors.txt file.
[errors.txt](https://github.com/Rsl1122/Plan-PlayerAnalytics/files/1524689/errors.txt)

**Comment by Fader-GumGum** [comment]
Here the errors.txt. The latest
[errors.txt](https://github.com/Rsl1122/Plan-PlayerAnalytics/files/1524693/errors.txt)
 errors are at the end of the file.

**Comment by Rsl1122** [comment]
```
java.lang.IllegalStateException: Duplicate key 300
   java.util.stream.Collectors.lambda$throwingMerger$0(Unknown Source)
   java.util.HashMap.merge(Unknown Source)
   java.util.stream.Collectors.lambda$toMap$58(Unknown Source)
   java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source)
   java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
   java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
   java.util.stream.AbstractPipeline.copyInto(Unknown Source)
   java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
   java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
   java.util.stream.AbstractPipeline.evaluate(Unknown Source)
   java.util.stream.ReferencePipeline.collect(Unknown Source)
   com.djrapitops.pluginbridge.plan.griefprevention.GriefPreventionData.getServerData(GriefPreventionData.java:73)
   main.java.com.djrapitops.plan.utilities.analysis.Analysis.lambda$analyzeAdditionalPluginData$4(Analysis.java:188)
   java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
   java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
   java.util.stream.AbstractPipeline.copyInto(Unknown Source)
   java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
   java.util.concurrent.CountedCompleter.exec(Unknown Source)
   java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
   java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
   java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
   java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)
   java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source)
   java.util.stream.AbstractPipeline.evaluate(Unknown Source)
   java.util.stream.ReferencePipeline.forEach(Unknown Source)
   java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
   main.java.com.djrapitops.plan.utilities.analysis.Analysis.analyzeAdditionalPluginData(Analysis.java:183)
   main.java.com.djrapitops.plan.utilities.analysis.Analysis.analyzeData(Analysis.java:137)
   main.java.com.djrapitops.plan.utilities.analysis.Analysis.analyze(Analysis.java:97)
   main.java.com.djrapitops.plan.utilities.analysis.Analysis$1.run(Analysis.java:70)
   com.djrapitops.plugin.task.RunnableFactory$1.run(RunnableFactory.java:38)
   org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
   org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
   java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   java.lang.Thread.run(Unknown Source)
Error was logged: Dec 02, 19:16:48
```
```
java.lang.NullPointerException
   com.djrapitops.pluginbridge.plan.factions.FactionsData.getServerData(FactionsData.java:71)
   main.java.com.djrapitops.plan.utilities.analysis.Analysis.lambda$analyzeAdditionalPluginData$4(Analysis.java:192)
   java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
   java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
   java.util.stream.AbstractPipeline.copyInto(Unknown Source)
   java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
   java.util.concurrent.CountedCompleter.exec(Unknown Source)
   java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
   java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(Unknown Source)
   java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
   java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
   java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Error was logged: Dec 03, 11:59:58
```
```
java.lang.ClassCastException: main.java.com.djrapitops.plan.systems.webserver.response.NotFoundResponse cannot be cast to main.java.com.djrapitops.plan.systems.webserver.response.InspectPageResponse
   main.java.com.djrapitops.plan.systems.info.BukkitInformationManager.cacheInspectPluginsTab(BukkitInformationManager.java:193)
   main.java.com.djrapitops.plan.systems.info.BukkitInformationManager.cacheInspectPluginsTab(BukkitInformationManager.java:175)
   main.java.com.djrapitops.plan.systems.info.BukkitInformationManager.cacheInspectPluginsTab(BukkitInformationManager.java:143)
   main.java.com.djrapitops.plan.systems.info.BukkitInformationManager$1.process(BukkitInformationManager.java:137)
   main.java.com.djrapitops.plan.systems.queue.ProcessConsumer.consume(ProcessingQueue.java:55)
   main.java.com.djrapitops.plan.systems.queue.ProcessConsumer.consume(ProcessingQueue.java:40)
   main.java.com.djrapitops.plan.systems.queue.Consumer.run(Consumer.java:34)
   com.djrapitops.plugin.task.RunnableFactory$1.run(RunnableFactory.java:38)
   org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
   org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
   java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   java.lang.Thread.run(Unknown Source)
Error was logged: Dec 03, 11:38:18
```

Alright, next time please go to `address:port/debug` - There only unique errors are shown and they're ready for copy pasting directly into github issue tracker.
