### ISSUE TITLE
Servername with a dash (-) causes Inspect page fail to render properly

### ISSUE THREAD

**Issue by DaNseRYT** [Rsl1122/Plan-PlayerAnalytics#453]
![image](https://user-images.githubusercontent.com/33249522/33525715-5a090670-d846-11e7-841b-c7e1f71729f2.png)
(I have not edited the code!)

**Comment by Rsl1122** [comment]
What theme did you set with the config? (Please also post whole theme.yml)

**Comment by Rsl1122** [comment]
Also, open the page on Chrome and screenshot all the errors in the Dev-Tools (Ctrl+Shift+I)

**Comment by DaNseRYT** [comment]
![image](https://user-images.githubusercontent.com/33249522/33525793-bc48347c-d847-11e7-8298-8f519df5a14c.png)

**Comment by DaNseRYT** [comment]
![image](https://user-images.githubusercontent.com/33249522/33525876-9d5513e0-d848-11e7-847b-1cb1f0fb30ae.png)

**Comment by Rsl1122** [comment]
Alright seems like a dash is causing havoc in the world name, try setting alias for world survival-1 to something  else

**Comment by DaNseRYT** [comment]
Thank you! Do to help! I understand Java/html. But I didn't know that because of this " - " this can happen

**Comment by Rsl1122** [comment]
It's my bad for not sanitizing the server name enough :D (Don't close this issue I'll have to sanitize it in the future)
