### ISSUE TITLE
Hide IP

### ISSUE THREAD

**Issue by DaNseRYT** [Rsl1122/Plan-PlayerAnalytics#454]
![image](https://user-images.githubusercontent.com/33249522/33525944-e8faff98-d849-11e7-9b15-0243de01868e.png)
127.0.0.XXX
For some users who prefer anonymity. can make 127.0.XXX.XXX ?
It is better to add this feature in the config (as WEB is available to all)

**Comment by Rsl1122** [comment]
You can choose to remove the table element from the html:
https://github.com/Rsl1122/Plan-PlayerAnalytics/wiki/Html-Customization

Or secure the pages with a login: (Requires SSL Certificate):
https://github.com/Rsl1122/Plan-PlayerAnalytics/wiki/SSL-Certificate-%28HTTPS%29-Set-Up
