### ISSUE TITLE
403 Forbidden when accessing IP:8804/

### ISSUE THREAD

**Issue by Faicu** [Rsl1122/Plan-PlayerAnalytics#46]
**Plan Version:** 2.8.3
**Server Version:** -
**Database Type:**  mysql
**Command Causing Issue:** I can't access website: error 403 forbidden
**Description:**
403 Forbidden when accessing :8804/
http://prntscr.com/eikpku

Startup log: http://prntscr.com/eikq9p

Edited by author

**Comment by Rsl1122** [comment]
> Make sure you're accessing the link given by a command

You need to use /plan inspect <player> or /plan analyze to obtain a link to the proper address.
The webserver blocks other links from being viewed with a 403 Forbidden

**Comment by Faicu** [comment]
ok... Sorry! But, now:
http://pastebin.com/G7CPswsL

**Comment by Faicu** [comment]
http://prntscr.com/eim1hz

**Comment by Rsl1122** [comment]
Moved exceptions to new issue #52
Original issue marked as solved.
