### ISSUE TITLE
IllegalStateException: Player profile was null! when a new player joins

### ISSUE THREAD

**Issue by Rbot48** [Rsl1122/Plan-PlayerAnalytics#465]
```
main.java.com.djrapitops.plan.systems.info.parsing.InspectPageParser Caught: java.lang.IllegalStateException: Player profile was null!
```
/debug doesn't show anything related to this.
Plan 4.1.3

**Comment by Rsl1122** [comment]
I thought I fix

**Comment by Rsl1122** [comment]
Ah it seems that I forgot to remove the extra error logging from this particular exception.
It is properly caught and doesn't cause any harm, just outputs that message. I'll remove it in the next version.
