### ISSUE TITLE
PlanPlayerListener (PlayerJoinEvent) causing lag

### ISSUE THREAD

**Issue by Rbot48** [Rsl1122/Plan-PlayerAnalytics#467]
Timings:
![Timings](https://i.imgur.com/R0DsdUl.png)

Plan v4.1.3
TacoSpigot 1.10.2

**Comment by Rsl1122** [comment]
Update pushed on Spigot with version 4.1.3.1 because of possible severity to performance :)

**Comment by Rbot48** [comment]
A lot better, thank you! :)
