### ISSUE TITLE
Interface improvements for smaller screen sizes

### ISSUE THREAD

**Issue by i0xHeX** [Rsl1122/Plan-PlayerAnalytics#481]
I think it will be better to have more compact webdesign, especially comfortable for small screens and may be smartphones. I didn't check smartphones but on my low screen 1366x768 some text rolls out from boxes, for example information tab and count of online, unique, new and regular players. Yesterday I looked into jar and changed text from UNIQUE PLAYERS / 24h to UNIQUE / 24h. Something better for now, but other tabs also needs optimizitions.
It would be great to make left pane compact as little buttons (see statscraft design) and make more free space to main pages.
Next, Server Health tab. Oh my eyes :D The height of blocks are different! Please, make it more comfortable for perfectionists.
Next, Geolocations tab. Some countries are so small and you even can't pos your cursor to see how many players from this country. Please make zoom ability.

**Comment by Rsl1122** [comment]
- [ ] Improve text overflowing from boxes
- [ ] Reduce size of sidebar when screen is lower resolution
- [ ] Improve vertical spacing of Server health tab
- [ ] HighCharts geolocation map zoom
   - [ ] Check if HighCharts supports zoom on the geolocation map

**Comment by Rsl1122** [comment]
Zoom supported by HighCharts  
https://www.highcharts.com/docs/maps/map-navigation

**Comment by Rsl1122** [comment]
This was my best attempt at the vertical spacing improvement for Server Health tab:
![1](http://puu.sh/zkByi/8170267c72.png)

As you can see it looks pretty terrible.

Bootstrap 3 doesn't support flexbox spacing of the card components & the template is not maintained. (Most likely will not be ported over to Bootstrap 4.)

The spacing just has to be dealt with until Playerbase gets it's own tab.
