### ISSUE TITLE
Player page link opens a new browser tab

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#483]
Spigot 1.12.2 latest
Plan 4.1.4
OS: Mac latest
Browsers: Chrome latest, Firefox latest, Safari latest

From Players tab on server page, click on a player name. A new browser tab with the player data is generated. Plan used to display the player data in the same browser tab.

Did I miss a configuration option?

**Comment by Rsl1122** [comment]
target _blank is added to links on player list to ease browsing the players (the list can have lot of filter/sorting done and a simple back button won't keep the info)
Added in 4.1.0 when the new player list was added

**Comment by SlimeDog** [comment]
Option, please. :)

**Comment by BrainStone** [comment]
I'd apprechiate an option too that prevents using a new tab.  
Especially if the navigation and link structure gets updated as pointed out in #708 the new tab isn't needed.

**Comment by Rsl1122** [comment]
Note to self: PluginBridge needs to be updated to start using the setting

**Comment by Rsl1122** [comment]
Turns out PluginBridge was already using current tab links. This enhancement has been implemented in 4.6.0 DEV3.
