### ISSUE TITLE
Add world name to GameMode slices

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#491]
Click the slices to view used GameMode

With GameModes displayed, one cannot determine the selected world. Please add an appropriate title.

**Comment by Rsl1122** [comment]
Please note that this change can be applied via Html Customization before arrival of the update.

**Comment by SlimeDog** [comment]
Yes. Change applied via Html customization, to be removed when 4.1.5 makes this the default. Thank you.

**Comment by SlimeDog** [comment]
Perfect in 4.1.5-DEV2
