### ISSUE TITLE
PlanWorldChangeListener (PlayerChangedWorldEvent) causing lag

### ISSUE THREAD

**Issue by Rbot48** [Rsl1122/Plan-PlayerAnalytics#493]
Timings:
![Timings](https://i.imgur.com/en0aoy1.png)

Using MySQL
Plan v4.1.4
TacoSpigot 1.10.2

**Comment by Rsl1122** [comment]
Caused by call that reads & possibly writes config
`new WorldAliasSettings().addWorld(worldName);`
