### ISSUE TITLE
[Plugin Support] GriefPreventionPlus

### ISSUE THREAD

**Issue by spannerman79** [Rsl1122/Plan-PlayerAnalytics#494]
With the (re)opening of issue https://github.com/Rsl1122/Plan-PlayerAnalytics/issues/218 I would like to request GriefPreventionPlus ( https://github.com/KaiKikuchi/GriefPreventionPlus ) to have added support.

GriefPreventionPlus (or GPP for short) is mostly used for 1.7.10 Cauldron & its forks as GPP provides better protection for forge based tile entities and forge fakeplayers.

NB: I understand this support will come **after** if/when 1.7.10 support is resolved/added to Plan.

**Comment by Rsl1122** [comment]
Requires #218
