### ISSUE TITLE
Player links are incorrect.

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#5]
Plan web service is http://_myserver_.com:8804/server

Player links on that page are http://:8804/player/_player_
They should be http://_myserver_.com:8804/player/_player_

**Comment by Rsl1122** [comment]
It is likely that the server ip in your server.properties is empty.
If this is the case use

> WebServer.ShowAlternativeServerIP
This setting determines whether or not the setting below is used to show alternative IP to the player, in case you don't want them to see just numbers.

WebServer.AlternativeIP
This IP is used as the address on /plan analyze and /plan inspect <playername> if the setting above is true. 
%port% will be replaced automatically with Webserver.Port
If you have port-forwarded an alternate address to the webserver port, %port% is not required.

https://www.spigotmc.org/wiki/plan-configuration/

**Comment by SlimeDog** [comment]
Yes, server-ip=
I did not understand the Alternative settings. Thanks.

**Comment by Rsl1122** [comment]
The GET Requests are handled by the SocketServer. There is only one player.html with placeholders that are replaced on request.

**Comment by SlimeDog** [comment]
AlternativeIP works only by IP address. FQDN does not work. :(

**Comment by Rsl1122** [comment]
This is caused because browsers request a favicon and there is none atm.
Will be fixed once I figure out how.
