### ISSUE TITLE
/plan goes to /pl, NPE | GamemodeTimesHandler

### ISSUE THREAD

**Issue by brooky1010** [Rsl1122/Plan-PlayerAnalytics#50]
**Plan Version:** Latest one
**Server Version:** Spigot-1.11
**Database Type:** MySQL
**Command Causing Issue:** /plan

**Description:**
When I type /plan, it just shows my plugin list. Which is very, very weird.

**Steps to Reproduce:**

1. Type /plan

**Stack Trace - Console/Errors.txt contents:**
No errors in console.
Error.txt:
```
[Mar 11 10:09:39] main.java.com.djrapitops.plan.data.cache.GetConsumer Caught java.lang.NullPointerException
[Mar 11 10:09:39]   main.java.com.djrapitops.plan.data.handlers.GamemodeTimesHandler.handleChangeEvent(GamemodeTimesHandler.java:54)
[Mar 11 10:09:39]   main.java.com.djrapitops.plan.data.listeners.PlanGamemodeChangeListener$1.process(PlanGamemodeChangeListener.java:49)
[Mar 11 10:09:39]   main.java.com.djrapitops.plan.database.databases.SQLDB.giveUserDataToProcessors(SQLDB.java:632)
[Mar 11 10:09:39]   main.java.com.djrapitops.plan.data.cache.GetConsumer.consume(DataCacheGetQueue.java:88)
[Mar 11 10:09:39]   main.java.com.djrapitops.plan.data.cache.GetConsumer.run(DataCacheGetQueue.java:73)
[Mar 11 10:09:39]   java.lang.Thread.run(Thread.java:745)
[Mar 11 10:09:39] 
[Mar 11 10:09:49] main.java.com.djrapitops.plan.utilities.Analysis$1 Caught java.lang.NullPointerException
[Mar 11 10:09:49]   main.java.com.djrapitops.plan.utilities.Analysis$1.lambda$run$15(Analysis.java:96)
[Mar 11 10:09:49]   java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
[Mar 11 10:09:49]   java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
[Mar 11 10:09:49]   java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
[Mar 11 10:09:49]   java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
[Mar 11 10:09:49]   java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
[Mar 11 10:09:49]   java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[Mar 11 10:09:49]   java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[Mar 11 10:09:49]   java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[Mar 11 10:09:49]   java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[Mar 11 10:09:49] 
```

**Comment by brooky1010** [comment]
Changed gamemode: 
Error in console:
` 11.03 10:09:18 [Server] WARN Unknown or disabled spell prerequisite meteor in path knight, ignoring
11.03 10:09:18 [Server] WARN Unknown or disabled spell prerequisite tendril in path knight, ignoring
11.03 10:09:18 [Server] WARN Unknown or disabled spell prerequisite torch in path beginner, ignoring
11.03 10:09:18 [Server] WARN Unknown or disabled spell prerequisite peek in path beginner, ignoring
11.03 10:09:18 [Server] WARN Unknown or disabled spell prerequisite grenade in path student, ignoring
11.03 10:09:18 [Server] WARN Unknown or disabled spell prerequisite mine in path student, ignoring
11.03 10:09:18 [Server] WARN Unknown or disabled spell prerequisite chop in path student, ignoring
11.03 10:09:18 [Server] WARN Unknown or disabled spell prerequisite rocket in path student, ignoring
11.03 10:09:18 [Server] WARN Unknown or disabled spell prerequisite secure in path student, ignoring
11.03 10:09:18 [Server] WARN Unknown or disabled spell prerequisite admission in path student, ignoring
11.03 10:09:18 [Server] WARN Unknown or disabled spell prerequisite tag in path student, ignoring
11.03 10:09:18 [Server] WARN Unknown or disabled spell prerequisite hat in path apprentice, ignoring
11.03 10:09:18 [Server] WARN Unknown or disabled spell prerequisite platform in path apprentice, ignoring
11.03 10:09:18 [Server] WARN Unknown or disabled spell prerequisite gatling in path apprentice, ignoring
11.03 10:09:18 [Server] WARN Unknown or disabled spell prerequisite walls in path apprentice, ignoring
11.03 10:09:18 [Server] WARN Unknown or disabled spell prerequisite ghast in path apprentice, ignoring
11.03 10:09:18 [Server] WARN Unknown or disabled spell prerequisite cluster in path master, ignoring
11.03 10:09:18 [Server] WARN Unknown or disabled spell prerequisite bomb in path master, ignoring
11.03 10:09:18 [Server] WARN Unknown or disabled spell prerequisite icbm in path master, ignoring
11.03 10:09:18 [Server] WARN Unknown or disabled spell prerequisite nuke in path master, ignoring
11.03 10:09:18 [Server] WARN Unknown or disabled spell prerequisite meteor in path master, ignoring
11.03 10:09:19 [Server] Skipped 48 lines due to rate limit (30/s)
11.03 10:09:19 [Server] Opstarten klaar! (10.399s)! For help, type "help" or "?"
11.03 10:09:19 [Server] [Informatie] ViaVersion detected server version: 1.11(315)
11.03 10:09:19 [Server] [Informatie] Loaded 3 NPCs.
11.03 10:09:19 [Server] [Informatie] Checking for Updates ...
11.03 10:09:19 [Server] [Informatie] Resource pack has not changed, using hash 387503fe02da596d6b51285ef0c79ad98467dc43 (1489185365000 <= 1489185365000)
11.03 10:09:20 [Server] [Informatie] No new version available
11.03 10:09:20 [Server] [Informatie] Essentials found, hooked up custom item handler
11.03 10:09:20 [Server] [Informatie] Loading lost wand data
11.03 10:09:20 [Server] [Informatie] Loaded 0 lost wands
11.03 10:09:20 [Server] [Informatie] Loading automata data
11.03 10:09:20 [Server] [Informatie] Loaded 0 automata
11.03 10:09:20 [Server] [Informatie] Loading image map data from imagemaps.yml
11.03 10:09:20 [Server] [Informatie] Loaded 0 image maps
11.03 10:09:20 [Server] [Informatie] Finished loading data.
11.03 10:09:38 [Server] [Informatie] UUID of player brooky1010 is c5ac5699-0510-484f-9945-71746f292fbf
11.03 10:09:39 [Connect] User brooky1010, IP 78.21.231.75
11.03 10:09:39 [Server] brooky1010 ran command Message of the Day
11.03 10:09:39 [Server] [Informatie] MysticPvP>> brooky1010 has joined the Mystic Realm.
11.03 10:09:39 [Server] [Informatie] Added c5ac5699-0510-484f-9945-71746f292fbf to Cache.
11.03 10:09:39 [Server] [Informatie] Added c5ac5699-0510-484f-9945-71746f292fbf to Cache.
11.03 10:09:39 [Server] ERROR Caugth java.lang.NullPointerException. It has been logged to the Errors.txt
11.03 10:09:49 [Server] [Informatie] Analysis | Starting Boot Analysis..
11.03 10:09:49 [Server] ERROR Some data might be corrupted: c5ac5699-0510-484f-9945-71746f292fbf
11.03 10:09:49 [Server] ERROR Caugth java.lang.NullPointerException. It has been logged to the Errors.txt
11.03 10:09:49 [Server] [Informatie] Analysis | Analysis Complete.
11.03 10:09:51 [Server] [Informatie] CONSOLE issued server command: /list
11.03 10:09:51 [Server] [Informatie] Knight: [Knight] Brooky1010
11.03 10:09:53 [Server] [Informatie] brooky1010 issued server command: /plan
11.03 10:10:23 [Server] [Informatie] CONSOLE issued server command: /list
11.03 10:10:23 [Server] [Informatie] Knight: [Knight] Brooky1010
11.03 10:10:55 [Server] [Informatie] CONSOLE issued server command: /list
11.03 10:10:55 [Server] [Informatie] Knight: [Knight] Brooky1010
11.03 10:11:19 [Server] WARN Plugin Plan v2.8.3 generated an exception while executing task 122
11.03 10:11:19 [Server] [Informatie] java.lang.NullPointerException
11.03 10:11:19 [Server] [Informatie] at main.java.com.djrapitops.plan.data.handlers.GamemodeTimesHandler.saveToCache(GamemodeTimesHandler.java:73) ~[?:?]
11.03 10:11:19 [Server] [Informatie] at main.java.com.djrapitops.plan.data.cache.DataCacheHandler$3.process(DataCacheHandler.java:239) ~[?:?]
11.03 10:11:19 [Server] [Informatie] at main.java.com.djrapitops.plan.data.cache.DataCacheHandler.getUserDataForProcessing(DataCacheHandler.java:146) ~[?:?]
11.03 10:11:19 [Server] [Informatie] at main.java.com.djrapitops.plan.data.cache.DataCacheHandler.getUserDataForProcessing(DataCacheHandler.java:159) ~[?:?]
11.03 10:11:19 [Server] [Informatie] at main.java.com.djrapitops.plan.data.cache.DataCacheHandler.saveHandlerDataToCache(DataCacheHandler.java:242) ~[?:?]
11.03 10:11:19 [Server] [Informatie] at main.java.com.djrapitops.plan.data.cache.DataCacheHandler.lambda$saveHandlerDataToCache$1(DataCacheHandler.java:229) ~[?:?]
11.03 10:11:19 [Server] [Informatie] at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_101]
11.03 10:11:19 [Server] [Informatie] at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_101]
11.03 10:11:19 [Server] [Informatie] at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_101]
11.03 10:11:19 [Server] [Informatie] at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_101]
11.03 10:11:19 [Server] [Informatie] at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) ~[?:1.8.0_101]
11.03 10:11:19 [Server] [Informatie] at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[?:1.8.0_101]
11.03 10:11:19 [Server] [Informatie] at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_101]
11.03 10:11:19 [Server] [Informatie] at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401) ~[?:1.8.0_101]
11.03 10:11:19 [Server] [Informatie] at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734) ~[?:1.8.0_101]
11.03 10:11:19 [Server] [Informatie] at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160) ~[?:1.8.0_101]
11.03 10:11:19 [Server] [Informatie] at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174) ~[?:1.8.0_101]
11.03 10:11:19 [Server] [Informatie] at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:1.8.0_101]
11.03 10:11:19 [Server] [Informatie] at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_101]
11.03 10:11:19 [Server] [Informatie] at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583) ~[?:1.8.0_101]
11.03 10:11:19 [Server] [Informatie] at main.java.com.djrapitops.plan.data.cache.DataCacheHandler.saveHandlerDataToCache(DataCacheHandler.java:228) ~[?:?]
11.03 10:11:19 [Server] [Informatie] at main.java.com.djrapitops.plan.data.cache.DataCacheHandler$1.run(DataCacheHandler.java:106) ~[?:?]
11.03 10:11:19 [Server] [Informatie] at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.jar:git-Spigot-f950f8e-0fa1ad2]
11.03 10:11:19 [Server] [Informatie] at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.11.jar:git-Spigot-f950f8e-0fa1ad2]
11.03 10:11:19 [Server] [Informatie] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
11.03 10:11:19 [Server] [Informatie] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
11.03 10:11:19 [Server] [Informatie] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
11.03 10:11:27 [Server] [Informatie] CONSOLE issued server command: /list
11.03 10:11:27 [Server] [Informatie] Knight: [Knight] Brooky1010
11.03 10:11:32 [Server] [Informatie] brooky1010 issued server command: /gmc
11.03 10:11:32 [Server] ERROR Could not pass event PlayerGameModeChangeEvent to Plan v2.8.3
11.03 10:11:32 [Server] [Informatie] org.bukkit.event.EventException
11.03 10:11:32 [Server] [Informatie] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.jar:git-Spigot-f950f8e-0fa1ad2]
11.03 10:11:32 [Server] [Informatie] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.jar:git-Spigot-f950f8e-0fa1ad2]
11.03 10:11:32 [Server] [Informatie] at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.jar:git-Spigot-f950f8e-0fa1ad2]
11.03 10:11:32 [Server] [Informatie] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.jar:git-Spigot-f950f8e-0fa1ad2]
11.03 10:11:32 [Server] [Informatie] at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.setGameMode(CraftPlayer.java:788) [spigot-1.11.jar:git-Spigot-f950f8e-0fa1ad2]
11.03 10:11:32 [Server] [Informatie] at com.earth2me.essentials.commands.Commandgamemode.run(Commandgamemode.java:76) [Essentials-2.x-SNAPSHOT.jar:?]
11.03 10:11:32 [Server] [Informatie] at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:180) [Essentials-2.x-SNAPSHOT.jar:?]
11.03 10:11:32 [Server] [Informatie] at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:526) [Essentials-2.x-SNAPSHOT.jar:?]
11.03 10:11:32 [Server] [Informatie] at com.earth2me.essentials.Essentials.onCommand(Essentials.java:401) [Essentials-2.x-SNAPSHOT.jar:?]
11.03 10:11:32 [Server] [Informatie] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.11.jar:git-Spigot-f950f8e-0fa1ad2]
11.03 10:11:32 [Server] [Informatie] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.11.jar:git-Spigot-f950f8e-0fa1ad2]
11.03 10:11:32 [Server] [Informatie] at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) [spigot-1.11.jar:git-Spigot-f950f8e-0fa1ad2]
11.03 10:11:32 [Server] [Informatie] at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1335) [spigot-1.11.jar:git-Spigot-f950f8e-0fa1ad2]
11.03 10:11:32 [Server] [Informatie] at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1170) [spigot-1.11.jar:git-Spigot-f950f8e-0fa1ad2]
11.03 10:11:32 [Server] [Informatie] at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.11.jar:git-Spigot-f950f8e-0fa1ad2]
11.03 10:11:32 [Server] [Informatie] at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.11.jar:git-Spigot-f950f8e-0fa1ad2]
11.03 10:11:32 [Server] [Informatie] at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.jar:git-Spigot-f950f8e-0fa1ad2]
11.03 10:11:32 [Server] [Informatie] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
11.03 10:11:32 [Server] [Informatie] at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
11.03 10:11:32 [Server] [Informatie] at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.jar:git-Spigot-f950f8e-0fa1ad2]
11.03 10:11:32 [Server] [Informatie] at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.jar:git-Spigot-f950f8e-0fa1ad2]
11.03 10:11:32 [Server] [Informatie] at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-f950f8e-0fa1ad2]
11.03 10:11:32 [Server] [Informatie] at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-f950f8e-0fa1ad2]
11.03 10:11:32 [Server] [Informatie] at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-f950f8e-0fa1ad2]
11.03 10:11:32 [Server] [Informatie] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
11.03 10:11:32 [Server] [Informatie] Caused by: java.lang.NullPointerException
11.03 10:11:32 [Server] [Informatie] at main.java.com.djrapitops.plan.data.handlers.GamemodeTimesHandler.handleChangeEvent(GamemodeTimesHandler.java:54) ~[?:?]
11.03 10:11:59 [Server] Skipped 10 lines due to rate limit (30/s) `

**Comment by Rsl1122** [comment]
Hey.
I have not been able to reproduce /plan -> plugin list issue.
What plugins do you have installed on your server?

**Comment by Rsl1122** [comment]
Rest of the Exceptions have been caused by a null value in GameModeTimes map for GameMode.SURVIVAL
I'll have to figure out why such value is saved there.
