### ISSUE TITLE
Support for LagMonitor

### ISSUE THREAD

**Issue by Rsl1122** [Rsl1122/Plan-PlayerAnalytics#503]
LagMonitor holds useful data about a lot of system information at runtime.
It fills some gaps that Plan doesn't offer directly

- Ping
- Access to Stacktraces of running threads
- Access to Java environment variables (mbeans)
- Blocking operations on the main thread check
- Information about native OS
- Heap information
- Server Timings report

https://www.spigotmc.org/resources/lagmonitor.21348/
https://github.com/games647/LagMonitor

**Comment by LightningBladeXYZ** [comment]
For timings, would it be worth having the plugin pass the timings command to spigot (maybe on a button press) and then placing the resultant url in an iframe?

**Comment by Rsl1122** [comment]
Buttons executing commands sound unsafe on servers that haven't enabled login (HTTPS)

I'll consider a special page for timings redirect when HTTPS is enabled.

**Comment by LightningBladeXYZ** [comment]
Ok, I mean it could be automatic too, but a server constantly receiving timing report commands would be a little spammy

**Comment by Rsl1122** [comment]
Closing the issue as the suggestion has been added to a multi-issue
