### ISSUE TITLE
Plugin Accordions have bad ID values

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#504]
Spigot 1.12.2 latest
Plan 4.1.4
Factions/Massive-Core 2.13.6

Two factions, but both links on the Plugins>Factions tab point to the same #session_faction_nnnnnnnn
Both links open the same faction detail.

**Comment by SlimeDog** [comment]
The "missing" faction is displayed correctly on the Player inspect page, Plugins>Factions tab.

**Comment by Rsl1122** [comment]
Most likely affects all plugin accordions then. (Kingdoms, Factions, Towny)

**Comment by SlimeDog** [comment]
I have only Factions (of those three).

Problem seems to be related to be production->test database kludge. Starting with an empty database on the test server, then connecting both players, all is reported correctly. Mea culpa.

**Comment by Rsl1122** [comment]
Confirmed working with 2 factions, seems like I've used creation date as an ID, so if two manage to have the same millisecond that will break it. I'll enhance that.

**Comment by Rsl1122** [comment]
In addition to that the id includes session_
Some accordions state their parent is session_accordion
Kingdoms accordion has an id of towny_accordion

**Comment by SlimeDog** [comment]
@Rsl1122 said
> Confirmed working with 2 factions, seems like I've used creation date as an ID, so if two manage to have the same millisecond that will break it.

That is exactly what I did manage (by creating them manually -- my bad!). When I recreated them (see above), problem disappeared. But agree that a more expansive ID would be good. Maybe including the NAME, which is guaranteed (in Factions) to be unique.
