### ISSUE TITLE
Player not found

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#505]
Spigot 1.12.2
Plan 4.1.4

Server>Players tab displays two players (test server)

The inspect page for one player displays
```
Player just registered, so the data was not yet in the database. Please wait until they log off or use /plan inspect
```
The player has connected and logged out twice, which is displayed on the Server>Player tab.

**/plan inspect** yields the same URL, and the same result.

**Comment by Rsl1122** [comment]
Does it still do that I'd you do /plan reload?

**Comment by SlimeDog** [comment]
Yes.
```
plan reload
plan analyze
```
from the console. The play time for the "missing" player -- still connected -- continues to increase. But the player inspect page reports no data in the database.

This may be due to the fact that I'm copying the database from production server into the test server. I'll continue to investigate. Nothing needed for now until I learn more.

**Comment by SlimeDog** [comment]
Problem seems to be related to my production->test database kludge. Starting with an empty database on the test server, then connecting both players, all is reported correctly. Mea culpa.
