### ISSUE TITLE
Punchcard x-axis labels are incorrect TZ

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#519]
Plan 4.1.5-DEV2 (and previous)

The issue is that, even if UserServerTime:true (ie., report localtime), the timespan for Punchcard is still midnight-to-midnight. But the x-axis labels do not reflect that.

I cleared the database and started fresh. It is currently 16:30 localtime (California USA). The single connection is now 30 minutes old. This graph illustrates the issue. The dot is in the correct position on the graph (2/3 along the x-axis), assuming midnight-to-midnight display. But the x-axis labels do not reflect midnight-to-midnight or that the dot is at 16:00-16:30. The x-axis labels are shifted by the difference between localtime and UTC.
![untitled](https://user-images.githubusercontent.com/17748923/35760758-434ddee4-0837-11e8-8530-16ab8b40edda.png)

**Comment by Rsl1122** [comment]
This fix can be applied with HtmlCustomization
