### ISSUE TITLE
Feature request: Allow comments in config.yml

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#522]
Plan 4.1.5-b2 and previous

Comments entered in _config.yml_ are removed on **/plan reload**.

It would be nice if they were retained.

**Comment by Rsl1122** [comment]
Requires a change to APF

**Comment by Rsl1122** [comment]
Looks like new comments above config nodes are already supported:
![1](http://puu.sh/zkAJW/8ffa36ca64.png)
_Screenshot after reload_

Currently old edited comments get overridden by default comments in the config.yml that are in the jar.

After writing the improvements:
- Default comments now override only if existing comment is less lines
- Comments added after values are moved to above the key (like in the screenshot)

**Comment by SlimeDog** [comment]
Thank you.
