### ISSUE TITLE
Connection succeeded, but Bungee failed to connect to this server.

### ISSUE THREAD

**Issue by BlackBeltPanda** [Rsl1122/Plan-PlayerAnalytics#531]
**Description of the issue**
I just updated from 4.0.7 to 4.1.6 and can no longer access the individual servers on the webserver. I can access the Bungee webserver, however.
When running "/plan m setup" on the individual servers, it outputs: "Connection succeeded, but Bungee failed to connect to this server. Use Connection debug commands for more.". There's only one error in the error log for the individual server; I'm not sure it's related.

Bungee debug: https://pastebin.com/raw/BhWL0r2x
Server debug: https://pastebin.com/raw/JgsqUw7A
Server error: https://pastebin.com/raw/HXYe9ssZ

On the webserver, attempting to click "analysis" for any of the individual servers just displays this page, which refreshes every few moments: https://i.gyazo.com/ef9d7eaf3ff5be8688c4c1c208598ea4.png
The only error I see on the webserver is this one: https://i.gyazo.com/c24881e664b071abf0b58dbde65b3145.png

Bungee Plan Config: https://pastebin.com/raw/G7nkfWbG
Server Plan Config: https://pastebin.com/raw/4Q128fZ1

Debug page info:
### Server Information
**Plan Version:** 4.1.6
**Server:** BungeeCord git:Waterfall-Bootstrap:1.12-SNAPSHOT:7bb18dc:147 git:Waterfall-Bootstrap:1.12-SNAPSHOT:7bb18dc:147
**Database:** MySQL schema v13

**Operating SubSystem:** Linux (amd64) version 4.10.0-24-generic
**Java Version:** 1.8.0_131, Oracle Corporation
**Java VM Version:** Java HotSpot(TM) 64-Bit Server VM version 25.131-b11, Oracle Corporation
**Java VM Flags:** [-Xmx1024M, -Xms1024M, -XX:+UseG1GC, -XX:+UnlockExperimentalVMOptions, -XX:MaxGCPauseMillis=100, -XX:+DisableExplicitGC, -XX:TargetSurvivorRatio=90, -XX:G1NewSizePercent=50, -XX:G1MaxNewSizePercent=80, -XX:InitiatingHeapOccupancyPercent=10, -XX:G1MixedGCLiveThresholdPercent=50, -XX:+AggressiveOpts, -XX:+AlwaysPreTouch, -XX:+UseStringDeduplication, -Dwaterfall.acceptInvalidPackets=true, -Djline.terminal=jline.UnsupportedTerminal]

**Connection Log:**

Server Address | Request Type | Response | Sent
-- | -- | -- | --
http://skyblock.pandacraft.org:8093 | Out: GenerateNetworkPageContentRequest | 200 | 
158.69.120.112 | In:  /info/cachenetworkpagecontentrequest | 200 | 
http://towny.pandacraft.org:8095 | Out: GenerateNetworkPageContentRequest | 200 | 
http://plots.pandacraft.org:8097 | Out: GenerateNetworkPageContentRequest | 200 | 

**Servers:**

Server Name | Address | UUID 
-- | -- | --
Towny | http://towny.pandacraft.org:8095 | b094a114-8cd3-3fc2-b356-8e97e2626f07
Skyblock | http://skyblock.pandacraft.org:8093 | 75be439d-f052-363b-a664-40defef4baf8
Plots | http://plots.pandacraft.org:8097 | 36c5d2db-202c-3d88-ae80-0268bef57c98

### Logged Errors
```
com.djrapitops.plan.api.exceptions.connection.WebFailException: Exception during Network Page Parsing
   com.djrapitops.plan.system.info.BungeeInfoSystem.updateNetworkPage(BungeeInfoSystem.java:42)
   com.djrapitops.plan.system.tasks.bukkit.NetworkPageRefreshTask.lambda$run$0(NetworkPageRefreshTask.java:15)
   com.djrapitops.plan.system.info.connection.WebExceptionLogger.logIfOccurs(WebExceptionLogger.java:24)
   com.djrapitops.plan.system.tasks.bukkit.NetworkPageRefreshTask.run(NetworkPageRefreshTask.java:15)
   com.djrapitops.plugin.task.RunnableFactory$2.run(RunnableFactory.java:47)
   net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   java.lang.Thread.run(Thread.java:748)
Caused by:
com.djrapitops.plan.api.exceptions.ParseException: java.lang.IllegalStateException: Settings are not supposed to be called before ConfigSystem is Enabled!
   com.djrapitops.plan.system.webserver.pages.parsing.NetworkPage.toHtml(NetworkPage.java:72)
   com.djrapitops.plan.system.info.BungeeInfoSystem.updateNetworkPage(BungeeInfoSystem.java:39)
   com.djrapitops.plan.system.tasks.bukkit.NetworkPageRefreshTask.lambda$run$0(NetworkPageRefreshTask.java:15)
   com.djrapitops.plan.system.info.connection.WebExceptionLogger.logIfOccurs(WebExceptionLogger.java:24)
   com.djrapitops.plan.system.tasks.bukkit.NetworkPageRefreshTask.run(NetworkPageRefreshTask.java:15)
   com.djrapitops.plugin.task.RunnableFactory$2.run(RunnableFactory.java:47)
   net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   java.lang.Thread.run(Thread.java:748)
Caused by:
java.lang.IllegalStateException: Settings are not supposed to be called before ConfigSystem is Enabled!
   com.djrapitops.plan.system.settings.Settings.lambda$getConfig$0(Settings.java:193)
   com.djrapitops.plugin.utilities.Verify.nullCheck(Verify.java:189)
   com.djrapitops.plan.system.settings.Settings.getConfig(Settings.java:193)
   com.djrapitops.plan.system.settings.Settings.isTrue(Settings.java:129)
   com.djrapitops.plan.system.database.databases.sql.processing.QueryStatement.<init>(QueryStatement.java:32)
   com.djrapitops.plan.system.database.databases.sql.processing.QueryStatement.<init>(QueryStatement.java:27)
   com.djrapitops.plan.system.database.databases.sql.tables.TPSTable$4.<init>(TPSTable.java:181)
   com.djrapitops.plan.system.database.databases.sql.tables.TPSTable.getPeakPlayerCount(TPSTable.java:181)
   com.djrapitops.plan.system.database.databases.sql.operation.SQLFetchOps.getPeakPlayerCount(SQLFetchOps.java:231)
   com.djrapitops.plan.system.webserver.pages.parsing.NetworkPage.peakTimes(NetworkPage.java:91)
   com.djrapitops.plan.system.webserver.pages.parsing.NetworkPage.toHtml(NetworkPage.java:48)
   com.djrapitops.plan.system.info.BungeeInfoSystem.updateNetworkPage(BungeeInfoSystem.java:39)
   com.djrapitops.plan.system.tasks.bukkit.NetworkPageRefreshTask.lambda$run$0(NetworkPageRefreshTask.java:15)
   com.djrapitops.plan.system.info.connection.WebExceptionLogger.logIfOccurs(WebExceptionLogger.java:24)
   com.djrapitops.plan.system.tasks.bukkit.NetworkPageRefreshTask.run(NetworkPageRefreshTask.java:15)
   com.djrapitops.plugin.task.RunnableFactory$2.run(RunnableFactory.java:47)
   net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   java.lang.Thread.run(Thread.java:748)
Error was logged: Feb 20, 06:54:32
```
- [ ] Fixed

### Benchmarks
```
66 ms     Init Database
4 ms      Initializing locale
3459 ms   Processed AnalysisPageResponse$$Lambda$185/605287325.
4 ms      Processed BungeePlayerRegisterProcessor.
1205 ms   Processed InfoSystem$$Lambda$141/1802188146.
7 ms      Processed NetworkSettings$$Lambda$149/1269230672.
2 ms      Processed TPSInsertProcessor.
0 ms      Register Listeners
5 ms      WebServer Initialization
```

**Comment by Rsl1122** [comment]
I looked at the debug pages and can't really figure why it wouldn't be working. All the connections have a 200 next to them in the connection logs, so I'm guessing it is some issue with the caching.

I'll try to debug further on my own system.
Please run /planbungee con & post what it says (From the connection log I would expect all green)

**Comment by BlackBeltPanda** [comment]
"/planbungee con" results:
http://skyblock.pandacraft.org:8093: HTTP : External : To:OK : From:OK
http://towny.pandacraft.org:8095: HTTP : External : To:OK : From:OK
http://plots.pandacraft.org:8097: HTTP : External : To:OK : From:OK

**Comment by Rsl1122** [comment]
I went ahead and looks like I can't break my own test system the same way.
It also looks like your system has cached the refresh page for each server and when the page is accessed nothing actually gets done by the other servers (They're never called to run analysis)

Short term fix may be /planbungee reload for the time being.
I'll try to prevent caching of the refresh page in the future..

**Comment by BlackBeltPanda** [comment]
I tried "/planbungee reload" several times, didn't help. =(
I'll do more testing when I get home from work. Only had a couple hours to play with it this morning.

**Comment by mibby** [comment]
Just to weigh in, I'm experiencing the exact same problem as of Plan 4.1.5 & 4.1.6 too as of updating today. Plan 4.1.4, I am able to access my server statistics via BungeeCord Plan's network page fine.

* Reloading with ```/planbungee reload``` does not fix the problem. 
* ```/planbungee con``` outputs ```HTTP : External : To:OK : From:OK```.
* The Bukkit instance of Plan and BungeeCord instance of Plan are both running on internal IP 0.0.0.0 (localhost). BungeeCord on port 9125, Bukkit on port 9126.
* Both Bukkit and Bungee instances of Plan are connected to the same MySQL database and host, localhost.
* The server list in the Bungee Plan config correctly matches the uuid and port of the Bukkit server. Likewise, the Bukkit Plan ServerInfoFile matching the Bungee Web Address info.

**Comment by BlackBeltPanda** [comment]
Still doing it with that version except now it runs the analysis on the bukkit instance each time, which, I imagine, is expected without caching.

**Comment by Rsl1122** [comment]
From the debug pages it would appear as if it wasn't sending Bungee the analysis page at all.. I'll have to investigate a bit.

**Comment by Rsl1122** [comment]
I added more debug logging to see what is going on, is it being cached locally or what - I couldn't quite figure it out from the code. I tried to do some requests to manually force it to cache the server page, but it seems that the server page was never placed in the transfer table (database) in the first place.

The debug logs should shine some light on what's the cause
https://www.dropbox.com/s/1b8nl10sn525xcm/Plan-4.1.6-b2.jar?dl=1

4.1.6-b2 is commit 3cb195592877fe0c3be3a77df8cfe5d7c99294f0
https://github.com/Rsl1122/Plan-PlayerAnalytics/commits/4.1.7

**Comment by BlackBeltPanda** [comment]
I've updated to 4.1.6-b2. The above debug links should show the latest info, now.

**Comment by Rsl1122** [comment]
Looks like we've found our culprit:

`Exception during request: com.djrapitops.plan.api.exceptions.connection.TransferDatabaseException: com.djrapitops.plan.api.exceptions.database.DBException: com.mysql.jdbc.PacketTooBigException: Packet for query is too large (15842709 > 4194304). You can change this value on the server by setting the max_allowed_packet' variable., running locally.`

**Comment by Rsl1122** [comment]
I'll try to solve this by splitting the sent page to smaller segments

**Comment by Rsl1122** [comment]
4.1.6-b3 contains a split for server pages:
https://www.dropbox.com/s/04uqftr03x58px8/Plan-4.1.6-b3.jar?dl=0

If it works 4.1.7 can be released.

**Comment by Rsl1122** [comment]
Brute force test of 20 million characters passed.

**Comment by Rsl1122** [comment]
4.2.0 will transfer the pages over HTTP instead of MySQL again to fix this issue properly
