### ISSUE TITLE
Bug: Server page inside a network squished to one side

### ISSUE THREAD

**Issue by LightningBladeXYZ** [Rsl1122/Plan-PlayerAnalytics#542]
The current issue seems to be that the page seems to want to compress itself to one side as if there were some column it was trying to fit into. I'm currently trying to load the page from a server in a network from the webpanel of the bungee server and I get this:

![screenshot 34](https://user-images.githubusercontent.com/27926588/36911439-6e7177d8-1e3b-11e8-82ba-a06ae77e6903.png)

**Comment by Rsl1122** [comment]
Could you send the html (Ctrl+S on chrome)?

**Comment by LightningBladeXYZ** [comment]
Sure, here is the hastebin link (since github says filetype not supported, unless you want a txt, I guess):

https://hastebin.com/quyorubaba.xml

**Comment by Rsl1122** [comment]
I'll look at this, one moment.

**Comment by LightningBladeXYZ** [comment]
Also, just a small sitrep, it won't let me click on the sidebar either

**Comment by Rsl1122** [comment]
Looks like the page would end abruptly `[1519695325109,0.0],</script>` which would suggest that a part is missing and chrome added the end tags.

This is most likely some unintended side-effect of eba17eb127247bee1da0806f787e6d0302695c04

Try running `/plan analyze` on that server and view the page again to see if the problem persists

**Comment by LightningBladeXYZ** [comment]
Works now :)

**Comment by LightningBladeXYZ** [comment]
Thanks, I'll just close this then

**Comment by Rsl1122** [comment]
Alright, I'll try to prevent it from happening again when this is fixed.

**Comment by Rsl1122** [comment]
Caused by #552
