### ISSUE TITLE
Version incorrect

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#554]
Spigot 1.12.2
Plan 4.2.0-b1

Version is 4.1.7-b1
- plugin.yml
- bungee.yml
- HTML pages as displayed 
- /version Plan

**Comment by Rsl1122** [comment]
Intended so that servers using dev versions get update notifications when 4.2.0 is released.

**Comment by SlimeDog** [comment]
Ah. Clever. My update-checker works differently, but I understand (and appreciate).
