### ISSUE TITLE
[Suggestion] BungeeAdminTools Support

### ISSUE THREAD

**Issue by DKing328** [Rsl1122/Plan-PlayerAnalytics#570]
For suggestions use any format you want. :)

I'd love to see support for BungeeAdminTools, similar to how LiteBans works with Plan. Looking forward!

https://www.spigotmc.org/resources/bungee-admin-tools-premium-edition.37880/
https://github.com/alphartdev/BungeeAdminTools

**Comment by Rsl1122** [comment]
Requires #571

**Comment by Rsl1122** [comment]
Closing the issue as the suggestion has been added to a multi-issue
