### ISSUE TITLE
Issues with Bungee Geolocation fetch - Inaccurate, MySQL Performance

### ISSUE THREAD

**Issue by UnioDex** [Rsl1122/Plan-PlayerAnalytics#585]
Version: Plan 4.3.1 Bungee Mode

Since i installed Plan my MySQL server's CPU is so high. I checked slow query logs and it is filled with these:
https://pastebin.com/Uv6KH1P6

Seems like selecting geolocations spends a lot of resource.

**Comment by Rsl1122** [comment]
Going to have to move the max value calculation to java from sql I guess

**Comment by UnioDex** [comment]
@Rsl1122 isn't it will only reduce BungeeCord's CPU? MySQL CPU usage is same as BungeeCord right now. But eats %400 and server barely handle it. (My server: https://www.soyoustart.com/en/offers/1801sys012.xml)

**Comment by Rsl1122** [comment]
It is still different kind of execution so it might reduce cpu usage. I have to rework this anyway since I'm getting reports on discord that it produces inaccurate results

**Comment by Rsl1122** [comment]
Fixed in 4.3.2-DEV2
https://github.com/Rsl1122/Plan-PlayerAnalytics/releases/tag/4.3.2-DEV2
