### ISSUE TITLE
Network Players  (http://192.168.2.201:8804/server/players) opens Geolocation

### ISSUE THREAD

**Issue by valenvaio** [Rsl1122/Plan-PlayerAnalytics#588]
If open http://192.168.2.101:8804/server/ 
and click **Network Players**  (http://192.168.2.201:8804/**server/**players) then opens Geolocation.

If open http://192.168.2.201:8804/players 
and click **Network Servers** (http://192.168.2.201:8804/**server**/)
and click **Network Players**  (http://192.168.2.201:8804/**players**) then opens players and etc.

**Comment by Rsl1122** [comment]
Which one of these options do you mean?

- from **/server** clicking Network Players goes to **/server/players** instead of **/players**
- from **/players** clicking Network Servers goes to **/server**, but opens Geolocations tab

**Comment by valenvaio** [comment]
if you open the page http://192.168.2.101:8804/server/ then there is an incorrect address generated on the Network of players link and Geolocation is being played back instead of players. The link is genre as http://192.168.2.201:8804/server/players and it should be http://192.168.2.201:8804/payers.

**Comment by Rsl1122** [comment]
Could you try DEV2 to see if the issue has already been fixed

https://github.com/Rsl1122/Plan-PlayerAnalytics/releases
