### ISSUE TITLE
MinecraftMarket support

### ISSUE THREAD

**Issue by MajorSkillage** [Rsl1122/Plan-PlayerAnalytics#590]
Instructions for issue reporting:
- Write description of the issue
- Copy possible errors here, If you're using 4.0.7+ head to `<address>/debug` & copy the information to the ticket.

For suggestions use any format you want. :)

----

[Suggestion] add support for MinecraftMarket as it's widely used (when it wants to work .-.)
https://github.com/MinecraftMarket/MinecraftMarket-Plugin

<REPLACE with error / debug-page contents>

**Comment by Rsl1122** [comment]
Added to main PluginData suggestion issue
