### ISSUE TITLE
Network Health Info

### ISSUE THREAD

**Issue by C-N1** [Rsl1122/Plan-PlayerAnalytics#601]
Suggestion/BungeeCord

I had an idea about adding a server health monitor to the network page. 
The reason it occurred to me that it may be a good idea is because I have a bungee network with 5 servers. Because it is spread out, each of the server playerbase development charts are kinda useless. People are sticking around, but the charts don't really reveal it. If a player is active on the survival server but took a quick look at the creative and chaos server, then those two worlds will have a "inactive" player cluttering the chart. If that makes sense? And the lobby shows people joining often but as inactive due to their short login time on that server.

Thanks :)

**Comment by Rsl1122** [comment]
First version of network health info has been implemented. The page is mostly useful for the playerbase charts at the moment.

More information like per-server performance will be added once the server analysis can be moved over on Bungee.
