### ISSUE TITLE
Wrong table header order (LiteBans)

### ISSUE THREAD

**Issue by Argetan** [Rsl1122/Plan-PlayerAnalytics#605]
**Description**
When viewing the data of a specific player, the LiteBans tab isn't working correctly. The order of the headers does not match the content of the table, see the screenshot below:
![screen shot 2018-06-11 at 15 40 52](https://user-images.githubusercontent.com/19390615/41235090-395d9ed0-6d8e-11e8-874f-9dbfd7c6534d.png)

I think this is just a visual bug which can be fixed by changing the `<thead>` associated with it.

**Edit:** I'm using the latest stable release of Firefox Developer Edition on OS X. 
**Edit 2:** Using Litebans v. 2.2.6 and Plan v. 4.3.2.

**Comment by Rsl1122** [comment]
I'm guessing this is player page, thanks for bringing it up.
