### ISSUE TITLE
Improve .travis.yml

### ISSUE THREAD

**Issue by Argetan** [Rsl1122/Plan-PlayerAnalytics#607]
**Small suggestion**
Regarding this line:
https://github.com/Rsl1122/Plan-PlayerAnalytics/blob/0b3e075e1ea9e4a2bb06033b50f80caffe37c6bf/.travis.yml#L8

This appears to be using an absolute path, but since we are already in the `PlanPluginBridge/` folder can't we run it as a relative path? So the config section would be this:
```yaml
...
before_install:
  - pwd
  - cd PlanPluginBridge # Change into the right directory
  - ls
  - mvn install:install-file -Dfile=./PlanPluginBridge-4.3.0.jar -DpomFile=./pom.xml # Using relative paths because we are already in the right directory
  - cd ../Plan
  - ls
...
```

Not an expert on Travis so it might be that changing it this way makes it do something completely different...

The reason I'm pointing this out is that you linked to it from [your set up guide](https://github.com/Rsl1122/Plan-PlayerAnalytics/wiki/Project-Setup).

(Note: for me it worked this way, using the absolute path didn't, it's just a minor thing for when someone wants to set up their own fork of the repository).

**Comment by Rsl1122** [comment]
Imma test this out

**Comment by Rsl1122** [comment]
Worked.

Improvement added in commit 7f58fff786430de5abbba84538d56df0fd4a3665
Build result: https://travis-ci.org/Rsl1122/Plan-PlayerAnalytics/builds/390891932
