### ISSUE TITLE
Banned tag added to players whilst not being banned (LiteBans)

### ISSUE THREAD

**Issue by Argetan** [Rsl1122/Plan-PlayerAnalytics#608]
**Description**
When going over the player list it sometimes shows the following:
![screen shot 2018-06-11 at 20 38 42](https://user-images.githubusercontent.com/19390615/41250711-fea1c5ee-6db7-11e8-9144-343483fadf3f.png)

However, this player is not banned. I figured out that this happens when a player was permanently banned once but manually unbanned. I'm not sure if it handles temporary bans correctly as I couldn't quickly find an example.

**Comment by Rsl1122** [comment]
Has the player joined after they have been unbanned? Plan handles ban status via login listener & PluginData getters

**Comment by Argetan** [comment]
Yes, the player was online today, just logged off, he/she was banned quite long ago before we had Plan (just installed it today). I'm not sure when they were unbanned, but it was quite a while back at least.

**Comment by Rsl1122** [comment]
I think the litebans plugindata marks them as banned if they have a single ban record in litebans database.

I'll rework this during PluginData update for Data Refactoring #604
