### ISSUE TITLE
Jobs Level Values Flipped

### ISSUE THREAD

**Issue by MadWookie** [Rsl1122/Plan-PlayerAnalytics#615]
![1](https://imgur.com/zVBJDKf.png)

Average/Total level values are flipped.

**Comment by Rsl1122** [comment]
https://github.com/Rsl1122/Plan-PlayerAnalytics/blob/master/PlanPluginBridge/src/main/java/com/djrapitops/pluginbridge/plan/jobs/JobsData.java#L79
