### ISSUE TITLE
[Feature Request] GDPR - User data export command

### ISSUE THREAD

**Issue by Morsmorse** [Rsl1122/Plan-PlayerAnalytics#620]
An export command that exports all stored data from a user in a file (html/json/txt/...) Which then can be send to this player. This is useful for networks that don't allow users to access the Plan-Webinterface but want to comply with the gdpr.

For example: `/plan export username`

**Comment by Rsl1122** [comment]
I made it simple to get the json files - access a player's page and add /raw to the end of the address (Or by using `/plan m raw <player>` to get direct link.

After the page is loaded in the browser, admin can use `Save As..` in browser and save the json to be sent to user.
