### ISSUE TITLE
ipaddresses in random order

### ISSUE THREAD

**Issue by Grand-Trizmo** [Rsl1122/Plan-PlayerAnalytics#624]
ipaddresses in/player/playername show in a random order that i cant seem to figuer our, aswell as sometimes dont censor

![Ordering?](https://i.triz.moe/1530226017.png)

**Comment by Rsl1122** [comment]
It seems like the ip transfer process has not properly completed.
I'll make it run again in next version..

For the order I think it is completely random order at the moment, but can be enhanced.
