### ISSUE TITLE
MySql 8 - caching_sha2_password

### ISSUE THREAD

**Issue by 1stian** [Rsl1122/Plan-PlayerAnalytics#625]
Hello, this plugin worked great for SQlite and so on. But when I changed to use MySql. I'm running MySql8 with "strong password". But then this plugin won't load anymore because of "caching_sha2_password" Any update on this?

This is showing in my console.

[19:06:38 ERROR]: [Plan] ----------------------------------------
[19:06:38 ERROR]: [Plan] Error: Database init failure: Cannot create PoolableConnectionFactory (Unable to load authentication plugin 'caching_sha2_password'.)
[19:06:38 ERROR]: [Plan] ----------------------------------------
[19:06:38 ERROR]: [Plan] Plugin Failed to Initialize Correctly. If this issue is caused by config settings you can use /plan reload

**Comment by Rsl1122** [comment]
I don't know what I can do to be honest.

Try inverting the ssl value in `Database.MySQL.LaunchOptions` or removing it

Please report back if another issue arises after changing the setting.

I could not get mysql v8 to work and had to replace it with MariaDB. Older spigot versions had more issues with the new MySQL version too (Unknown charset & others I can't remember.) so I don't know if it is in MySQL settings or Java.

**Comment by Argetan** [comment]
I did a quick Google search and found [this](https://stackoverflow.com/a/18799821/8150085). What you can try and do is change the address, set it to the following par example (assuming you are on localhost): `127.0.0.1` or `localhost`.

If that didn't work you can try to set the address to your server's IP.

**Comment by Rsl1122** [comment]
Hello @1stian - Sorry about the delay on the solution.

Another user on Discord had this issue and found a solution from Spigot.

> The newer versions of MySQL default to caching_sha2_password and not the old mysql_native_password that the plugins seem to want to use.
>
> I think you can convert the users but it was easy enough for me to just delete them and then recreate them with the mysql_native_password as the default authentication.
>
> `CREATE USER 'username'@'localhost' IDENTIFIED WITH mysql_native_password BY 'pa$$word';`
>
> ~ [Source (Spigot)](https://www.spigotmc.org/threads/mysql-errors-unable-to-load-authentication-plugin-caching_sha2_password.304616/#post-2909853)

Special thanks to falceso for finding the solution.
