### ISSUE TITLE
Suggestion - Per group statistics

### ISSUE THREAD

**Issue by Argetan** [Rsl1122/Plan-PlayerAnalytics#639]
**Suggestion:**

Make it possible to select a user group (provided by plugins such as LuckPerms or PEX par example) and see the statistics for that specific group.

See the image below for what we talked about.
![screen shot 2018-07-19 at 13 59 11](https://user-images.githubusercontent.com/19390615/42941123-05231942-8b5c-11e8-8bd5-8e6140730fe1.png)

**Comment by BrainStone** [comment]
In addition things like prefix and suffix and player group(s) (either all or just the primary group) would be cool information to display.

**Comment by Rsl1122** [comment]
Some form of group statistics has been incorporated into upcoming DataExtension API. #638
