### ISSUE TITLE
World playtime whitelist

### ISSUE THREAD

**Issue by Frerduro** [Rsl1122/Plan-PlayerAnalytics#645]
Add a small option to whitelist the worlds it keeps track of since this can happen after just half a day if you have temporary worlds
![worldcapture](https://user-images.githubusercontent.com/35627247/42983328-f6c813e0-8b9a-11e8-8bed-9a59f77dd18b.PNG)

**Comment by Rsl1122** [comment]
You can use World Alias settings to group the temporary worlds as a single world

Eg
DXL_Game0: DXL
DXL_Game1: DXL
