### ISSUE TITLE
System not getting online/offline status correctly

### ISSUE THREAD

**Issue by DeCarvalho83** [Rsl1122/Plan-PlayerAnalytics#646]
The system is running on a bungee network and apparently its well configured.
The current issue is about the system not getting the players online when they are online.
Even after some minutes, i can say for sure, even after 30 minutes online the system still showing the server with 0 players online.
Changing servers doesnt affect it, the system still not showing players online nor that it had a player online once.

I used the chat to send messaged to try make the system recognize a player but nothing changed.

The system only updated the info only after the player leaving the server.
After reconnecting the player is shown as online.
Even after leaving the player still shown as online.
20 minutes and the player still shown as online.
Even the server overview still showing that theres a player online, when theres none.

Reconnecting the player makes the server shows him as offline for some minutes and then it update the status to online, also the player status.

No status were updated while the player was online executing actions..
The server, if im not wrong, is configured to update within 15 minutes, but nothing was updated.

No console errors to be shown

**Basic Bukkit Servers Configuration**
https://hastebin.com/ayaxarerod.php

**Bungee Configuration**
https://hastebin.com/ducogogole.php

>planbungee con
03:10:40 [INFO] CONSOLE executed command: /planbungee con
>> 03:10:41 [INFO] http://[suppressed]: HTTP : External : To:Fail : From:Fail
> 03:10:41 [INFO] Fail reason: Older Plan version on receiving server
> 03:10:41 [INFO] http://[suppressed]: HTTP : External : To:Fail : From:Fail
> 03:10:41 [INFO] Fail reason: Older Plan version on receiving server

>plan m con
> [03:11:06 INFO]: http://[suppressed]: HTTP : External : To:OK : From:OK
> [03:11:06 INFO]: http://[suppressed]: HTTP : External : To:OK : From:OK

/Debug info with suppressed information
https://hastebin.com/tayuyuxima.makefile

**Comment by Rsl1122** [comment]
There seems to be something related to server change event causes Bungee to lose track of player online status
