### ISSUE TITLE
Network Page Hang

### ISSUE THREAD

**Issue by Rsl1122** [Rsl1122/Plan-PlayerAnalytics#648]
Brinza reload:
https://pastebin.com/FbHGc5dn

Deadlock:
https://pastebin.com/7c4gdui0

Reload exception:
https://pastebin.com/qHYJ4pYv

Reload exceptions:
https://hastebin.com/zopowuvusu.cs

Debug page could not be accessed so errors could not be fetched

**Comment by Rsl1122** [comment]
Though nut to crack since there is no exception of MySQL failing, but all of the exceptions mention that DataSource is closed

**Comment by Rsl1122** [comment]
More logs - not fixed

https://pastebin.com/WG5zZdhy

**Comment by lucas2107** [comment]
Got the same problem since Plan 4.4.0

**Comment by Rsl1122** [comment]
DEV3 errors reported on Discord
https://pastebin.com/eVemNywB

**Comment by Rsl1122** [comment]
Fixed in 4.4.2-b1.2
