### ISSUE TITLE
Suggestion: Log Feature

### ISSUE THREAD

**Issue by JSingDreams** [Rsl1122/Plan-PlayerAnalytics#657]
I would like chat logs and command logs. Basically, see what is being said in chat and the commands being used by which players.

Could this also support ShopGUIPlus? Like, have a log showing who is buying/selling what.

I do have other plugins, too that would be nice to have logged. I don't want to trouble you too much though. If possible, could I explain more on Discord of which plugins I'd like hooked? I'm more active on there than on GitHub.

Discord ID: JSingDreams#6458

**Comment by DeCarvalho83** [comment]
@JSingDreams 
for suggestion you must post here
https://github.com/Rsl1122/Plan-PlayerAnalytics/issues/583

It says it needs at least the API Link or Source Code if it has also the spigot link..
