### ISSUE TITLE
ShopGUI+

### ISSUE THREAD

**Issue by JSingDreams** [Rsl1122/Plan-PlayerAnalytics#658]
I would like chat logs and command logs. Basically, see what is being said in chat and the commands being used by which players.

Could this also support ShopGUIPlus? Like, have a log showing who is buying/selling what.

Spigot Page: https://www.spigotmc.org/resources/shopgui-admin-gui-shop-plugin.6515/
API Link: https://gist.github.com/brcDev/15f7b9587dca52442904d331a026a8c8

**Comment by DeCarvalho83** [comment]
i think you got me wrong.. you should use that post that i marked to ask for shopgui integration in comment..
Wasnt needed to create a new issue report.. I think you didnt read the #583 right?
The idea is to leave open your last issue and just comment in there #583 the spigot link and the API/SOURCE CODE
But lets hope for the best :) :*
The Dev is a friendly one :)

**Comment by Rsl1122** [comment]
Please use separate issues for different suggestions in the future. 

As DeCarvalho said, please comment spigot and source code/Api links to issue #583 for ShopGUI+

----

#### Why chat logs will not be a thing in Plan

I feel like chat logs cross the boundary to "big brother sees all"-type of a plugin, and I don't want to go there. It will lead to players (people) not liking what Plan provides about them (Currently mostly playtime related things).

If you're adamant on having chat logs in Plan you can code a plugin that adds these logs as PluginData (API tutorial in the wiki)

**Comment by Rsl1122** [comment]
ShopGUI+ support resolved in the above issue - No support, reason:
Plugin has no way to access data easily
