### ISSUE TITLE
Plan causing a decent amount of lag spikes

### ISSUE THREAD

**Issue by blazex224** [Rsl1122/Plan-PlayerAnalytics#659]
Hello,
I'm loving using this plugin, it is really comprehensive with it's server analytics, but the one problem is that it seems to be causing a good amount of lag spikes to my server. Perhaps I am doing something wrong with it, but I thought it'd be good to let you know. I am using [React](https://www.spigotmc.org/resources/react-smart-server-performance.21057/) to find this information.

![1](https://i.imgur.com/8DE5dne.png)

Thanks for the plugin!

*Edit by Rsl: made image appear in issue*

**Comment by Rsl1122** [comment]
Please provide further information to debug this issue further:

- Server (Bungee/Paper/Spigot/Sponge)
- Plan Version
- How many servers are on the network if it is a network
- Analysis Refresh period in the config

Thanks!

**Comment by blazex224** [comment]
Server - Spigot
Plan Version - 4.4.1
One server, not a network
AnalysisRefreshPeriod: 60

Thanks

**Comment by Rsl1122** [comment]
Could you run a timings report on the server (1 hour to 1 day in length) so that we know what is causing the lag spikes?

Cheers! :)

**Comment by Rsl1122** [comment]
Looks like it's something related to the PlayerJoinEvent - How many players do you have registered?

Peak time timings might be more useful if that's the case.
These timings say that total time spent in Plan code on server thread was 0.3s / 360s (0.1%) and 8s / 1300s (0.6%) with averages below 10 ms.

Does React have some sort of log that says in more detail what in the plugin caused it?

Thanks.

**Comment by blazex224** [comment]
https://timings.spigotmc.org/?url=xeyocerava

Thanks

**Comment by Rsl1122** [comment]
Definitely would say it's the PlayerOnlineListener - I'll have to do some benchmarks on it.

**Comment by Rsl1122** [comment]
I made some improvements, but I don't know their exact impact on the lag spikes.
If it appears again I'll reopen this issue.
