### ISSUE TITLE
Memory Access Violation [Exit Code 139]

### ISSUE THREAD

**Issue by Maciner** [Rsl1122/Plan-PlayerAnalytics#665]
The server I manage crashes a few seconds upon startup. Here's some vital information.
OS: Ubuntu 16.04.4
Java Version: 8_171
Minecraft: Pixelmon Reforged 6.3.2
Partial Crash Report: https://pastebin.com/FAqXd0Lw
Full Error: https://pastebin.com/M1xgdruY
We're running Pterodactyl Panel, latest version and all that. Additionally, I cannot access the `ip_address:8804/debug` before the server crashes. This does not happen at random either, the server starts up, stays up for 10-20 seconds or so, and then proceeds to crash with exit code 139. Once the plugin is removed, the problem goes away.

**Comment by Shybella** [comment]
This is crashing my JVM on server restarts too. 

I'll move over to MySQL and see what happens, I am not using Pterodactyl.

**Comment by Rsl1122** [comment]
Could you send the crash dump @Shybella, to see if it's the same error or related to sqlite, sqlite tends to be very unstable when reloading (Plan test suite crashes 1/4 of the time)
