### ISSUE TITLE
Make /server the default page

### ISSUE THREAD

**Issue by Miclebrick** [Rsl1122/Plan-PlayerAnalytics#668]
Instead of a 404 page, it'd probably be more logical for /server to be the default page on bungee and the display for an individual server on an individual server's page

**Comment by DeCarvalho83** [comment]
This happens when we dont use https..
but would be good to have this or maybe give the list of servers in the left panel so we could click to select..

I gave this suggestion i dont remember where (i mean mine one)

**Comment by Miclebrick** [comment]
Did not know that enabling HTTPS fixed that. Thanks for the tip
