### ISSUE TITLE
Use SSL on nginx instead of on plan

### ISSUE THREAD

**Issue by Miclebrick** [Rsl1122/Plan-PlayerAnalytics#669]
It'd be nice to be able to use nginx for SSL instead of directly on Plan itself so it's easier to set up. Maybe a way to let Plan know that it's behind a secure proxy?

**Comment by Rsl1122** [comment]
You can set up https on nginx and put the self signed certificate on Plan (Tutorial in the wiki article)

**Comment by Miclebrick** [comment]
That works I guess. Usually there is just an option to assume it's ssl

**Comment by Miclebrick** [comment]
maybe make it default config to use that cert..

**Comment by Rsl1122** [comment]
I'll make it so that if Certificate file name is 'proxy' it'll ignore whole thing and assume it's behind https proxy
