### ISSUE TITLE
NOT NULL constraint failed: plan_nicknames.user_id

### ISSUE THREAD

**Issue by Akadyson** [Rsl1122/Plan-PlayerAnalytics#678]
New "players" not being added, most likely due to a kingdom plugin which lists the usernames as their original minecraft username and another instance of their name.

Mc version: 1.12.2 (spigot)

http://145.239.11.117:8804/server
http://145.239.11.117:8804/debug

Running PHPmyadmin on a local mysql instance on our dedicated box.

The names are looking like this on the DB side due to a kingdom plugin we are running., not sure if this would cause an issue however:

1
Vigridr
1
1533813637461
1
§7[§9Bele§8gost§7] §fVigridr§r
1
1533813695604
2
xCheymeermin
1
1533813832400
2
§7[§4Mis§8uto§7]§f xCheymeermin§r
1
1533813841166

While there are 25 players online currently I'm not seeing this reflected on the DB side, however not sure how this process works in the background, the SQL error I'm constantly see being returned is the following:

com.djrapitops.plan.api.exceptions.database.DBOpException: SQL Failed: INSERT INTO plan_nicknames (user_id, server_id, nickname, last_used) VALUES ((SELECT plan_users.id FROM plan_users WHERE (uuid=?) LIMIT 1), (SELECT plan_servers.id FROM plan_servers WHERE (plan_servers.uuid=?) LIMIT 1), ?, ?); [SQLITE_CONSTRAINT_NOTNULL]  A NOT NULL constraint failed (NOT NULL constraint failed: plan_nicknames.user_id)

Everything else seems to be functional in Plan except for the sessions which are not reflecting the amount of online players ( could be a DB thing that they're not registered yet) and the playerlist is missing online people (same as above)

**Comment by Rsl1122** [comment]
From the errors, it appears that someone got on the server and their UUID was not registered properly - Unfortunately there doesn't seem to be an error that indicates why they were not registered.

Are you using offline mode CraftBukkit?

Could you check your server log for any uncaught exceptions?

**Comment by Akadyson** [comment]
Thanks for the quick reply on this one :) 

Running this server via Multicraft with out of the box settings for the minecraft jar itself, would suppose that this isn't the offline variant.

What kind of exceptions should I be looking for, by the looks of it the only exceptions that I Can find in the server logs are related to Plugindatasource causing the exception:

[13:00:40] [Server thread/WARN]: [Plan] com.djrapitops.plan.data.plugin.HookHandler Caught: java.lang.IllegalStateException: Absolute Path was null (Not defined)
[13:00:40] [Server thread/WARN]: [Plan] Exception can be viewed at http://0.0.0.0:8804/debug
[13:00:40] [Server thread/ERROR]: [Plan] Attempting to register PluginDataSource caused an exception.

We have an automated restart in about an hour, will troubleshoot some more when im done at work.

**Comment by Rsl1122** [comment]
Exceptions related to either PlayerOnlineListener or RegisterProcessor might get some answers, but they are usually caught by Plan - Which would make them show up on the the debug page.
There are none to be found.

It's probably some processing order issue - I'll see if there is a solution for it (Possibly run the registration on a task instead of the processing system)

If you manage to figure out how to reproduce the issue, that would help a ton - Not necessary though.

**Comment by Akadyson** [comment]
Yeah seems to be all straightened out by itself now, sessions are coming up as expected and everything is  being written to the DB including mob kills and pvp kills now.

Probably a timing issue or something, appreciate the quick updates however!

**Comment by Rsl1122** [comment]
Please comment if it occurs again
