### ISSUE TITLE
Thousands of lines of Plan tasks in thread dump

### ISSUE THREAD

**Issue by Miclebrick** [Rsl1122/Plan-PlayerAnalytics#680]
My server's been having crazy issues as of a few days ago.. which is around when I got Plan again I think. Looking at these logs there are **thousands of lines of Plan tasks!**

https://gist.github.com/Miclebrick/3194d85ed992349f2e61768bd298e70b

**Comment by Rsl1122** [comment]
Well, damn. Thanks for reporting this.

Cause of #671

**Comment by Rsl1122** [comment]
Cause of #648

**Comment by Rsl1122** [comment]
Could you test this version for the issue - I could not get the tasks to appear in thread dumps (done with `jstack`) on 4.4.2 so I can not confirm that it's fixed. If you're routing through nginx, that might be part of the reason why I can't reproduce it.

https://github.com/Rsl1122/Plan-PlayerAnalytics/releases/tag/4.4.3-DEV1

**Comment by Miclebrick** [comment]
yeah I'm routing through nginx. I'll test it soon
