### ISSUE TITLE
ASkyBlock Challenges support

### ISSUE THREAD

**Issue by MajorSkillage** [Rsl1122/Plan-PlayerAnalytics#686]
I think it'd be epic if you gave ASkyBlock support so we can see who has finished what challenges, which challenges are the most popular, how many times they've been finished and any other appropriate data. I think it'd help us learn how to enhance our player's gameplay quality.

**Comment by Rsl1122** [comment]
Was not aware of challenges, will investigate what I can do.

**Comment by MajorSkillage** [comment]
https://github.com/tastybento/askyblock/blob/master/src/com/wasteofplastic/askyblock/commands/Challenges.java#L1667
This class has some really good insights into how challenges work on askyblock. The only fault in this case is it assumes the player is online.

**Comment by Rsl1122** [comment]
I can't really read the linked class for implementation details (So much spaghetti, nesting levels of 9)

----

I think I'll just go with `getChallengeStatus` in [ASkyBlockAPI](https://github.com/tastybento/askyblock/blob/master/src/com/wasteofplastic/askyblock/ASkyBlockAPI.java#L72)

Drawback to this method is that I can not get challenge completion for all players to be displayed on the server page (I think the method makes a database call somewhere, so fetching for all UUIDs would take too long a time.)

**Comment by MajorSkillage** [comment]
Could you see how data is stored in databases and if the player is using SQL, query the data yourself?

**Comment by Poslovitch** [comment]
There is no SQL support in ASkyBlock.
That's right, data is only queried when requested - caching all the players data could just lead to a huge load of memory.

**Comment by MajorSkillage** [comment]
@Poslovitch I don't mind adding these in myself, I'd just like to know how I should go about making a hook for these challenges. I thought of a way already but I'd be limited on what tiers I can add it to and false completion messages would be listed (which I was thinking of removing anyway, they're quite annoying).

**Comment by Poslovitch** [comment]
@MajorSkillage Editing ASkyBlock's code base is a pain, but if you want to have a try : everything is handled in Challenges class. We're not adding ne features to ASB, so we won't be making that event cancellable. But that discussion is not related to Plan at all.

**Comment by VankkaGithub** [comment]
Shouldn't this be in #583

**Comment by Rsl1122** [comment]
@VankkaGithub ASkyBlock is already supported, but challenges are not, hence Enhancement tag
