### ISSUE TITLE
JSON player data

### ISSUE THREAD

**Issue by FrozenBeard** [Rsl1122/Plan-PlayerAnalytics#700]
This is going to be a very specific feature request.
Im not sure how you send the data to the HTML builder to create player html files, but would it be possible to create player json files as an addition too? Then we could build third party applications and websites to pull the data from plan without having to have a database connection. 

my very specific reasoning; I am re-building my website from scratch and at some point im going to create my own stats web UI to pull data from Statz plugin (Once I convert it from Stats3) and it would be fantastic to pull some of your data and display it on my website, issue being that my game server and web server are on different hosts.

I would LOVE to be able to show the player punchcards on my player page too though, so im not sure if its the best method to get the data over.

Then I could just pull the JSON with PHP to parse the data that I want to display for each user from the player page im creating, which will be public.

**Comment by Rsl1122** [comment]
Currently Plan Webserver serves raw data json at /player/PlayerName/raw (fast) and /server/ServerName/raw (very slow, lots of data, 4k players ~150Mb)

**Comment by Rsl1122** [comment]
The json is currently not part of the exported files, but it would be possible to add (At least the player json files) - I don't know how much space they would take to be honest.

Best bet might be getting directly from the database if you don't want to turn the Plan webserver on.

**Comment by Rsl1122** [comment]
The graph data and some other things may become available as json in the future when looking into #506, but there are a lot of things ahead in the todo list before that one.

**Comment by Rsl1122** [comment]
While making enhancements to configuration, JSON export was added.
This will be available in 4.6.0

**Comment by FrozenBeard** [comment]
Holy shit! I forgot about this, what amazing timing I just started on my JavaScript learning! So the front end will just be that! Thank you n
