### ISSUE TITLE
The `/players` list only updates when reloading

### ISSUE THREAD

**Issue by BrainStone** [Rsl1122/Plan-PlayerAnalytics#707]
### Describe the bug

The list of network players under `/players` only updates when reloading the plugin.

### Server information

**Plan Version:** 4.4.5
**Server:** BungeeCord git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178 git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178
**Database:** MySQL

**Operating SubSystem:** Linux (amd64) version 4.9.0-6-amd64
**Java Version:** 1.8.0_171, Oracle Corporation
**Java VM Version:** OpenJDK 64-Bit Server VM version 25.171-b11, Oracle Corporation
**Java VM Flags:** [-Xms921M, -Xmx1843M, -XX:+UseG1GC, -XX:+UnlockExperimentalVMOptions, -XX:MaxGCPauseMillis=100, -XX:+DisableExplicitGC, -XX:TargetSurvivorRatio=90, -XX:G1NeuSizePercent=50, -XX:G1MaxNeuSizePercent=80, -XX:InitiatingHeapOccupancyPercent=10, -XX:G1MixedGCLiveThresholdPercent=50, -XX:+AggressiveOpts, -XX:+AlwaysPreTouch]

**Comment by Rsl1122** [comment]
I think it might be implemented with the addition of the cache already, but I haven't tested.
It's going to have a 5 minute delay anyway since that's the cache invalidation timer.

**Comment by BrainStone** [comment]
Would it be possible to make that time configurable?

**Comment by Rsl1122** [comment]
Not until it's possible to make it non static

**Comment by BrainStone** [comment]
The initialization should be possible to be non-static
