### ISSUE TITLE
Add back links and add link back to main page

### ISSUE THREAD

**Issue by BrainStone** [Rsl1122/Plan-PlayerAnalytics#708]
I think the navigation is a bit awkward in the sense that links that get you back are missing. For example when you start on the main page, you can go to a player page in a pretty logical fashion, but you can't go back! I know it opens a new tab, but a base pricinple in web design is that you need to be able to go back where you came from in one click and to the main page in one click.

**Comment by Rsl1122** [comment]
I can try this at some point, last time I tried it broke mobile navigation and was thus postponed.
