### ISSUE TITLE
Allow punchcard to use 24h time too

### ISSUE THREAD

**Issue by BrainStone** [Rsl1122/Plan-PlayerAnalytics#713]
I'd love to have 24h time on the punchcard as an option, as the am/pm thing is mostly specific to the English language and most other languages use 24h time.

**Comment by Rsl1122** [comment]
You can change the formatting method in punchcard.js for changing this before an update.

**Comment by BrainStone** [comment]
Is there a way to do that without modifying the js in the jar?  
Sorry if there’s documentation on that, I can’t really look for it because I’m on my phone.

**Comment by Rsl1122** [comment]
https://github.com/Rsl1122/Plan-PlayerAnalytics/wiki/Html-Customization

There is a link to the wiki in the README on Repo root

**Comment by BrainStone** [comment]
Perfect. Thanks.

**Comment by Rsl1122** [comment]
Following change uses 24 hour clock

```
            dateTimeLabelFormats: {
                hour: '%H:00',
                day: '%H:00'
            },
```
See http://www.php.net/manual/en/function.strftime.php for format reference
