### ISSUE TITLE
com.djrapitops.plan.api.exceptions.database.DBOpException: SQL Failed: INSERT INTO plan_tps

### ISSUE THREAD

**Issue by DeCarvalho83** [Rsl1122/Plan-PlayerAnalytics#719]
https://pastebin.com/wWL8xwL0

### Server Information
**Plan Version:** 4.4.5
**Server:** BungeeCord git:BungeeCord-Bootstrap:1.13-SNAPSHOT:4c47549:1349 git:BungeeCord-Bootstrap:1.13-SNAPSHOT:4c47549:1349
**Database:** MySQL

**Operating SubSystem:** Linux (amd64) version 4.13.0-46-generic
**Java Version:** 1.8.0_171, Oracle Corporation
**Java VM Version:** OpenJDK 64-Bit Server VM version 25.171-b11, Oracle Corporation
**Java VM Flags:** [-Xms128M, -Xmx1024M]

### Connection Log:

Server Address | Request Type | Response | Sent
-- | -- | -- | --
https://mcserver.dkogameplays.net:8089 | Out: GenerateInspectPluginsTabRequest | 200 | Thursday, 06:02:39
https://mcserver.dkogameplays.net:8089 | Out: GenerateNetworkPageContentRequest | 200 | 28 Aug 2018, 02:28:31
172.18.0.1 | In:  /info/generatenetworkpagecontentrequest | 200 | 28 Aug 2018, 02:28:31
172.18.0.1 | In:  /info/cachenetworkpagecontentrequest | 200 | Today, 20:41:07
172.18.0.1 | In:  /info/generateinspectpluginstabrequest | 200 | Thursday, 06:02:39
172.18.0.1 | In:  /info/cacheanalysispagerequest | 200 | Today, 20:41:07
http://mcserver.dkogameplays.net:8089 | Out: GenerateInspectPluginsTabRequest | -1 | Thursday, 06:02:39
http://mcserver.dkogameplays.net:8089 | Out: GenerateNetworkPageContentRequest | -1 | 28 Aug 2018, 02:28:31

### Benchmarks
```
210 ms    Init Database
4 ms      Inspect Parse, Fetch
2 ms      Register Listeners
56 ms     WebServer Initialization
```

**Comment by Rsl1122** [comment]
I'm going to need a bit more context for this issue - When did this exception occur?

Does the plugin enable just fine?
Was MySQL under high load?
Does MySQL have enough connections (Plan uses 1-8 per instance)

**Comment by Rsl1122** [comment]
More information required. Closing issue as no progress has been made.
Comment to reopen for discussion.
