### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by Faicu** [Rsl1122/Plan-PlayerAnalytics#72]
[Apr 02 04:17:44] main.java.com.djrapitops.plan.database.databases.SQLiteDB Caught java.lang.NullPointerException
[Apr 02 04:17:44]   main.java.com.djrapitops.plan.database.databases.SQLDB.saveGMTimes(SQLDB.java:1198)
[Apr 02 04:17:44]   main.java.com.djrapitops.plan.database.databases.SQLDB.saveMultipleUserData(SQLDB.java:859)
[Apr 02 04:17:44]   main.java.com.djrapitops.plan.data.cache.DataCacheHandler.saveCachedUserData(DataCacheHandler.java:170)
[Apr 02 04:17:44]   main.java.com.djrapitops.plan.data.cache.DataCacheHandler$1.run(DataCacheHandler.java:107)
[Apr 02 04:17:44]   org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[Apr 02 04:17:44]   org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[Apr 02 04:17:44]   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[Apr 02 04:17:44]   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[Apr 02 04:17:44]   java.lang.Thread.run(Thread.java:745)

This happen random on console and 2nd problem is: when I click a player from Online Players, it gives me 404 data not found, /plan inspect <his name> gives me no player found... but it playerd on server, al least 1 day

**Comment by Nikolay0054** [comment]
same about '404 data not found"

**Comment by Faicu** [comment]
Now: "404 - Player doesn't exist" on web and on plan inspect...
