### ISSUE TITLE
When removing Plan for a while, then getting it back, it considers a month of absence as instant

### ISSUE THREAD

**Issue by Miclebrick** [Rsl1122/Plan-PlayerAnalytics#720]
### Describe the bug
I removed Plan a month ago, and got it again now. On the graphs, September 3rd comes a pixel after August 9th.

### Server Information
**Plan Version:** 4.4.5
**Server:** BungeeCord git:Waterfall-Bootstrap:1.13-SNAPSHOT:9dfa9ad:213 git:Waterfall-Bootstrap:1.13-SNAPSHOT:9dfa9ad:213
**Database:** MySQL

**Operating SubSystem:** Linux (amd64) version 4.15.0-23-generic
**Java Version:** 1.8.0_171, Oracle Corporation
**Java VM Version:** OpenJDK 64-Bit Server VM version 25.171-b11, Oracle Corporation
**Java VM Flags:** [-Dnet.starlegacy.server=proxy, -Dcom.sun.management.jmxremote.ssl=false, -Dcom.sun.management.jmxremote.authenticate=false, -Dcom.sun.management.jmxremote.port=14300, -Dcom.sun.management.jmxremote.rmi.port=14310, -Djava.rmi.server.hostname=localhost, -Dcom.sun.management.jmxremote.local.only=false, -Dfile.encoding=UTF-8, -XX:+UseG1GC, -XX:+ParallelRefProcEnabled, -XX:+UnlockExperimentalVMOptions, -XX:MaxGCPauseMillis=100, -XX:+DisableExplicitGC, -XX:G1HeapRegionSize=8M, -XX:TargetSurvivorRatio=90, -XX:+AggressiveOpts, -XX:-OmitStackTraceInFastThrow, -XX:HeapDumpPath=crash-reports/, -XX:+HeapDumpOnOutOfMemoryError, -XX:+AlwaysPreTouch, -XX:+UseLargePagesInMetaspace, -Dio.netty.recycler.maxCapacity.default=20000, -Dio.netty.recycler.maxCapacity=20000, -XX:G1NewSizePercent=30, -XX:G1MaxNewSizePercent=60, -XX:InitiatingHeapOccupancyPercent=30, -DIReallyKnowWhatIAmDoingISwear=1, -Xms1024M, -Xmx1024M]
### Connection Log:

Server Address | Request Type | Response | Sent
-- | -- | -- | --
https://127.0.0.1:9002 | Out: GenerateInspectPluginsTabRequest | 200 | Today, 13:59:35
https://127.0.0.1:9002 | Out: GenerateNetworkPageContentRequest | -1 | Today, 13:54:42
https://127.0.0.1:9001 | Out: GenerateInspectPluginsTabRequest | 200 | Today, 13:59:35
https://127.0.0.1:9001 | Out: GenerateNetworkPageContentRequest | -1 | Today, 13:54:42
127.0.0.1 | In:  /info/cacheinspectpluginstabrequest | 200 | Today, 13:59:35
127.0.0.1 | In:  /info/cachenetworkpagecontentrequest | 200 | Today, 13:59:30
127.0.0.1 | In:  /info/cacheanalysispagerequest | 200 | Today, 13:57:20
### Servers:

Server Name | Address | UUID 
-- | -- | --
Survival | https://127.0.0.1:9001 | 89faca4f-2c3a-3902-a9d4-bf85336fcbd1
Creative | https://127.0.0.1:9002 | 64051680-6255-3b25-8e5a-2c9389dc5fed
### Benchmarks
```
296 ms    Init Database
1 ms      Inspect Parse, Fetch
0 ms      Register Listeners
21 ms     WebServer Initialization
```

### Exceptions & Other Logs
No error logs that I'm aware of

### Additional information

**Frequency of occurrence**: n/a ?

**Other:** dinosaurs are laser masters

**Comment by Rsl1122** [comment]
Set Customization Display GapsInGraphs to true in the config

**Comment by Miclebrick** [comment]
Shouldn't that be on by default?

**Comment by Rsl1122** [comment]
Yes.

The reason it is false is because when it was first implemented it was not optimized, and caused large increase in the "Please wait" loading time. It was never changed to true after optimizations.
