### ISSUE TITLE
Peak has no data

### ISSUE THREAD

**Issue by BrainStone** [Rsl1122/Plan-PlayerAnalytics#726]
### Describe the bug

The player peak doesn't seem to be calculated anymore. During the first few days that worked fine but after around 5 days it just keeps displaying "No data" and a dash for the value.

See screenshot:
![screenshot](https://screenshotscdn.firefoxusercontent.com/images/2d5ce457-fa95-41e3-8aa2-29a99ff54268.png)

### Server information

**Plan Version:** 4.4.5
**Server:** BungeeCord git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178 git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178
**Database:** MySQL

**Operating SubSystem:** Linux (amd64) version 4.9.0-8-amd64
**Java Version:** 1.8.0_171, Oracle Corporation
**Java VM Version:** OpenJDK 64-Bit Server VM version 25.171-b11, Oracle Corporation
**Java VM Flags:** [-Xms921M, -Xmx1843M, -XX:+UseG1GC, -XX:+UnlockExperimentalVMOptions, -XX:MaxGCPauseMillis=100, -XX:+DisableExplicitGC, -XX:TargetSurvivorRatio=90, -XX:G1NeuSizePercent=50, -XX:G1MaxNeuSizePercent=80, -XX:InitiatingHeapOccupancyPercent=10, -XX:G1MixedGCLiveThresholdPercent=50, -XX:+AggressiveOpts, -XX:+AlwaysPreTouch]

### Additional information
**Frequency of occurrence**: Permanent. Once it happened it never goes away

**Comment by Rsl1122** [comment]
This bug is caused by the sub select statement in the SQL not taking server UUID into account.

This means that the peak is not available if there is some other server with a higher all time peak (even if that peak was the same server some time ago)
