### ISSUE TITLE
Webserver not reachable from inside Docker container

### ISSUE THREAD

**Issue by TheFox1312** [Rsl1122/Plan-PlayerAnalytics#73]
**Plan Version: latest** 
**Server Version: Spigot 1.11.2**
**Database Type: sqlite** 

**Description:**
I cant access to the Website because im running my Server in a docker container and it has another ip than my server.

**Proposed Solution:**
Add an Option to manually set the IP. Thx :)

**Comment by Rsl1122** [comment]
Alright I'll see what I can do.

**Comment by Rsl1122** [comment]
I'll leave this open until I get confirmation after the update is live (still bugs to fix).

**Comment by Rsl1122** [comment]
Assumed fixed, comment to reopen.
