### ISSUE TITLE
More words/phrases to translate

### ISSUE THREAD

**Issue by Sprungente** [Rsl1122/Plan-PlayerAnalytics#734]
### Is your feature request related to a problem? Please describe.
I saw that Days not translatable and the serverhealthpage aren't translatable too. 
times are not tranlatable (like yesterday, tomorrow)

### Describe the solution you'd like
Add new/more words and phrases. If translat

### Describe alternatives you've considered
i don't have any idea^^

### Additional context
I wanna help to translate :)

**Comment by Rsl1122** [comment]
This has been planned, I just haven't had the time. Thanks for opening the issue, it'll help remembering to do it at some point.

**Comment by Rsl1122** [comment]
Added today, yesteday and health info to the locale.

Use [Development branch](https://github.com/Rsl1122/Plan-PlayerAnalytics/tree/development/Plan/src/main/resources/locale) if you wish to translate before release
