### ISSUE TITLE
Symbols of another language in the nickname.

### ISSUE THREAD

**Issue by yaroslav4167** [Rsl1122/Plan-PlayerAnalytics#735]
### Describe the bug

On my server you can use nicknames with special characters. But I can not view information about them.
For example: myproject.ru:8805/player/Привет - 404 (Although such a player exists and information about it in the /server section is.)

### Server information

Plan-version: 4.4.6
Sponge-Forge: 1.12.2-2705-7.1.0-BETA-3361

**Comment by Rsl1122** [comment]
Sine the URL can contain only ASCII during transmission, other characters are encoded - Plan doesn't decode the URL, which leads to a 404.

Thanks for bringing this up.
