### ISSUE TITLE
HTML icon not recognized/displayed

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#752]
Server:
```
CentOS Linux release 7.5.1804
HTTPD up-to-date
Spigot 1.13.1 latest
Plan 4.4.7-beta1 (and previous)
```

Client:
```
MacOS Mojave latest
Safari 12.0 (14606.1.36.1.9) up-to-date
```

Icon specified in customized HTML files
```
<head>
...
    <link rel="icon" type="image/png" href="http://URL_MASKED/images/BlackDog-32.png" />
...
</head>
```
is not displayed in tabs. (Icons are displayed in tabs for other sites.)

**Comment by Rsl1122** [comment]
Apparently you need 10 different favicon icons in correct sizes and formats to display the favicon correctly on all browsers

Here is a page that generates them for you
http://faviconit.com

Alternative is to convert the favicon to a Base64 string
https://stackoverflow.com/a/34699173

**Comment by SlimeDog** [comment]
True, but the icon in question is displayed correctly on other tabs. I copied the <link...> from my other pages. However, I may go the Base64 route. :(

I will update here as I test.
