### ISSUE TITLE
Server stops responding 

### ISSUE THREAD

**Issue by ipozow** [Rsl1122/Plan-PlayerAnalytics#753]
### Describe the bug

Today I updated my server from 1.12.2, and since then sometimes the server crashes. 

### Server information

Spigot version: git-Spigot-f6a273b-e3d7b2f (MC: 1.13.1)
Plan 4.4.7

### Exceptions & Other Logs

last one: https://pastebin.com/BASaLv1j
https://pastebin.com/EepyYy5f

### Additional information

**Frequency of occurrence**: <>
2 times a day
**Other:**

**Comment by ipozow** [comment]
well, seems like it's not related to Plan. I posted here because I saw in some part of the log something related to the plugin

**Comment by Rsl1122** [comment]
Alright. What plugin was it? :)
