### ISSUE TITLE
AAC Stacktrace

### ISSUE THREAD

**Issue by Zenya4** [Rsl1122/Plan-PlayerAnalytics#759]
All in the pastebin. It gives this error on server startup.

https://pastebin.com/1gmn1EA3

Doesn't seem to negatively affect anything, but looks rather spammy and something internal may be broken

**Comment by Zenya4** [comment]
Using the latest version of AAC (3.5.0-b1) and Plan

**Comment by Rsl1122** [comment]
Further attempts resulting on the exception can be disabled from Plan config Plugins.AAC.Enabled: false
