### ISSUE TITLE
Would Dependabot be useful?

### ISSUE THREAD

**Issue by PyvesB** [Rsl1122/Plan-PlayerAnalytics#761]
Hello @Rsl1122,

[Dependabot](https://github.com/dependabot) is a tool that makes sure that you dependencies are kept up-to-date and automatically submits pull requests to your repository if need-be. I have enabled it on [AdvancedAchievements](https://github.com/PyvesB/AdvancedAchievements) this morning and we also heavily rely on it on another repository I help maintain, [shields](https://github.com/badges/shields).

It's free for non-commercial use, easy to enable, configurable and has beta support for Java projects. When the service detects an outdated Maven dependency or plugin, it submits a pull request with the version bump and additional information about the upgrade if available.

What do you think? Would it be something useful to enable for Plan? 😄 

Cheers,

Pyves

**Comment by Rsl1122** [comment]
Dependabot is now enabled on Plan.

It was surprisingly easy to configure! :)

**Comment by PyvesB** [comment]
Glad adding it went smoothly!
