### ISSUE TITLE
Error on shutdown related to MySQL

### ISSUE THREAD

**Issue by Rsl1122** [Rsl1122/Plan-PlayerAnalytics#769]
### Describe the bug

An error was thrown when a server stops

### Server information

Spigot 1.13.2 
MySQL

### Exceptions & Other Logs

https://hastebin.com/remewaqiho.sql

**Comment by Fuzzlemann** [comment]
Testing performed: Sponge does not perform player leave events on shutdown.

![image](https://user-images.githubusercontent.com/16463103/47680985-9b491400-dbc8-11e8-8423-c69fa62fa5b7.png)

**Comment by Rsl1122** [comment]
Thanks. I guess next step is to check if they have an event that fires only on server stop

**Comment by Sprungente** [comment]
https://pastebin.com/iYw3R6P1

it is the same issue?
