### ISSUE TITLE
Expose RESTful(?) API instead of full webpage

### ISSUE THREAD

**Issue by lifehome** [Rsl1122/Plan-PlayerAnalytics#770]
### Describe the solution you'd like

An option of `WebServer` in config.yml, to enable the web server function as a read-only endpoint, providing JSON data for other services to read. This could also lead to possibilities to separate backend and frontend too.

### Describe alternatives you've considered

Direct access to the SQLite database would result in a fight of file lock, as well as desynced data from direct access to MySQL DB.

### Additional context

Possibly better to listen as unix socket instead of TCP port... nginx could've read it in another way :D

**Comment by Rsl1122** [comment]
Related to implementation details of #700 and #506

You have left out the first section of a feature request ("what problem do you have that this solves?") - That section is useful to me when considering the priority of different suggestions, so please comment below on that, thanks :)

**Comment by lifehome** [comment]
Hi, sorry for missed that out. This was proposed to allow data to be extracted easily, and need not to touch the database. This feature can be used in various ways, from feeding data to another analytic engine, to the making of widgets.

**Comment by Rsl1122** [comment]
Well, some sort of JSON requests have been available for a while at `/player/<name>/raw` and `/server/<name>/raw`.

I think that is as close to a REST API there is going to be, as I will likely not have time to implement/maintain this feature.
