### ISSUE TITLE
Error when Creating analysis

### ISSUE THREAD

**Issue by mesl** [Rsl1122/Plan-PlayerAnalytics#784]
I get this error when I wan't to generate an Analysis:

com.djrapitops.plan.api.exceptions.connection.BadRequestException: Bad Request: http://0.0.0.0:8804/info/generateanalysispagerequest | sender=90bdba8a-7f79-3a27-8840-a21d68df5181;&variable;type=GenerateAnalysisPageRequest;&variable;server=23aa6c64-07ce-3b2f-baca-25867d4e9859 | Failed to generate Analysis Page
    com.djrapitops.plan.system.info.connection.ConnectionOut.handleResult(ConnectionOut.java:130)
    com.djrapitops.plan.system.info.connection.ConnectionOut.sendRequest(ConnectionOut.java:108)
    com.djrapitops.plan.system.info.connection.ConnectionSystem.sendInfoRequest(ConnectionSystem.java:87)
    com.djrapitops.plan.system.info.connection.ConnectionSystem.sendInfoRequest(ConnectionSystem.java:79)
    com.djrapitops.plan.system.info.InfoSystem.sendRequest(InfoSystem.java:118)
    com.djrapitops.plan.system.info.InfoSystem.generateAnalysisPage(InfoSystem.java:99)
    com.djrapitops.plan.system.webserver.pages.ServerPageHandler.lambda$refreshNow$3(ServerPageHandler.java:95)
    com.djrapitops.plan.system.processing.Processing.lambda$submitNonCritical$0(Processing.java:70)
    java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    java.lang.Thread.run(Thread.java:748)

**Comment by Rsl1122** [comment]
Ensure that all servers are running the same version

**Comment by Rsl1122** [comment]
More information required. Closing issue as no progress has been made.
