### ISSUE TITLE
Start using Gradle instead of Maven

### ISSUE THREAD

**Issue by Rsl1122** [Rsl1122/Plan-PlayerAnalytics#831]
Currently Maven is used as build system, and builds seem to take a long time (Full build without tests takes 1 minute on my machine)
One way to improve this would be swapping to gradle.

I tested if it would be possible, and it is, but will take quite a lot of effort as some parts of the configuration can not be automatically converted to gradle.

### Required manual work to implement this issue

- Add annotation processor for Dagger to compile the project appropriately
- Add sponge annotation processor to Plan-sponge
- Add velocity annotation processor to Plan-velocity
- Add test jars as testCompile dependencies to the modules
- Add shadow configuration to replace maven shade configuration
- Make sure that projects that depend on Plan with Maven still work

### Pros

- Faster build time
- Gradle tasks integrate better with IntelliJ IDEA than Maven
- Good discovery feature for tasks

### Cons

- Dependency version management is spread to more places
- Issues can pop up from improper configuration definition order (Eg. plugins applied at the end of file)

**Comment by Miclebrick** [comment]
did it partially in https://github.com/Rsl1122/Plan-PlayerAnalytics/pull/833

**Comment by RoboMWM** [comment]
Missing a gradle wrapper tho

**Comment by MicleBrick** [comment]
PR it :3

**Comment by MicleBrick** [comment]
dum ol robo i'll do it
