### ISSUE TITLE
NPE on player login

### ISSUE THREAD

**Issue by stepech** [Rsl1122/Plan-PlayerAnalytics#837]
Hello,
I am using spigot 1.13.2 with Plan v 4.5.2 installed and upon new player login, it throws these errors. I have attached files with code. Thank you. ¨
I am running very latest version of spigot. Can you please fix it or help me with solution for this problem?
[Errors-2018_12_06.txt](https://github.com/Rsl1122/Plan-PlayerAnalytics/files/2660104/Errors-2018_12_06.txt)
[Errors-2018_12_07.txt](https://github.com/Rsl1122/Plan-PlayerAnalytics/files/2660105/Errors-2018_12_07.txt)
[Errors-2018_12_08.txt](https://github.com/Rsl1122/Plan-PlayerAnalytics/files/2660106/Errors-2018_12_08.txt)
[DebugLog-2018_12_09.txt](https://github.com/Rsl1122/Plan-PlayerAnalytics/files/2660107/DebugLog-2018_12_09.txt)
[Errors-2018_12_02.txt](https://github.com/Rsl1122/Plan-PlayerAnalytics/files/2660108/Errors-2018_12_02.txt)
[Errors-2018_12_05.txt](https://github.com/Rsl1122/Plan-PlayerAnalytics/files/2660109/Errors-2018_12_05.txt)

**Comment by Rsl1122** [comment]
Something is giving Processing#submit a null as parameter.

I have a hunch about what is causing it, please try setting `Data.Geolocations` to true in Plan config to see if the errors stop.
