### ISSUE TITLE
Broken menu items go to wrong page

### ISSUE THREAD

**Issue by kalleswe** [Rsl1122/Plan-PlayerAnalytics#839]
Plan 4.5.2

In the webinterface when running on BungeeCord the menu item "Servers" show the Network Health page and the menu item "Network Health" shows the Geolocation page. THe Plugins/Player Data shows a white page.

**Comment by Rsl1122** [comment]
Looks like I forgot to add some sort of "You have no servers connected to BungeeCord" page

**Comment by Rsl1122** [comment]
Fix will be available in 4.6.0
