### ISSUE TITLE
Configuration conversion errors 4.5.2->4.6.0DEV2

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#844]
### Describe the bug
Some configuration values were not converted; left empty.

```
<         Delete_logs_after_days:
<         Dev:

<         AFK_threshold:

<     Theme:

<     HTML_Export_path:
```

SSL certificate values were double-quoted.
```
<         SSL_certificate:
<             Alias: 'DefaultPlanCert'
<             KeyStore_path: "'Cert.keystore'"
<             Key_pass: "'MnD3bU5HpmPXag0e'"
<             Store_pass: "'wDwwf663NLTm73gL'"

```

### Server information
CentOS Linux 7.6.1810 latest patches
Java openjdk version "1.8.0_191" OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
Spigot 1.13.2 latest
Plan 4.6.0-DEV2 aka 4.5.2-b2

**Comment by Rsl1122** [comment]
Still trying to figure it out the problem with the empty values - It seems to work sometimes and sometimes it doesn't.

Thanks for reporting.

**Comment by SlimeDog** [comment]
No worries. I populated them manually, from backups and diffs. But it would be a large concern for operators less skilled in backup and testing fundamentals.

**Comment by TheFlagCourier** [comment]
![untitled](https://user-images.githubusercontent.com/2712890/50458785-6d175480-092b-11e9-85f0-01f1f48b7f6f.png)
The YAML is also invalid, according to Js-YAML, and [PyYaml](http://yaml-online-parser.appspot.com/)

**Comment by Rsl1122** [comment]
Yes the yaml does not follow convention to allow better configuration in cases where some feature needs to have a toggle (Alternative IP) and where a number needs a time unit (Time)

Linters want each node with a value to be a leaf while I want some trunk nodes to have values as well.

The unconventional yml format has been in use for about 8 months.

**Comment by Rsl1122** [comment]
This issue should be fixed with DEV3.

I'm a bit uncertain though, since it kept happening on my linux laptop and every test I threw at it passed.
Now it didn't happen on my Windows machine so it is either fixed or occurs randomly.
