### ISSUE TITLE
Add an Event that get called when running /plan reload - "PlanReloadEvent"

### ISSUE THREAD

**Issue by Poslovitch** [Rsl1122/Plan-PlayerAnalytics#845]
### Is your feature request related to a problem? Please describe.
I'm planning to do #722, but I need to know when Plan gets reloaded in order to reload BentoBox's hook.

### Describe the solution you'd like
Add an event called `PlanReloadEvent`. Or whatever the name.

**Comment by Rsl1122** [comment]
Implemented an event that fires when Plan is enabled. This will be available in 4.6.0

See the above commit message for class names.

**Comment by Poslovitch** [comment]
Great, thanks :thumbsup:
