### ISSUE TITLE
Integration for SkyblockEarth?

### ISSUE THREAD

**Issue by lukeeexd** [Rsl1122/Plan-PlayerAnalytics#853]
https://www.spigotmc.org/resources/skyblockearth-1-8-x-1-13-x.61976/

https://songoda.atlassian.net/wiki/spaces/SON/pages/24281109/SkyBlockEarth

**Comment by Rsl1122** [comment]
Thank you for the suggestion.
I looked into how their API is implemented to assess viability.

The API uses `Player` objects which are the code representation of online players.
so this is not very viable addition for the current plugin data system.
