### ISSUE TITLE
Cloudnet Support

### ISSUE THREAD

**Issue by Nevercold** [Rsl1122/Plan-PlayerAnalytics#856]
Is it possible to install cloudnet support? (https://github.com/CloudNetService/CloudNet & https://www.spigotmc.org/resources/cloudnet-the-cloud-network-environment-technology.42059/) on GitHub is Still the version V2, on Spigot V3. It would be good if support for both versions. since CloudNet has a template system, I can not always set the server to a different port in the config.

**Comment by Rsl1122** [comment]
Please be more specific. I do not understand what cloudnet support means.

What would Plan have to do for it to support Cloudnet?

**Comment by Rsl1122** [comment]
Closing this issue as stalled as no reply was given.

I have no idea what to do with it.
