### ISSUE TITLE
500 Internal Error Ocurred

### ISSUE THREAD

**Issue by krisjenner** [Rsl1122/Plan-PlayerAnalytics#857]
### Describe the bug

I connect to the address that I normally use for Plan but I have the following error.

### Server information

Sponge7.1.5 MC 1.12.2 Forge 2768

### Exceptions & Other Logs

/plan/logs empty

### Additional information

[Error on page](https://gist.github.com/krisjenner/fdb37edd6d42f079beadb629105f50d0)
**Frequency of occurrence**: <>

**Other:**

**Comment by Rsl1122** [comment]
What database are you using?

**Comment by Rsl1122** [comment]
Closing ticket as stalled.
