### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DarkFort** [Rsl1122/Plan-PlayerAnalytics#878]
https://hastebin.com/ohiweqenic.sql
Paper version git-Paper-1562 (MC: 1.12.2)
Plan version 4.5.2

**Comment by DarkFort** [comment]
https://hastebin.com/icatifuzab.md

**Comment by Rsl1122** [comment]
Please open new issue for different errors in the future.

First error has been fixed in 4.6.0 DEV3 (can be found under releases)

Second error is this https://github.com/Rsl1122/Abstract-Plugin-Framework/issues/20 and is still being fixed.

Closing this issue.
