### ISSUE TITLE
You do not have the required permission

### ISSUE THREAD

**Issue by Stager83** [Rsl1122/Plan-PlayerAnalytics#886]
### Describe the bug
I have managed to setup the plugin and it works fine on my individual servers and has no issues when navigating the web ui either. however I am unable to perform the command /planbungee setup as it stats I do have the required permission. I am OP on all the servers.

### Server information
I am running 5 servers in total. 3 x Spigot 1.13.2 severs for towny, survival and skyblock. 1 x Spigot 1.13.2 server for lobby and 1 x Spigot Bungeecord server as proxy to connect all servers. 

### Additional information
I have followed the directions for setting up for bungeecord and as described all the other servers run the plugin fine when I visit their ip address and port (ip:8804) but the issue is that I cannot connect them using the command above due to the permission error.

**Comment by Rsl1122** [comment]
`/planbungee setup` requires `plan.*` permission which defaults to false (Not given to OP by default)

You can use the command on the BungeeCord console or give yourself the permission.

**Comment by Stager83** [comment]
I have managed to get this done however I am getting an 500 internal error on the bungeecord web ui but not on the other servers ui? I would create a new ticket with the link but I see I cannot mark an issue as private here?

**Comment by Rsl1122** [comment]
500 usually comes with an exception stactrace, please open a new issue with the error in it
