### ISSUE TITLE
Updated from 4.5.2 to 4.6.1 and infinate errors.

### ISSUE THREAD

**Issue by FrozenBeard** [Rsl1122/Plan-PlayerAnalytics#893]
Latest Paper 1.12.2

Snippet of server log of errors from plan:
https://pastebin.com/YS6fHr2k

**Comment by Rsl1122** [comment]
Patches have not finished applying leading to these exceptions.

It's because the patches need to be run async on database start and I can't prevent other queries from running before that..

I'm working on it in #818 but it will take a while.

**Comment by FrozenBeard** [comment]
Alright, I backdated to 4.5.2 for now, hopefully it didn't change the database schema!

**Comment by Rsl1122** [comment]
If you are able to test on a non production server [4.7.0-DEV1](https://github.com/Rsl1122/Plan-PlayerAnalytics/releases/tag/4.7.0-DEV1) is available with changes that should resolve this issue
