### ISSUE TITLE
Mobile Design is buggy

### ISSUE THREAD

**Issue by DeepRobin** [Rsl1122/Plan-PlayerAnalytics#895]
### Describe the bug

The chart is not sized correctly. The hole page is not sized correctly. Please fix this, because i want see the statistics on my mobile.

![screenshot_20190121-220604](https://user-images.githubusercontent.com/10373452/51556501-a1265c80-1e7a-11e9-85b1-0b010d7036f5.png)

### Exceptions & Other Logs

No exceptions available (visual bug)

### Additional information

**Frequency of occurrence**: <>

**Comment by Rsl1122** [comment]
What browser are you using?

**Comment by DeepRobin** [comment]
Chrome for mobile. But i think its not the browser, i think it is currently not responsive.

**Comment by DeepRobin** [comment]
(Chrome)

**Comment by DeepRobin** [comment]
On my pc its on some pages buggy, too (Chrome, the latest version, too) 
![image](https://user-images.githubusercontent.com/10373452/51561214-f1a3b700-1e86-11e9-914e-5fa633edf3dc.png)

**Comment by Rsl1122** [comment]
This appears to be an issue with a recent fix for "No Servers" message not appearing - There is likely a misplaced `<div>` tag somewhere in the generated code for "No Servers" box.

Try connecting a Bukkit or Sponge server to temporarily fix this issue until a proper fix is out.

**Comment by DeepRobin** [comment]
okay, if the fix is out please mark this issue in your commit.

**Comment by Rsl1122** [comment]
Will do.
