### ISSUE TITLE
GeoLocation stores only country?

### ISSUE THREAD

**Issue by fjeddy** [Rsl1122/Plan-PlayerAnalytics#898]
Hello again,

Another "feature", "question", "bug"; I'm not sure.

But it seems like the GeoIP database your using is only storing the country? Is that correct? And if so, why? For a server running in a single country, where 99% of the players are from within that country, then storing the country alone is quite pointless?

Any specific reason why the city database isn't used instead of country one? I tried replacing the database with the city database but simply get "Not known" in the db, I assume this is due to how the API is implemented.

**Comment by Rsl1122** [comment]
Indeed only country is stored because of two reasons:
- The map in use does not use cities
- IP based city location was inaccurate when tested

**Comment by fjeddy** [comment]
City has always been unreliable with the lite databases. Having a 75%
chance of a correct match. Buy 75% is really better then 0 isn't it?

Besides. Even tho the city might be inaccurate, then the country still is :)

Den ons. 23. jan. 2019, 07.58 skrev Risto Lahtela <notifications@github.com:

**Comment by Rsl1122** [comment]
You can probably manipulate the geoip database by replacing the country row with cities instead.

**Comment by Rsl1122** [comment]
You weren't there man :)
