### ISSUE TITLE
Console error mentioning mcMMO

### ISSUE THREAD

**Issue by doitliketyler** [Rsl1122/Plan-PlayerAnalytics#904]
### Describe the bug
This error relating to the new mcMMO Overhaul plugin is happening on startup:
https://hastebin.com/zogoxaqiwa

### Server information
https://hastebin.com/ojewedovuj

Any idea what is going on here?

**Comment by Rsl1122** [comment]
The revamped plugin does not have the same class structure as the old one, but has the class Plan uses for detection in the same place. 

The new revamped plugin is not supported, set `Plugins.McMMO.Enabled` to `false` in the Plan config to stop the error.

**Comment by Rsl1122** [comment]
If you would like to have support for the new plugin be added, please send the required information over on issue https://github.com/Rsl1122/Plan-PlayerAnalytics/issues/583

**Comment by doitliketyler** [comment]
I'll do that now. Thanks
