### ISSUE TITLE
Apparent connection leak detected

### ISSUE THREAD

**Issue by runescapejon** [Rsl1122/Plan-PlayerAnalytics#929]
### Describe the bug

My console kept spamming with this error `Apparent connection leak detected`. Please know that i had ran this plugin into a test server with no other plugins installed and it still happen my server versions are
- spongeforge-1.12.2-2768-7.1.6-RC3596
- plan 4.6.2

Please tell me if you need any more information. Oh I also have mariadb as mysql.
### Exceptions & Other Logs

https://pastebin.com/raw/TLfhj5ap

### Additional information

**Frequency of occurrence**: <>

**Other:**

**Comment by Rsl1122** [comment]
It's probably caused by the old HikariCP version Sponge uses (2.6.3).

I'll try to move Plan to use the HikariCP included within Plan that other servers use (3.3.0) on Sponge as well.
