### ISSUE TITLE
Database Patching failed, plugin has to be disabled. Please report this issue

### ISSUE THREAD

**Issue by FrozenBeard** [Rsl1122/Plan-PlayerAnalytics#939]
I've not been able to get plan to work at all since my #893 the data will not update.

using paper 1.12.2 : git-Paper-1596
using plan 4.6.2

Errors on boot:
https://gist.github.com/FrozenBeard/98136b9a9f240245fd6adcef68077054

**Comment by Rsl1122** [comment]
Please check if the database has a `temp_kills` table.
If it does, please send results of `DESCRIBE temp_kills`

After that you can attempt the temporary fix described in the issue #934 (This issue looks pretty similar to that one)

**Comment by FrozenBeard** [comment]
Yeah it does.

![screenshot 2019-03-01 at 15 35 27](https://user-images.githubusercontent.com/144046/53648400-b770c680-3c37-11e9-895b-8c66fc99b697.png)

**Comment by Rsl1122** [comment]
The second solution in #934 should temporarily fix the issue.

If the temp_kills table shows up again after you start the plugin again, please send the full enable log for the plugin

**Comment by FrozenBeard** [comment]
I run that SQL query line by line, then I also updated to 4.7.0, which no longer shows errors on boot!
What is weird is in the server logs it now says `Webserver running on PORT` when I disabled my web-server in favour of hosting the static files myself. 
So this boot issue seems solved, I will see you in #905 where I don't get a website!

**Comment by Rsl1122** [comment]
It sounds like the config is out of date in some small way that the config patching has not managed to resolve.

Ensure that these settings (case sensitive) have values that you would prefer them to have:
`Webserver.Disable_Webserver`, `Export.HTML_Export_path`, `Export.Parts.<part>`

**Comment by FrozenBeard** [comment]
Yeah, it overwrote some of the config options, I edited it again to get it back to how I had it setup! Thanks.
