### ISSUE TITLE
Plan 4.7.0 /network page parsing error

### ISSUE THREAD

**Issue by mercurialmusic** [Rsl1122/Plan-PlayerAnalytics#942]
### Describe the bug
I navigate to our usual access page and I get a Plan page with a 500 Internal Error with the following: 
https://gist.github.com/mercurialmusic/47938c521a6fd300568681a41f9ede25

The /plan reload command does not seem to work on the proxy with a "Command not found". 
The current version also seems to be extremely resource heavy despite the above not working - memory on the **bungee** has been maxed out since the 4.7.0 install, where previously it barely registers any being used. This Plan update is the only change.

Restarting has no effect on the described outcome.

I do not get the same errors on the Spigot servers, but I am not able to access those webservers individually either -- but I haven't tried accessing these individually since we enabled https so I'm guessing that's related.

### Server information
Bungee build 1397

Spigot version: CraftBukkit version git-Spigot-3cb9dcb-0f708cb (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by Rsl1122** [comment]
Hello.

> The /plan reload command does not seem to work on the proxy 

On Bungee the command to use Plan is `/planbungee reload` (To avoid conflict on a spigot server).

>  I am not able to access those webservers individually either -- but I haven't tried accessing these individually since we enabled https so I'm guessing that's related.

When using https `https://` needs to be included in the address

----

4.6.2 is compatible with 4.7.0 so I recommend downgrading (bungee) until the first bug has been fixed.

I was not able to reproduce the memory usage, could you open another issue with the following information:
- a memory dump if possible
- JVM flags
- How many servers are running Plan that are connected

**Comment by mercurialmusic** [comment]
> On Bungee the command to use Plan is /planbungee reload (To avoid conflict on a spigot server).

Derp. Sorry. This at least does reload it and the reload itself seems normal. The outcome with the error is unchanged.

> When using https https:// needs to be included in the address

I had been using this. The first time I got the standard Chrome "this page failed to load" error, but trying it again it's working now. Or at least it went to the "Analysis is being run" page, which it has been on for a few minutes now. 

> I was not able to reproduce the memory usage, could you open another issue with the following information:
> 
> a memory dump if possible
> JVM flags
> How many servers are running Plan that are connected

It's a hosted server unfortunately, so I'm not sure how to get the memory dump or the flags, but there are 3 servers running plan that are connected. This was not an issue with 4.6.2.

> 4.6.2 is compatible with 4.7.0 so I recommend downgrading (bungee) until the first bug has been fixed.

I will do that, thank you.

**Comment by Rsl1122** [comment]
Alright since there isn't a possibility for a memory dump, could you tell me how much is maxed out? :)

**Comment by mercurialmusic** [comment]
So we have BeastNode and Multicraft, which gives only a percentage meter for RAM use. We have 1GB RAM allotted to the Bungee, and it was running at 100% when typically it runs at around 10%. I can see that about the analysis being run, though -- just when something goes wrong I get hyper-sensitive about anything else that may seem unusual and try to provide as much info as I can, even if it's useless. =p Everything seems to be fine after downgrading to 4.6.2 on the Bungee, and no problems with the Bungee on 4.6.2 and the Spigot servers on 4.7.0, so thanks again for that.

**Comment by Rsl1122** [comment]
I'm trying to figure out the cause of the parsing error, could you run the following SQL and send me the result

```
SELECT geolocation, COUNT(1) FROM (
    (SELECT uuid, geolocation, last_used FROM plan_ips) as q1
    INNER JOIN 
    (SELECT uuid, MAX(last_used) as m FROM plan_ips GROUP BY uuid) as q2
    ON q1.uuid = q2.uuid)
WHERE last_used=m
GROUP BY geolocation;
```

**Comment by Rsl1122** [comment]
Here is a jar that includes the fix:
[Plan-4.7.0#942.zip](https://github.com/Rsl1122/Plan-PlayerAnalytics/files/2924872/Plan-4.7.0.942.zip)

The error was caused by two unknown countries mapping to null since no hardcoded geocode exists for them.
