### ISSUE TITLE
MinecraftAnalytics.plan_world_times.server_uuid' isn't in GROUP BY

### ISSUE THREAD

**Issue by lmitchel** [Rsl1122/Plan-PlayerAnalytics#943]
When running version 4.7.0 I receive the following error:
MinecraftAnalytics.plan_world_times.server_uuid' isn't in GROUP BY
Similar to https://github.com/Rsl1122/Plan-PlayerAnalytics/issues/900

### Server information
Server is Debian Stretch, MySQL version 10.1.37.  I know there is a newer version of MariaDB (10.3) but it is not in the official Debian Stretch repository and is not a simple or trivial upgrade. It will require further investigation to ensure it won't break my other applications.

### Exceptions & Other Logs
Caused by: com.djrapitops.plan.api.exceptions.database.DBOpException: SQL Failed: SELECT SUM(survival_time) as survival, SUM(creative_time) as creative, SUM(adventure_time) as adventure, SU
M(spectator_time) as spectator, plan_world_times.server_uuid, plan_worlds.world_name as world FROM plan_world_times INNER JOIN plan_worlds on plan_worlds.id=world_id WHERE plan_world_times.
server_uuid=? GROUP BY world; 'MinecraftAnalytics.plan_world_times.server_uuid' isn't in GROUP BY

**Frequency of occurrence**: <>
Every time it is run or updated
Worked in 4.6.2

**Comment by Rsl1122** [comment]
I'll look into it. 

PS: please include the full stacktrace in the future. I am able to find the sql statement I  the code, but it always helps being able to see which file and line caused it.

**Comment by Rsl1122** [comment]
Here is a version with this bugfix applied to it 
[Plan-4.7.0#943.zip](https://github.com/Rsl1122/Plan-PlayerAnalytics/files/2930740/Plan-4.7.0.943.zip)
