### ISSUE TITLE
Unsupported Key: player_death_count on Server JSON Export

### ISSUE THREAD

**Issue by FrozenBeard** [Rsl1122/Plan-PlayerAnalytics#948]
Updated to 4.7.0 today and got my plan re-working.

Im getting these errors in console now:
https://gist.github.com/FrozenBeard/db1ff73f48c3d38419bd7b4e2cf0c55e

**Comment by Rsl1122** [comment]
Here is a jar with the fix 
[Plan-4.7.0#948.zip](https://github.com/Rsl1122/Plan-PlayerAnalytics/files/2931417/Plan-4.7.0.948.zip)

**Comment by FrozenBeard** [comment]
Thanks man, amazing fast fix!
