### ISSUE TITLE
Server UUID error

### ISSUE THREAD

**Issue by MicleBrick** [Rsl1122/Plan-PlayerAnalytics#957]
This error prints the first (few?) time(s?) an an analysis is attempted to be created after a restart or `/plan reload`: https://gist.github.com/MicleBrick/a67305f954f3ef88fb0f70a9c74f1802

**Comment by Rsl1122** [comment]
Possible side-effect of database not initializing correctly before call to `getServerUuid` - Database queries are blocked until the database patches, so ServerInfo might not have been fetched.

Related:
There might be an issue where queries passed to a closed database are blocked indefinitely.

**Comment by Rsl1122** [comment]
Fixed in commit 0ed86b532c0035bc51c0fb2b1fafecce566d9df6 while fixing another bug
