### ISSUE TITLE
Export not exporting players

### ISSUE THREAD

**Issue by FrozenBeard** [Rsl1122/Plan-PlayerAnalytics#958]
Server: This server is running Paper version git-Paper-1606 (MC: 1.12.2) 
Plan: 4.7.0

The player pages are not being exported, opening up my Export/player directory, I have 6300+ pages that are all from 2018 and the bottom left reports "Player Analytics: v4.1.7" What is the trigger for a player page to be generated? I havnet had plan working for a long time and only got it back up and running yesterday! Shall I delete all these old player pages?

Title was JSON wasn't exporting either, but I just noticed your 4.7.1 fixed the JSON export! Since there's no mention in the changelogs of the exporting of player pages being solved, I created this anywho.

My configs
https://gist.github.com/FrozenBeard/ece3878379081e509f9c6667652d98a3

**Comment by Rsl1122** [comment]
Hmm, I think the issue is caused by a change introduced in 4.4.6

> - Reduced memory usage:
>   - Player page now rendered on demand instead of on login status change

This means that the page (and JSON) is only generated on `/plan inspect` command or when `/player` page would be accessed on the Plan WebServer.

This is a design flaw.
I'll look into it.

**Comment by FrozenBeard** [comment]
Thanks for the amazing fast response and figuring it out.
I have quite a few players (10,263 in the plan_users table, and 210,000 in total ever joined), it might be a little intensive to generate on login, I tend to only generate the exports when I need them and have /plan analyze on a cron job to run twice a day. 
My idea is a bit of work, I would export JSON as its lightweight and just text, no HTML to generate, then I would use Javascript to pull the JSON async inside a HTML page to display it, so you are not having to generate HTML each time, the JSON gets updated and the HTML wont have to re-generate as its pulling from the JSON data via Javascript client side.

**Comment by Rsl1122** [comment]
Generating a player's page takes about 700ms on my machine.
I think that updating the player's file when they login/logout is a lot more efficient than running the export for all players at the same time. 

I'll make it configurable.

**Comment by FrozenBeard** [comment]
Sounds awesome to me man, I'll run the real world tests for, if I throw on debug does it record timings?

**Comment by Rsl1122** [comment]
It does record the timings at all times, but putting on debug logs the results somewhere too.

The timings are available on the `/debug` page if you hvve Plan webserver enabled.

**Comment by FrozenBeard** [comment]
Bump.
Screenshot from today, the players folder and all users haven't been updated since 2018 in the export folder.

![Screenshot 2019-07-01 at 11 38 08](https://user-images.githubusercontent.com/144046/60430451-3fbaa480-9bf5-11e9-87ba-d5702e342edc.png)

**Comment by Rsl1122** [comment]
Have you enabled Export.Export_player_on_login_and_logout` setting or ran `plan m export players` command? @FrozenBeard

**Comment by FrozenBeard** [comment]
Nope! Silly me haha!
