### ISSUE TITLE
[Sponge] Permissions issue

### ISSUE THREAD

**Issue by XakepSDK** [Rsl1122/Plan-PlayerAnalytics#961]
Sponge permission are tree based.
Permission `plan` in sponge equals to `plan.*` in bukkit.
According to this page, https://github.com/Rsl1122/Plan-PlayerAnalytics/wiki/SSL-Certificate-%28HTTPS%29-Set-Up
If player has permission `plan.inspect`, then he would get level `2` when registering, but tree `plan.inspect` includes `plan.inspect.others`, so, player would get level `1`.

**Comment by Rsl1122** [comment]
Looks like I have forgotten to update the permissions, the correct permission is `plan.inspect.base`

**Comment by Rsl1122** [comment]
The documentation has been updated to match what the plugin uses for permissions.
(`plan.inspect.base` has been in use since 4.4.6 https://ore.spongepowered.org/Rsl1122/Plan/versions/4.4.6)
