### ISSUE TITLE
Feature request: Indicate current HTML page

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#99]
**Plan Version:** 3.2.1
**Server Version:** any
**Database Type:** any
**Command Causing Issue:** None

**Description:**
1. Indicate the current HTML page. Probably best in the (left) sidebar.
2. Add a title to the page, based on the options in the left sidebar.

**Comment by Rsl1122** [comment]
Could you describe it a bit more?
Currently it says in the title "Analysis" or "Inspect" & Also on the Header
Html files are analysis.html & player.html respectively.

**Comment by Rsl1122** [comment]
I'll write some Javascript to keep the current tab highlighted.

**Comment by SlimeDog** [comment]
Thanks. That will be sufficient. I'll modify based on that if I want to display the current tab value at the top of the page.

**Comment by SlimeDog** [comment]
Confirmed. Thanks for quick turnaround.
